export type SpecialistFlow={id:string;domain:string;goal_types:string[];keywords:string[];questions:string[];evidence:string[];completion:string;planning_lens:string};

export const SPECIALIST_FLOWS:SpecialistFlow[]=[
{id:'running',domain:'Sports',goal_types:['Running'],keywords:['run','running','5k','5 km','10k','10 km','marathon','half marathon','jog'],questions:['What distance, pace or event outcome are you targeting?','What is your most recent verified running baseline?','What training constraints, surfaces, recovery limits or equipment matter?'],evidence:['distance','pace','time','heart-rate or effort where useful','completed runs'],completion:'the stated running target is achieved or the intended participation outcome is completed',planning_lens:'running-specific progression, pacing, recovery and benchmark testing'},
{id:'cycling',domain:'Sports',goal_types:['Cycling'],keywords:['cycle','cycling','bike','biking','ride','riding','kilometre','kilometer'],questions:['What cycling outcome are you targeting?','What is your current riding baseline?','What terrain, bike setup, recovery or safety constraints matter?'],evidence:['distance','duration','speed','elevation','ride completion'],completion:'the stated cycling outcome is achieved',planning_lens:'cycling-specific endurance, pacing, terrain and bike-handling progression'},
{id:'football',domain:'Sports',goal_types:['Football'],keywords:['football','soccer','dribbling','passing','shooting','defending','goalkeeper'],questions:['What position, skill or match outcome are you targeting?','What can you reliably do now?','Where and with whom can you practise, and what equipment is available?'],evidence:['drills completed','technical accuracy','match observations','training sessions'],completion:'the target football skill or match outcome is demonstrated',planning_lens:'position-specific technical practice, decision making and match transfer'},
{id:'basketball',domain:'Sports',goal_types:['Basketball'],keywords:['basketball','layup','free throw','three point','dribble'],questions:['Which basketball skill or performance result matters most?','What is your current measurable baseline?','What court, hoop and practice access do you have?'],evidence:['made shots','repetition quality','practice sessions','game outcomes'],completion:'the target basketball capability is demonstrated',planning_lens:'basketball skill isolation, repetition quality, game-speed transfer'},
{id:'tennis',domain:'Sports',goal_types:['Tennis'],keywords:['tennis','serve','forehand','backhand','racket','racquet'],questions:['Which stroke, tactical skill or match outcome are you targeting?','What is your current level and typical errors?','What court, partner or coach access do you have?'],evidence:['serve/rally outcomes','drill completion','match notes','feedback'],completion:'the target tennis capability is demonstrated under realistic play',planning_lens:'stroke mechanics, movement, point construction and feedback loops'},
{id:'swimming',domain:'Sports',goal_types:['Swimming'],keywords:['swim','swimming','pool','freestyle','backstroke','breaststroke','butterfly','laps'],questions:['What distance, stroke or time outcome are you targeting?','What is your current swim baseline?','What pool access, technique constraints or safety considerations matter?'],evidence:['distance','time','stroke efficiency','completed sets'],completion:'the target swim capability or distance outcome is demonstrated',planning_lens:'technique, repeatable sets, pacing and water-specific conditioning'},
{id:'cooking',domain:'Practical Skills',goal_types:['Cooking'],keywords:['cook','cooking','culinary','recipe','bake','baking','pasta','ravioli','dough','filling','sauce','meal'],questions:['What exact dish, cuisine or cooking capability are you trying to achieve?','What is your cooking experience with this type of dish?','What ingredients, tools, equipment, dietary constraints or serving quantity matter?'],evidence:['ingredient preparation','technique execution','dish completion','taste/texture checks'],completion:'the exact culinary outcome is prepared to the stated standard',planning_lens:'dish-specific mise en place, technique order, equipment adaptation and quality checks'},
{id:'woodworking',domain:'Practical Skills',goal_types:['Woodworking'],keywords:['woodworking','woodwork','carpentry','furniture','saw','joinery'],questions:['What are you making and what standard must it meet?','What tools and previous woodworking experience do you have?','What material, workspace and measurement constraints matter?'],evidence:['measurements','cuts','joints','assembly','finished object'],completion:'the intended build is complete and meets its acceptance criteria',planning_lens:'measurement, tool safety, joining sequence and staged build verification'},
{id:'languages',domain:'Languages',goal_types:['Language Learning'],keywords:['french','spanish','german','italian','portuguese','arabic','swahili','japanese','korean','mandarin','language','fluent','vocabulary'],questions:['What can you currently understand and say in the language?','What real-world use case do you want to reach?','Which skill matters most: speaking, listening, reading, writing or a balance?'],evidence:['comprehension','speaking samples','writing samples','vocabulary recall','real-world conversations'],completion:'the stated communication capability is demonstrated in a realistic context',planning_lens:'input-output balance, retrieval, communicative practice and increasing contextual complexity'},
{id:'academic-study',domain:'Education',goal_types:['Academic Study'],keywords:['study','studying','revision','revise','exam','homework','physics','chemistry','biology','maths','mathematics','history','geography','economics'],questions:['What exact syllabus, topic or assessment are you preparing for?','What do you already know and where are the gaps?','What exam date, mark target or resource constraints matter?'],evidence:['diagnostic questions','practice accuracy','retrieval results','completed papers'],completion:'the required academic standard is demonstrated',planning_lens:'diagnosis, retrieval, worked practice, error correction and assessment simulation'},
{id:'programming',domain:'Technology/Projects',goal_types:['Programming'],keywords:['code','coding','programming','python','javascript','typescript','java','c++','html','css','software','app','website','web development'],questions:['What exact software outcome or capability are you targeting?','What is already working and what is not?','What stack, environment, dependencies and acceptance criteria constrain the work?'],evidence:['working features','tests','commits','bugs resolved','deployments'],completion:'the software outcome passes its defined acceptance criteria',planning_lens:'acceptance criteria, dependency order, small working increments, tests and shipping'},
{id:'engineering',domain:'Technology/Projects',goal_types:['Engineering'],keywords:['engineering','mechatronics','robotics','arduino','cad','prototype','electronics','mechanical','3d print'],questions:['What physical or technical outcome are you building?','What components, measurements and current prototype state exist?','What tools, tolerances, budget or safety constraints matter?'],evidence:['prototype iterations','test measurements','schematics','working subsystems'],completion:'the engineering outcome passes its required functional tests',planning_lens:'requirements, subsystem dependencies, prototyping, testing and iteration'},
{id:'reading',domain:'Reading',goal_types:['Reading'],keywords:['read','reading','book','books','novel','pages','chapter'],questions:['Why are you reading this material?','What material and difficulty are you choosing?','Do you care more about speed, comprehension, retention or finishing?'],evidence:['pages','chapters','reading time','notes','comprehension checks'],completion:'the defined reading outcome is completed with the intended understanding',planning_lens:'reading purpose, sustainable pace and comprehension feedback'},
{id:'writing',domain:'Creative Skills',goal_types:['Writing'],keywords:['write','writing','story','short story','novel','poetry','poem','screenplay','essay'],questions:['What exact piece are you trying to finish?','What genre, audience, tone or reference style matters?','What stage are you at: idea, outline, draft, revision or final?'],evidence:['outline','drafts','revisions','feedback','finished piece'],completion:'the defined written piece is finished to its stated standard',planning_lens:'ideation, structure, drafting, revision and feedback'},
{id:'drawing',domain:'Creative Skills',goal_types:['Drawing'],keywords:['draw','drawing','sketch','sketching','illustration'],questions:['What are you trying to draw or become able to draw?','What is your current skill level?','Which medium, reference style and tools will you use?'],evidence:['studies','drawings','proportion checks','finished pieces'],completion:'the target drawing outcome or capability is demonstrated',planning_lens:'observation, proportion, construction, value, composition and finished studies'},
{id:'painting',domain:'Creative Skills',goal_types:['Painting'],keywords:['paint','painting','watercolour','watercolor','acrylic','oil painting','canvas'],questions:['What are you trying to paint?','What medium and current experience do you have?','What style, palette, surface and workspace constraints matter?'],evidence:['studies','colour mixes','paintings','critiques'],completion:'the target painting is completed to the stated standard',planning_lens:'medium-specific technique, colour/value studies, composition and finished work'},
{id:'photography',domain:'Creative Skills',goal_types:['Photography'],keywords:['photography','photograph','camera','portrait','street photography'],questions:['What kind of photographs are you trying to create?','What camera or phone and current skill level do you have?','What lighting, location and editing constraints matter?'],evidence:['shoots','selected images','technical checks','feedback'],completion:'the target photographic result or capability is demonstrated',planning_lens:'exposure/focus, composition, controlled shoots, selection and editing'},
{id:'music',domain:'Creative Skills',goal_types:['Music'],keywords:['music','piano','guitar','keyboard','drums','violin','ukulele','singing','vocals','instrument'],questions:['What instrument or musical capability are you targeting?','What can you play or perform now?','What instrument access, genre and practice environment do you have?'],evidence:['practice sessions','technique exercises','pieces performed','recordings'],completion:'the target musical capability or performance is demonstrated',planning_lens:'technique, repertoire, deliberate practice and performance evidence'},
{id:'crochet',domain:'Creative Skills',goal_types:['Crochet'],keywords:['crochet','crocheting','amigurumi','crochet hook'],questions:['What are you trying to make or learn?','What stitches and techniques can you already do?','What yarn, hook and pattern constraints matter?'],evidence:['stitches','swatches','finished projects'],completion:'the stated crochet outcome is completed',planning_lens:'stitch foundations, tension, construction and project transfer'},
{id:'knitting',domain:'Creative Skills',goal_types:['Knitting'],keywords:['knit','knitting','purl','cast on','knitting needles'],questions:['What are you trying to knit?','Which techniques can you already perform?','What yarn, needle and pattern constraints matter?'],evidence:['swatches','stitch control','shaping','finished projects'],completion:'the stated knitting outcome is completed',planning_lens:'stitch control, tension, shaping and project transfer'},
{id:'public-speaking',domain:'Communication',goal_types:['Public Speaking'],keywords:['public speaking','presentation','speech','presenting','debate'],questions:['What real presentation or speaking situation are you preparing for?','What currently goes wrong or feels weakest?','What audience, length and feedback source will you have?'],evidence:['rehearsals','recordings','timing','feedback'],completion:'the target speaking performance is delivered to the required standard',planning_lens:'message structure, delivery, rehearsal and audience simulation'},
{id:'finance',domain:'Finance',goal_types:['Saving'],keywords:['save','saving','savings','money','budget','financial','finance'],questions:['What exact financial outcome are you trying to reach?','What is your current baseline and realistic contribution?','What expenses, deadlines and non-negotiables constrain the plan?'],evidence:['balances','saving milestones','budget adherence'],completion:'the stated financial target or behaviour is reached',planning_lens:'controllable actions, milestones, behaviour review and adjustment'},
{id:'meditation',domain:'Mindfulness',goal_types:['Meditation'],keywords:['meditate','meditation','mindfulness','breathing'],questions:['What change are you hoping meditation will support?','What is your current practice, if any?','What session length and environment are realistically available?'],evidence:['sessions','duration','self-reported response','consistency'],completion:'the intended practice or outcome is established and evidenced',planning_lens:'sustainable practice, gradual consistency and reflection'},
{id:'travel',domain:'Travel',goal_types:['Travel Planning'],keywords:['travel','trip','itinerary','destination','holiday','flight','abroad'],questions:['Where are you going and what is the purpose of the trip?','What dates, budget and must-haves are fixed?','What documents, bookings, transport or contingency constraints matter?'],evidence:['confirmed bookings','completed checklist','itinerary completeness'],completion:'the trip is prepared to the stated standard',planning_lens:'hard constraints, dependency order, bookings and final readiness'},
{id:'career',domain:'Career/Projects',goal_types:['Career Development','Project'],keywords:['career','cv','resume','job','application','internship','portfolio','interview'],questions:['What exact opportunity or outcome are you targeting?','What evidence or requirements do you currently have?','What deadlines, contacts and constraints matter?'],evidence:['applications','interviews','portfolio deliverables','milestones'],completion:'the stated career outcome or acceptance criteria are met',planning_lens:'requirements, evidence-producing actions, dependencies and review'},
];

export function specialistFor(input:{title?:string|null;category?:string|null;goal_type?:string|null}):SpecialistFlow|null{const text=[input.title,input.category,input.goal_type].filter(Boolean).join(' ').toLowerCase();return SPECIALIST_FLOWS.find(flow=>flow.keywords.some(k=>text.includes(k)))||SPECIALIST_FLOWS.find(flow=>flow.goal_types.some(k=>k.toLowerCase()===(input.goal_type||'').toLowerCase()))||null;}
