export type DomainFlow = {
  id: string;
  category: string;
  goal_types: string[];
  keywords: string[];
  discovery_questions: string[];
  evidence: string[];
  metrics: string[];
  integrations: string[];
  research_focus: string[];
  progression: string;
};

const flow = (value: DomainFlow) => value;

export const DOMAIN_FLOWS: DomainFlow[] = [
  flow({id:'sports-running',category:'Sports',goal_types:['Running'],keywords:['run','running','5k','10k','half marathon','marathon','mile'],discovery_questions:['What is your current running baseline?','What exact performance outcome are you targeting, and by when?','What usually limits your running right now?'],evidence:['distance','pace','time','heart rate','sessions','race results'],metrics:['pace','distance','duration','frequency','PB','training load'],integrations:['Strava'],research_focus:['training progression','pacing','recovery','race preparation'],progression:'Progress from the user baseline and adapt from observed performance and recovery.'}),
  flow({id:'sports-cycling',category:'Sports',goal_types:['Cycling'],keywords:['cycle','cycling','bike','biking','ride','kilometre','kilometer'],discovery_questions:['What is your current riding baseline?','What outcome matters most: distance, speed, climbing, endurance, skill, or an event?','What bike, terrain, equipment, time and recovery constraints apply?'],evidence:['ride distance','duration','speed','elevation','sessions'],metrics:['distance','duration','average speed','elevation','frequency'],integrations:['Strava'],research_focus:['endurance progression','pacing','cycling skills','recovery'],progression:'Increase volume, intensity or technical demand one controlled step at a time.'}),
  flow({id:'sports-football',category:'Sports',goal_types:['Football'],keywords:['football','soccer','match','winger','fullback','defender','midfielder','striker'],discovery_questions:['What position, level and current strengths are you working from?','Which outcome are you targeting: technical skill, fitness, tactical understanding, match performance, or role-specific development?','What training access and weekly frequency do you have?'],evidence:['training sessions','match notes','minutes','technical repetitions','fitness tests','coach feedback'],metrics:['sessions','minutes','technical success','fitness tests','match actions'],integrations:['Strava'],research_focus:['position-specific development','technical repetition','tactical decision-making','conditioning'],progression:'Move from isolated skill work to pressure, decisions and match-transfer tasks.'}),
  flow({id:'sports-swimming',category:'Sports',goal_types:['Swimming'],keywords:['swim','swimming','freestyle','backstroke','breaststroke','butterfly','pool'],discovery_questions:['What stroke, distance and current time or pace are you starting from?','What exact outcome are you targeting?','What pool access, coaching, equipment and frequency do you have?'],evidence:['distance','split times','duration','stroke data','sessions'],metrics:['pace','distance','stroke efficiency','frequency','race time'],integrations:['Strava'],research_focus:['stroke technique','intervals','aerobic development','race pacing'],progression:'Build technique first, then add repeatable volume and race-specific intensity.'}),
  flow({id:'education-learning',category:'Education',goal_types:['Study'],keywords:['study','revise','revision','exam','homework','learn','learning','physics','chemistry','biology','maths','mathematics','english','history','geography','french'],discovery_questions:['What subject or capability are you trying to master, and what is your current level?','What assessment or outcome proves success, and when is it due?','Which topics, study methods, time limits and resources matter?'],evidence:['study sessions','practice results','quiz accuracy','past-paper scores','completed topics'],metrics:['accuracy','recall','practice score','coverage','study time'],integrations:['Google Calendar'],research_focus:['retrieval practice','spaced practice','subject-specific methods','exam technique'],progression:'Prioritise weak areas, increase retrieval difficulty, then test under realistic conditions.'}),
  flow({id:'technology-coding',category:'Technology/Projects',goal_types:['Coding'],keywords:['code','coding','programming','software','developer','github','commit','pull request','repository','repo','app','website'],discovery_questions:['What are you building and what does done look like in observable terms?','What is your current technical level, stack and prototype state?','What constraints matter most: platform, time, security, design, budget or deployment?'],evidence:['commits','pull requests','tests','issues closed','releases','deployed features'],metrics:['shipped features','test coverage','bug rate','cycle time','release frequency'],integrations:['GitHub'],research_focus:['architecture','implementation','testing','security','deployment'],progression:'Move from the smallest working slice to integrated, tested and deployable increments.'}),
  flow({id:'technology-engineering',category:'Technology/Projects',goal_types:['Engineering'],keywords:['engineering','mechatronics','robotics','arduino','cad','prototype','electronics','mechanical','3d print','circuit','microcontroller'],discovery_questions:['What are you trying to make, and what functional requirement must it satisfy?','What tools, components and technical experience do you have?','What physical, electrical, cost and time constraints apply?'],evidence:['design iterations','test results','measurements','prototype revisions','build logs'],metrics:['test pass rate','dimensions','performance','cost','iteration count'],integrations:['Google Calendar'],research_focus:['requirements','prototyping','test design','component selection','failure analysis'],progression:'Define requirements, prototype cheaply, test against criteria, then iterate.'}),
  flow({id:'career',category:'Career/Projects',goal_types:['Career'],keywords:['career','cv','resume','job','application','internship','portfolio','interview','linkedin','freelance','client'],discovery_questions:['What exact career outcome are you pursuing and which role or market matters?','What evidence of readiness do you already have and what are the biggest gaps?','What opportunity, time, location and portfolio constraints apply?'],evidence:['applications','interviews','portfolio milestones','networking actions','skills evidence'],metrics:['quality applications','interviews','portfolio outputs','skill gaps closed'],integrations:['Google Calendar'],research_focus:['role requirements','portfolio evidence','application quality','interviews'],progression:'Close the highest-value readiness gaps before scaling outreach.'}),
  flow({id:'productivity',category:'Productivity',goal_types:['Task Execution'],keywords:['productive','productivity','tasks','organise','organize','routine','declutter','plan my day','focus','time management'],discovery_questions:['What exactly are you trying to get under control or accomplish?','What does a successful week look like in concrete behaviours or outputs?','What recurring obstacles, energy patterns and commitments should VOW account for?'],evidence:['completed tasks','scheduled sessions','completion rate','focus sessions'],metrics:['completion rate','consistency','focus duration','carry-over'],integrations:['Google Tasks'],research_focus:['task design','time blocking','friction reduction','attention management','review loops'],progression:'Reduce friction first, then increase consistency before workload.'}),
  flow({id:'faith',category:'Faith',goal_types:['Bible Reading'],keywords:['bible','scripture','prayer','devotion','devotional','verse','verses','christian','christ','god','jesus','faith','spiritual','church'],discovery_questions:['What are you hoping to grow in spiritually right now?','How familiar are you with the Bible, and what have you read before?','How much time and consistency can you realistically give this goal?'],evidence:['reading sessions','chapters','reflections','journal entries'],metrics:['sessions','chapters','reflection quality','consistency'],integrations:['YouVersion Bible'],research_focus:['book context','reading comprehension','historical context','reflection prompts'],progression:'Move from a personally relevant starting point to broader reading as understanding grows.'}),
  flow({id:'reading',category:'Reading',goal_types:['Reading'],keywords:['read','reading','book','books','pages','novel','nonfiction','literature'],discovery_questions:['What are you reading and why does this reading goal matter?','What is your current reading pace and comprehension level?','What genres, formats and available time help you read consistently?'],evidence:['pages','books completed','reading time','notes','completion'],metrics:['pages/day','books completed','minutes','retention notes'],integrations:['Google Books'],research_focus:['reading strategy','comprehension','note-taking','book selection','retention'],progression:'Optimise reading rhythm and comprehension before increasing volume.'}),
  flow({id:'mindfulness',category:'Mindfulness',goal_types:['Meditation'],keywords:['meditate','meditation','mindfulness','breathing','calm','reflection'],discovery_questions:['What change are you trying to create through mindfulness or meditation?','What is your current experience and what makes practice easy or difficult?','What session length, environment and style feels realistic?'],evidence:['sessions','duration','self-report','journal reflections'],metrics:['frequency','duration','consistency','self-rated focus'],integrations:['Medito'],research_focus:['mindfulness practice','attention training','habit formation','reflection'],progression:'Build a repeatable practice before extending duration or complexity.'}),
  flow({id:'health-routine',category:'Health',goal_types:['Healthy Routine'],keywords:['health','healthy','sleep','hydration','water','habit','wellness','nutrition','routine'],discovery_questions:['Which health behaviour or outcome are you actually trying to improve?','What is your current baseline and what would count as meaningful improvement?','What schedule, food, equipment or lifestyle constraints apply?'],evidence:['habit completion','sleep data','hydration logs','routines','self-report'],metrics:['frequency','duration','consistency','trend from baseline'],integrations:['Health Connect'],research_focus:['habit design','sleep routine','hydration behaviour','nutrition basics','recovery'],progression:'Change one high-leverage behaviour at a time and adapt from adherence.'}),
  flow({id:'culinary',category:'Culinary',goal_types:['Cooking & Food Skills'],keywords:['cook','cooking','recipe','ravioli','pasta','bread','bake','baking','cake','sauce','meal','dish','cuisine','knife skills','ferment','food'],discovery_questions:['What exactly are you trying to make or learn, and what end result are you aiming for?','What is your current experience with this kind of food?','What equipment, ingredients, dietary constraints, serving size, budget and kitchen time should VOW design around?'],evidence:['completed dishes','recipe attempts','taste and texture notes','timing','ingredient measurements','repeatability'],metrics:['successful attempts','timing','consistency','waste','quality feedback'],integrations:[],research_focus:['technique','ingredient function','food safety','equipment alternatives','recipe scaling','troubleshooting'],progression:'Learn the core technique, execute a controlled attempt, diagnose the result, then increase complexity or precision.'}),
  flow({id:'creative-arts',category:'Creative Arts',goal_types:['Art & Design'],keywords:['draw','drawing','paint','painting','illustration','design','graphic design','photography','photo','visual art','sketch'],discovery_questions:['What are you creating and what visual result do you want?','What is your current skill level and medium?','What tools, time, style preferences and feedback sources do you have?'],evidence:['finished works','iterations','critiques','practice hours','portfolio pieces'],metrics:['pieces completed','iteration count','skill checks','consistency'],integrations:[],research_focus:['fundamentals','composition','medium technique','art critique','reference study'],progression:'Isolate one skill, practise deliberately, then combine it in increasingly complete works.'}),
  flow({id:'music',category:'Music',goal_types:['Instrument & Music'],keywords:['guitar','piano','keyboard','drums','sing','singing','vocals','instrument','music','songwriting','chords'],discovery_questions:['What instrument or musical skill are you developing and what exact outcome do you want?','What is your current level and what can you already perform?','What instrument access, practice time, style preferences and feedback options do you have?'],evidence:['practice sessions','tempo','repertoire','recordings','technique checks'],metrics:['tempo','accuracy','repertoire pieces','practice frequency'],integrations:[],research_focus:['technique','music theory','practice structure','repertoire selection','performance preparation'],progression:'Master small technique or repertoire units, then integrate them into complete performances.'}),
  flow({id:'languages',category:'Languages',goal_types:['Language Learning'],keywords:['language','french','spanish','swahili','german','arabic','mandarin','vocabulary','speaking','grammar','fluency'],discovery_questions:['Which language and real-world use case are you targeting?','What can you currently understand, say, read and write?','How much time and which practice environments or native-speaker opportunities are available?'],evidence:['study sessions','vocabulary recall','speaking practice','writing samples','tests'],metrics:['active vocabulary','accuracy','comprehension','speaking time'],integrations:[],research_focus:['comprehensible input','retrieval','speaking practice','useful grammar','CEFR progression'],progression:'Prioritise usable communication, then expand accuracy and complexity from observed gaps.'}),
  flow({id:'finance',category:'Personal Finance',goal_types:['Money Management'],keywords:['save','savings','budget','money','finance','financial','investing','investment','spending','debt'],discovery_questions:['What financial outcome are you pursuing and by what date?','What baseline is relevant: available income, commitments, savings or spending pattern?','What constraints, priorities and risk limits should the plan respect?'],evidence:['budgets','savings contributions','spending categories','goal balance'],metrics:['savings rate','goal balance','budget adherence','cash buffer'],integrations:[],research_focus:['budgeting','goal tracking','cash flow planning','financial literacy'],progression:'Establish visibility and a realistic baseline, then build behaviours around the stated goal.'}),
  flow({id:'communication',category:'Communication',goal_types:['Speaking & Presentation'],keywords:['speak','speaking','presentation','present','public speaking','speech','debate','communication'],discovery_questions:['What speaking situation or audience are you preparing for?','What can you currently do confidently and where do you struggle?','What practice opportunities, recording tools, feedback and time constraints do you have?'],evidence:['recordings','practice runs','feedback','timings','speech outlines'],metrics:['timing','clarity','structure','filler-word frequency','feedback'],integrations:[],research_focus:['speech structure','delivery','audience adaptation','rehearsal','feedback'],progression:'Move from controlled rehearsal to realistic delivery with targeted feedback.'}),
  flow({id:'travel',category:'Travel',goal_types:['Trip Planning'],keywords:['travel','trip','holiday','vacation','tour','backpacking','visit','itinerary'],discovery_questions:['What is the destination, purpose and date range?','What pace and experiences matter most to you?','What budget, transport, accommodation, group and practical constraints apply?'],evidence:['bookings','itinerary completeness','budget tracking','readiness checklist'],metrics:['budget variance','readiness','travel time','priority experiences'],integrations:['Google Calendar'],research_focus:['current destination information','transport','local logistics','budgeting','official guidance'],progression:'Resolve hard constraints first, then optimise the itinerary around actual priorities.'}),
];

export const UNKNOWN_DOMAIN_FLOW: DomainFlow = flow({id:'domain-discovery',category:'Domain Discovery',goal_types:['Unmapped Goal'],keywords:[],discovery_questions:['What exact result are you trying to create or become able to do?','What does success look like in observable terms, and what is your current starting point?','What specialist tools, methods, constraints or context are specific to this goal?'],evidence:['user-provided evidence','goal-specific milestones','observable outputs'],metrics:['goal-specific success metric'],integrations:[],research_focus:['identify the domain','find authoritative methodology','identify relevant metrics and constraints'],progression:'Do not generate a generic plan; first identify enough domain-specific context to construct the appropriate flow.'});

export function detectDomainFlow(input:{title?:string|null;outcome?:string|null;why_it_matters?:string|null}) {
  const text=[input.title,input.outcome,input.why_it_matters].filter(Boolean).join(' ').toLowerCase();
  let best:{flow:DomainFlow;score:number}|null=null;
  for(const candidate of DOMAIN_FLOWS){const score=candidate.keywords.reduce((sum,keyword)=>sum+(text.includes(keyword.toLowerCase())?1:0),0);if(score>(best?.score||0))best={flow:candidate,score};}
  if(!best)return {flow:UNKNOWN_DOMAIN_FLOW,confidence:0.3};
  return {flow:best.flow,confidence:Math.min(0.98,0.65+best.score*0.06)};
}

export function getDomainFlow(id:string|null|undefined){return DOMAIN_FLOWS.find((item)=>item.id===id)||UNKNOWN_DOMAIN_FLOW;}
