export type RequiredInput={key:string;question:string;why:string};
export type SpecialistFlow={id:string;domain:string;goal_types:string[];keywords:string[];required_inputs:RequiredInput[];questions:string[];evidence:string[];completion:string;planning_lens:string};

// VOW's domain registry is intentionally broad. A goal should enter the most
// specific specialist flow available instead of being flattened into a generic planner.
const flow=(id:string,domain:string,goal_types:string[],keywords:string[],required_inputs:RequiredInput[],questions:string[],evidence:string[],completion:string,planning_lens:string):SpecialistFlow=>({id,domain,goal_types,keywords,required_inputs,questions,evidence,completion,planning_lens});
const noRequired:RequiredInput[]=[];
const req=(key:string,question:string,why:string):RequiredInput=>({key,question,why});

export const SPECIALIST_FLOWS:SpecialistFlow[]=[
// Sports & movement
flow('running','Sports',['Running'],['run','running','5k','5 km','10k','10 km','half marathon','marathon','jog'],[req('target_distance','What distance or running event are you targeting?','Distance determines the training structure, progression and workload.'),req('current_baseline','What is your current running baseline?','Current performance determines an appropriate starting workload and progression rate.'),req('constraints','What training, recovery, surface or equipment constraints matter?','Constraints materially affect what training can safely and practically be prescribed.')],['What distance, pace or event outcome are you targeting?','What is your most recent running baseline?','What training, recovery, surface or equipment constraints matter?'],['distance','pace','time','effort','completed runs'],'the stated running target or participation outcome is achieved','running-specific progression, pacing, recovery and benchmark testing'),
flow('cycling','Sports',['Cycling'],['cycle','cycling','bike','biking','ride','riding','kilometre','kilometer','cycling tour'],noRequired,['What cycling outcome are you targeting?','What is your current riding baseline?','What terrain, bike setup, recovery or safety constraints matter?'],['distance','duration','speed','elevation','ride completion'],'the stated cycling outcome is achieved','cycling-specific endurance, pacing, terrain and handling progression'),
flow('football','Sports',['Football'],['football','soccer','dribbling','passing','shooting','defending','goalkeeper','fullback','midfielder'],noRequired,['What position, skill or match outcome are you targeting?','What can you reliably do now?','Where and with whom can you practise, and what equipment is available?'],['drills','technical accuracy','match observations','training sessions'],'the target football capability or match outcome is demonstrated','position-specific technical practice, decision making and match transfer'),
flow('basketball','Sports',['Basketball'],['basketball','layup','free throw','three point','dribble'],noRequired,['Which basketball skill or performance result matters most?','What is your current measurable baseline?','What court, hoop and practice access do you have?'],['made shots','repetitions','practice sessions','game outcomes'],'the target basketball capability is demonstrated','basketball skill isolation, repetition quality and game-speed transfer'),
flow('tennis','Sports',['Tennis'],['tennis','serve','forehand','backhand','racket','racquet'],noRequired,['Which stroke, tactical skill or match outcome are you targeting?','What is your current level and typical error pattern?','What court, partner or coach access do you have?'],['serve/rally outcomes','drill completion','match notes','feedback'],'the target tennis capability is demonstrated under realistic play','stroke mechanics, movement, point construction and feedback loops'),
flow('swimming','Sports',['Swimming'],['swim','swimming','pool','freestyle','backstroke','breaststroke','butterfly','laps'],noRequired,['What distance, stroke or time outcome are you targeting?','What is your current swim baseline?','What pool access, technique constraints or safety considerations matter?'],['distance','time','stroke efficiency','completed sets'],'the target swim capability or distance outcome is demonstrated','technique, repeatable sets, pacing and water-specific conditioning'),
flow('golf','Sports',['Golf'],['golf','putting','driving range','golf swing'],noRequired,['What golf outcome are you targeting: technique, scoring or course performance?','What is your current handicap or scoring baseline?','What clubs, practice area and playing access do you have?'],['practice sessions','shots','round scores','miss patterns'],'the target golf capability or score outcome is demonstrated','fundamentals, limiting-factor practice, course transfer and scoring review'),
flow('martial-arts','Sports',['Martial Arts'],['martial arts','karate','judo','taekwondo','jiu jitsu','jiujitsu','boxing','kickboxing','muay thai'],noRequired,['What discipline and capability are you working towards?','What can you currently perform under instructor supervision?','What class, coach and equipment access do you have?'],['classes','technique drills','coach feedback','assessed skills'],'the target skill or progression standard is demonstrated safely in training','coach-led fundamentals, controlled practice, technical progression and recovery'),
flow('dance','Sports',['Dance'],['dance','dancing','hip hop dance','ballet','salsa','contemporary dance','choreography'],noRequired,['What style, routine or performance are you targeting?','What can you currently perform confidently?','What studio, space, music and feedback access do you have?'],['practice sessions','routine sections','timing','recorded rehearsals'],'the target routine or dance capability is performed to the required standard','movement foundations, combinations, musicality, choreography and performance practice'),
flow('hiking','Outdoors',['Hiking'],['hike','hiking','trek','trekking','trail','summit'],noRequired,['What route, distance or outdoor outcome are you targeting?','What is your current hiking baseline?','What terrain, weather, navigation, gear and group constraints matter?'],['route completion','distance','elevation','navigation checks','pack readiness'],'the intended hike is completed with the required preparation','route planning, conditioning, gear readiness, navigation and contingencies'),

// Food, home & practical skills
flow('cooking','Practical Skills',['Cooking'],['cook','cooking','culinary','recipe','pasta','ravioli','dough','filling','sauce','meal'],noRequired,['What exact dish, cuisine or cooking capability are you trying to achieve?','What is your experience with this type of cooking?','What ingredients, tools, equipment, dietary constraints or serving quantity matter?'],['ingredient preparation','technique execution','dish completion','taste/texture checks'],'the exact culinary outcome is prepared to the stated standard','dish-specific mise en place, technique order, equipment adaptation and quality checks'),
flow('baking','Practical Skills',['Baking'],['bake','baking','cake','bread','cookies','pastry','sourdough'],noRequired,['What exact baked result are you aiming for?','What baking experience and baseline technique do you have?','What oven, tin, ingredients, recipe and timing constraints matter?'],['mise en place','proofing/fermentation','bake results','texture checks'],'the baked item meets the intended recipe and quality standard','formula accuracy, temperature control, timing, process checks and iteration'),
flow('gardening','Practical Skills',['Gardening'],['garden','gardening','plant','plants','vegetable garden','herb garden','grow tomatoes','grow herbs'],noRequired,['What are you trying to grow or establish?','What is your current growing setup and experience?','What space, light, soil, water and climate constraints matter?'],['planting tasks','growth observations','watering/feed schedule','harvests'],'the intended plants are established or the growing outcome is achieved','site assessment, planting sequence, care schedule and observation-based adjustment'),
flow('woodworking','Practical Skills',['Woodworking'],['woodworking','woodwork','carpentry','furniture','saw','joinery'],noRequired,['What are you making and what standard must it meet?','What tools and previous woodworking experience do you have?','What material, workspace and measurement constraints matter?'],['measurements','cuts','joints','assembly','finished object'],'the intended build is complete and meets its acceptance criteria','measurement, tool safety, joining sequence and staged verification'),
flow('sewing','Practical Skills',['Sewing'],['sew','sewing','seam','sewing machine','dressmaking','tailoring','embroidery'],noRequired,['What garment, repair or sewing capability are you targeting?','What techniques can you already perform?','What machine, needles, fabric, pattern and workspace constraints matter?'],['pattern work','seams','fittings','repairs','finished item'],'the intended garment, repair or textile outcome is complete','measurement, pattern interpretation, seam control, fitting and finishing'),
flow('crafts','Practical Skills',['Crafts'],['craft','crafting','diy','diy project','handmade','paper craft','origami','model making'],noRequired,['What are you trying to make?','What techniques and tools can you already use?','What materials, dimensions, finish and workspace constraints matter?'],['prototype','technique practice','assembly','finished item'],'the intended craft outcome is complete to its stated standard','materials planning, technique sequence, prototyping and finishing'),
flow('home-organisation','Life Admin',['Home Organisation'],['organise my room','organize my room','declutter','decluttering','tidy','organise','organize','clean my room','home organisation','home organization'],noRequired,['What space or household problem are you trying to solve?','What does a successful end state look like?','What time, storage, household and disposal constraints matter?'],['areas completed','items sorted','storage setup','before/after checklist'],'the defined space or household system reaches the intended state','scope control, sorting sequence, storage decisions and maintenance routine'),
flow('personal-admin','Life Admin',['Personal Administration'],['documents','paperwork','admin','administration','appointments','forms','application form','renew documents'],noRequired,['What exact administrative outcome needs to be completed?','What documents, information or approvals do you already have?','What deadline, office, dependency or submission constraint matters?'],['documents gathered','forms completed','submissions','confirmations'],'the administrative task is fully submitted or completed','dependency tracking, document checklist, deadline management and confirmation checks'),

// Education & learning
flow('academic-study','Education',['Academic Study'],['study','studying','revision','revise','exam','homework','physics','chemistry','biology','maths','mathematics','history','geography','economics','computer science','schoolwork'],noRequired,['What exact syllabus, topic or assessment are you preparing for?','What do you already know and where are the gaps?','What exam date, mark target or resource constraints matter?'],['diagnostic questions','practice accuracy','retrieval results','completed papers'],'the required academic standard is demonstrated','diagnosis, retrieval, worked practice, error correction and assessment simulation'),
flow('research','Education',['Research'],['research','research paper','investigate a topic','literature review','dissertation','thesis','academic research'],noRequired,['What exact question are you trying to answer?','What evidence or sources have you already collected?','What citation, scope, method and deadline constraints apply?'],['research question','source set','notes','analysis','draft sections'],'the research question is answered to the stated evidence and scope standard','question refinement, source quality, evidence synthesis, analysis and writing'),
flow('university-prep','Education',['University Preparation'],['university application','college application','ucas','personal statement','university prep','campus prep','foundation application'],noRequired,['What institution, course or application outcome are you targeting?','Which requirements have you already completed?','What deadlines, documents, tests or references are still outstanding?'],['requirements checklist','documents','applications','deadlines','confirmed submissions'],'the application or preparation checklist is fully completed','requirements mapping, dependency order, drafting and verification'),
flow('language','Languages',['Language Learning'],['french','spanish','german','italian','portuguese','arabic','swahili','japanese','korean','mandarin','chinese','language','fluent','vocabulary','pronunciation'],[req('current_level','What is your current level in the language?','Starting level determines vocabulary, grammar, input difficulty and progression.'),req('target_use','What do you want to be able to use the language for?','Conversation, travel, school, work and fluency require different practice priorities.'),req('priority_skills','Which language skills matter most to you?','Speaking, listening, reading and writing require different training and practice.')],['What can you currently understand and say in the language?','What real-world use case do you want to reach?','Which skills matter most: speaking, listening, reading, writing or a balance?'],['comprehension','speaking samples','writing samples','vocabulary recall','real conversations'],'the stated communication capability is demonstrated in a realistic context','input-output balance, retrieval, communicative practice and increasing complexity'),
flow('reading','Reading',['Reading'],['read','reading','book','books','novel','pages','chapter','non-fiction','fiction'],noRequired,['Why are you reading this material?','What material and difficulty are you choosing?','Do you care most about speed, comprehension, retention or finishing?'],['pages','chapters','reading sessions','notes','comprehension checks'],'the defined reading outcome is completed with the intended understanding','reading purpose, sustainable pace and comprehension feedback'),
flow('skill-learning','Learning',['Skill Acquisition'],['learn','learning','master','mastery','get good at','become good at','practise','practice','improve my skills','develop a skill','learn how to'],noRequired,['What exact skill or capability are you trying to build?','What can you already do independently?','What tools, teacher/resources and real-world application opportunities do you have?'],['practice sessions','demonstrated techniques','projects','performance checks','real-world applications'],'the stated capability is demonstrated independently','baseline diagnosis, deliberate practice, feedback and progressively harder application'),

// Technology, design & engineering
flow('programming','Technology',['Programming'],['code','coding','programming','python','javascript','typescript','java','c++','rust','go ','html','css','software','app','website','web development','api'],[req('software_outcome','What exact software outcome are you trying to achieve?','The intended outcome determines implementation scope and acceptance criteria.'),req('current_state','What is already working and what is not?','The current state determines whether the work is building, debugging, refactoring or extending.'),req('stack_environment','What stack and development environment are you using?','Frameworks, runtimes, dependencies and tooling materially constrain implementation choices.')],['What exact software outcome or capability are you targeting?','What is already working and what is not?','What stack, environment, dependencies and acceptance criteria constrain the work?'],['working features','tests','commits','bugs resolved','deployments'],'the software outcome passes its defined acceptance criteria','acceptance criteria, dependency order, small working increments, tests and shipping'),
flow('cybersecurity','Technology',['Cybersecurity Learning'],['cybersecurity','cyber security','network security','ethical hacking','penetration testing','ctf','security lab'],noRequired,['What exact cybersecurity skill or lab outcome are you targeting?','What concepts and tools do you already understand?','What legal lab, course environment and assessment constraints apply?'],['lab exercises','completed challenges','write-ups','defensive checks','course assessments'],'the target cybersecurity capability is demonstrated in an authorised learning environment','foundations, isolated labs, defensive reasoning, challenge practice and evidence'),
flow('data','Technology',['Data Analysis'],['data analysis','data science','pandas','sql','statistics','machine learning','ml','analytics','dashboard','visualisation','visualization'],noRequired,['What question or analytical outcome are you trying to produce?','What data and current analytical skills do you have?','What tools, quality issues and output requirements constrain the work?'],['cleaned data','queries','analysis','models','charts','findings'],'the analytical question is answered with a validated output','data quality, exploratory analysis, appropriate methods, validation and communication'),
flow('engineering','Engineering',['Engineering'],['engineering','mechatronics','robotics','arduino','cad','prototype','electronics','mechanical','3d print','microcontroller'],noRequired,['What physical or technical outcome are you building?','What components, measurements and current prototype state exist?','What tools, tolerances, budget or safety constraints matter?'],['prototype iterations','test measurements','schematics','working subsystems'],'the engineering outcome passes its required functional tests','requirements, subsystem dependencies, prototyping, testing and iteration'),
flow('design','Creative Technology',['Digital Design'],['graphic design','ui design','ux design','user interface','user experience','figma','branding','logo','design system','visual design'],noRequired,['What exact design outcome are you creating and for whom?','What existing brief, reference or baseline do you have?','What platform, dimensions, brand constraints and feedback source matter?'],['wireframes','components','iterations','prototype','feedback'],'the defined design deliverable meets its brief and quality criteria','brief definition, hierarchy, system consistency, prototyping and critique'),
flow('3d','Creative Technology',['3D Modelling'],['3d modelling','3d model','blender','fusion 360','solidworks','modelling','modeling','render'],noRequired,['What exact object or 3D outcome are you creating?','What modelling skills and software knowledge do you already have?','What dimensions, geometry, export format and use case matter?'],['model iterations','dimensions','renders','exports','fit checks'],'the 3D asset meets its defined geometry and output requirements','reference analysis, modelling sequence, constraint checks, refinement and export'),
flow('video','Creative Skills',['Video Production'],['video editing','video','filmmaking','film','premiere pro','davinci resolve','capcut','after effects','editing'],noRequired,['What video are you trying to produce and what should viewers experience?','What footage, editing skill and software do you already have?','What duration, aspect ratio, audio, deadline and delivery constraints matter?'],['rough cut','edited sequences','audio checks','final export','feedback'],'the finished video meets its creative and technical brief','story structure, edit passes, audio, pacing, colour and final delivery'),
flow('photography','Creative Skills',['Photography'],['photography','photograph','camera','portrait','street photography','landscape photography'],noRequired,['What kind of photographs are you trying to create?','What camera or phone and current skill level do you have?','What lighting, location and editing constraints matter?'],['shoots','selected images','technical checks','feedback'],'the target photographic result or capability is demonstrated','exposure/focus, composition, controlled shoots, selection and editing'),
flow('writing','Creative Skills',['Writing'],['write','writing','story','short story','novel','poetry','poem','screenplay','essay','blog','article'],noRequired,['What exact piece are you trying to finish?','What genre, audience, tone or reference style matters?','What stage are you at: idea, outline, draft, revision or final?'],['outline','drafts','revisions','feedback','finished piece'],'the defined written piece is finished to its stated standard','ideation, structure, drafting, revision and feedback'),
flow('drawing','Creative Skills',['Drawing'],['draw','drawing','sketch','sketching','illustration'],noRequired,['What are you trying to draw or become able to draw?','What is your current skill level?','Which medium, reference style and tools will you use?'],['studies','drawings','proportion checks','finished pieces'],'the target drawing outcome or capability is demonstrated','observation, proportion, construction, value, perspective and composition'),
flow('painting','Creative Skills',['Painting'],['paint','painting','watercolour','watercolor','acrylic','oil painting','canvas'],noRequired,['What are you trying to paint?','What medium and current experience do you have?','What style, palette, surface and workspace constraints matter?'],['studies','colour mixes','paintings','critiques'],'the target painting is completed to the stated standard','medium-specific technique, colour/value studies, composition and finished work'),
flow('music','Creative Skills',['Music'],['music','piano','guitar','keyboard','drums','violin','ukulele','singing','vocals','instrument'],noRequired,['What instrument or musical capability are you targeting?','What can you play or perform now?','What instrument access, genre and practice environment do you have?'],['practice sessions','technique exercises','pieces performed','recordings'],'the target musical capability or performance is demonstrated','technique, repertoire, deliberate practice and performance evidence'),
flow('crochet','Creative Skills',['Crochet'],['crochet','crocheting','amigurumi','crochet hook'],noRequired,['What are you trying to make or learn?','What stitches and techniques can you already do?','What yarn, hook and pattern constraints matter?'],['stitches','swatches','finished projects'],'the stated crochet outcome is completed','stitch foundations, tension, construction and project transfer'),
flow('knitting','Creative Skills',['Knitting'],['knit','knitting','purl','cast on','knitting needles'],noRequired,['What are you trying to knit?','Which techniques can you already perform?','What yarn, needle and pattern constraints matter?'],['swatches','stitch control','shaping','finished projects'],'the stated knitting outcome is completed','stitch control, tension, shaping and project transfer'),

// Career, money & entrepreneurship
flow('career','Career',['Career Development'],['career','cv','resume','job','application','internship','interview','portfolio','cover letter','linkedin'],noRequired,['What exact opportunity or career outcome are you targeting?','What evidence, experience or requirements do you currently have?','What deadlines, contacts and constraints matter?'],['applications','interviews','portfolio deliverables','milestones','feedback'],'the stated career outcome or acceptance criteria are met','requirements mapping, evidence-producing actions, dependencies and review'),
flow('entrepreneurship','Business',['Entrepreneurship'],['business','startup','entrepreneur','entrepreneurship','side business','company','founder','product launch'],noRequired,['What customer problem and business outcome are you targeting?','What have you validated or built so far?','What resources, budget, audience and deadline constraints matter?'],['customer interviews','prototype','validation','offers','sales or usage evidence'],'the defined business validation or launch milestone is achieved','problem definition, validation, offer design, execution and evidence-based iteration'),
flow('personal-finance','Finance',['Personal Finance'],['money','budget','budgeting','financial','finance','savings','saving','expense','expenses','allowance','spending'],noRequired,['What exact financial outcome or behaviour are you trying to change?','What is your current baseline and realistic contribution?','What deadlines, fixed expenses and non-negotiables constrain the plan?'],['budget reviews','savings milestones','expense tracking','completed money tasks'],'the stated financial target or behaviour is reached','baseline, controllable actions, milestone tracking and review-based adjustment'),
flow('communication','Communication',['Public Speaking'],['public speaking','presentation','speech','presenting','debate','toastmaster'],noRequired,['What real speaking situation are you preparing for?','What currently feels weakest in your delivery?','What audience, length and feedback source will you have?'],['rehearsals','recordings','timing','feedback'],'the target speaking performance is delivered to the required standard','message structure, delivery, rehearsal and audience simulation'),
flow('social','Relationships',['Social Connection'],['friendship','friends','make friends','social','community','meet people','networking'],noRequired,['What social outcome are you trying to create?','What interactions or situations are currently easiest or hardest for you?','What communities, activities and boundaries are available to you?'],['conversations','attended activities','follow-ups','reflections'],'the intended social outcome is reached through healthy, voluntary interactions','environment selection, small actions, repetition, reflection and adjustment'),
flow('volunteering','Community',['Volunteering'],['volunteer','volunteering','community service','serve my community','charity work'],noRequired,['What cause or community outcome matters to you?','What skills, time and organisation access do you have?','What role, location and safeguarding requirements apply?'],['volunteer shifts','tasks completed','hours','project outputs'],'the defined volunteering commitment or community outcome is completed','cause-role fit, scheduling, preparation, contribution and reflection'),

// Travel, events & logistics
flow('travel','Travel',['Travel Planning'],['travel','trip','itinerary','destination','holiday','vacation','flight','abroad','backpacking','city break'],[req('destination','Where are you travelling to?','Destination materially changes transport, accommodation, activities, costs, timing and logistics.'),req('travel_style','What kind of trip are you looking for?','Budget, adventure, relaxation, culture and other travel styles produce substantially different plans.'),req('budget','What budget are you working with?','Budget determines feasible transport, accommodation, activities and spending priorities.')],['Where are you going and what is the purpose of the trip?','What dates, budget and must-haves are fixed?','What documents, bookings, transport, accommodation or contingency constraints matter?'],['confirmed bookings','completed checklist','itinerary completeness','document readiness'],'the trip is prepared to the stated standard','hard constraints, dependency order, bookings, packing and final readiness'),
flow('moving','Life Admin',['Moving / Relocation'],['move house','moving house','relocate','relocation','move abroad','moving abroad','new apartment','new home'],noRequired,['Where are you moving and what needs to be ready by move day?','What has already been arranged?','What documents, transport, packing, accommodation and budget constraints matter?'],['housing confirmation','documents','packed areas','transport','arrival checklist'],'the relocation is ready and the move is completed to the defined standard','dependency mapping, packing sequence, logistics and arrival readiness'),
flow('event','Events',['Event Planning'],['event','party','birthday','graduation','conference','workshop','dinner','celebration','ceremony'],noRequired,['What exact event are you organising and what should guests experience?','What venue, date, guests and commitments are already fixed?','What suppliers, budget, programme and contingency constraints matter?'],['venue','guest list','bookings','run sheet','final checks'],'the event is fully prepared and ready to run','backward planning, dependency order, supplier coordination and contingency checks'),
flow('packing','Travel',['Packing / Travel Readiness'],['pack','packing','suitcase','luggage','carry on','carry-on','travel checklist'],noRequired,['What trip or move is this packing for?','What is already available and what must be obtained or washed?','What baggage limits, weather, activities or document constraints matter?'],['packing checklist','weight/size checks','documents','essentials'],'everything required is packed and travel-ready','trip-specific inventory, priority ordering, baggage constraints and final verification'),

// Wellbeing, routines & personal development
flow('sleep','Wellbeing',['Sleep Routine'],['sleep','sleeping','bedtime','wake up','sleep schedule'],noRequired,['What sleep routine change are you trying to make?','What does your current pattern look like?','What school/work timing, environment or evening constraints matter?'],['bed/wake consistency','routine adherence','morning readiness','self-observation'],'a sustainable sleep routine is established','schedule consistency, environment, wind-down cues and gradual adjustment'),
flow('mindfulness','Wellbeing',['Mindfulness'],['mindfulness','meditation','meditate','breathing','reflection'],noRequired,['What change are you hoping mindfulness will support?','What is your current practice, if any?','What session length and environment are realistically available?'],['sessions','duration','self-reflection','consistency'],'the intended practice is established and evidenced','short repeatable sessions, gradual consistency and reflection'),
flow('productivity','Personal Development',['Productivity System'],['productivity','productive','focus','time management','time management','organise my tasks','organize my tasks','get organised','get organized'],noRequired,['What recurring workload or bottleneck are you trying to solve?','How do you currently capture and execute your tasks?','What schedule, tools and fixed commitments constrain the system?'],['completed priorities','missed-task patterns','review notes','system adherence'],'the defined workflow improves execution of the stated responsibilities','workflow diagnosis, prioritisation, friction reduction and review loops'),
flow('habit','Personal Development',['Habit Building'],['habit','routine','daily habit','weekly habit','consistency','streak'],noRequired,['What exact behaviour are you trying to establish?','When and where does it currently happen, if at all?','What cues, blockers and realistic frequency constraints matter?'],['completed instances','adherence','barriers','review outcomes'],'the behaviour is performed at the intended frequency with evidence of sustainability','cue design, low-friction execution, adherence tracking and adaptation'),
flow('goals','Personal Development',['Personal Goal Development'],['personal growth','self improvement','self-improvement','discipline','confidence','personal development'],noRequired,['What concrete change would show that this goal is working?','What is already true today and what is missing?','What situations, routines and resources can you realistically use?'],['behaviour evidence','milestones','reflections','completed actions'],'the defined personal-development outcome is demonstrated','baseline, concrete behaviour, repeated practice and reflection'),

// Faith & reflection
flow('faith','Faith',['Faith Practice'],['faith','prayer','pray','bible','scripture','church','christian','christianity','devotional','devotion','quran','islam','religious study'],noRequired,['What faith practice or learning outcome are you pursuing?','What is your current practice or understanding?','What tradition, text, community or schedule should shape the plan?'],['reading','study notes','prayer/reflection sessions','community participation'],'the stated faith practice or learning outcome is completed with the intended consistency or understanding','tradition-aware study, practice, reflection and community support'),

// Hobbies and collections
flow('gaming','Hobbies',['Gaming Goal'],['gaming','game','minecraft','fortnite','rocket league','efootball','video game'],noRequired,['What exact gaming outcome are you targeting: skill, completion, rank or a project?','What is your current baseline?','What game mode, platform, time and equipment constraints matter?'],['matches','rank/score','completed objectives','practice metrics'],'the target gaming outcome is achieved','goal-specific practice, deliberate repetition, feedback and measured progression'),
flow('collecting','Hobbies',['Collecting'],['collect','collecting','collection','stamps','coins','cards','memorabilia','figures'],noRequired,['What collection are you building and what does completion mean?','What do you already have?','What authenticity, budget, storage and sourcing constraints matter?'],['catalogue entries','verified items','collection milestones','storage organisation'],'the collection reaches its defined scope or milestone','scope definition, cataloguing, verification, sourcing and storage'),
flow('pet-care','Home & Life',['Pet Care'],['pet','dog','cat','puppy','kitten','fish tank','aquarium'],noRequired,['What pet-care outcome are you trying to establish?','What is the current routine and what does the animal already require?','What schedule, supplies, household and professional-care constraints matter?'],['care tasks','routine adherence','supplies','appointments'],'the required routine or preparation is consistently in place','routine design, preparation, environment and escalation to appropriate care'),
];

export function specialistFor(input:{title?:string|null;category?:string|null;goal_type?:string|null}):SpecialistFlow|null{
 const text=[input.title,input.category,input.goal_type].filter(Boolean).join(' ').toLowerCase();
 return SPECIALIST_FLOWS.find(flow=>flow.keywords.some(k=>text.includes(k)))
   ||SPECIALIST_FLOWS.find(flow=>flow.goal_types.some(k=>k.toLowerCase()===(input.goal_type||'').toLowerCase()))
   ||null;
}
