import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json"};
const MODES=["one_time","project","recurring","mastery","performance","event","adaptive"] as const;
type Mode=typeof MODES[number];
type RequiredInput={key:string;question:string;why?:string};

const json=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:CORS});
const text=(x:unknown,n=900)=>typeof x==='string'?x.trim().slice(0,n):'';

function modeFor(g:any):Mode{const t=[g?.title,g?.outcome,g?.why_it_matters,g?.target,g?.time_target].filter(Boolean).join(' ');if(/\b(?:by|before|deadline|for)\s+(?:the\s+)?(?:event|exam|race|match|trip|flight|deadline)\b/i.test(t))return'event';if(/\b(?:daily|every day|weekly|every week|monthly|every month|habit|routine|regularly)\b/i.test(t))return'recurring';if(/\b(?:under|sub)\s+\d+|\b(?:PB|PR|personal best|faster|higher|lower|stronger|score|pace)\b/i.test(t))return'performance';if(/\b(?:project|prototype|portfolio|website|app|launch|deliverable|MVP)\b/i.test(t))return'project';if(/\b(?:learn|master|improve|develop|skill|fluent|competent|understand)\b/i.test(t))return'mastery';if(/\b(?:once|one[- ]time|just once|single time|make|cook|build|create|write|fix|prepare|set up|do)\b/i.test(t))return'one_time';return'adaptive'}
function workflow(mode:Mode){return({one_time:{name:'One-time',output:'ordered_steps',rules:['No artificial weekly programme','Optimise prerequisites and order','Schedule only when useful']},project:{name:'Project',output:'milestones_and_tasks',rules:['Sequence dependencies','Use deliverable milestones','Re-plan when scope changes']},recurring:{name:'Recurring',output:'cadence_and_adaptation',rules:['Cadence is part of the goal','Optimise sustainability','Adapt from adherence']},mastery:{name:'Mastery',output:'skill_levels_and_practice',rules:['Start from baseline','Advance from demonstrated competence','Test transfer']},performance:{name:'Performance',output:'training_blocks_and_benchmarks',rules:['Use verified baseline','Train limiting factors','Benchmark and adapt']},event:{name:'Event',output:'countdown_plan',rules:['Work backwards from fixed requirements','Resolve dependencies early','Protect readiness']},adaptive:{name:'Adaptive',output:'rolling_next_best_action',rules:['New evidence can change the route','Every execution creates learning','Preserve the goal while changing the next action']}} as any)[mode]}
async function ai(messages:any[],plan:boolean){const key=Deno.env.get('GROQ_API_KEY');if(!key)throw new Error('AI_UNAVAILABLE');const r=await fetch('https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${key}`},body:JSON.stringify({model:'openai/gpt-oss-120b',messages,temperature:.15,reasoning_effort:plan?'low':'medium',max_completion_tokens:plan?9000:2200,response_format:{type:'json_object'}})});const raw=await r.text();if(!r.ok)throw new Error(`AI_${r.status}`);const out=JSON.parse(raw)?.choices?.[0]?.message?.content;if(typeof out!=='string'||!out.trim())throw new Error('AI_EMPTY');return JSON.parse(out)}
async function knowledge(q:string,domain?:string|null){try{const c=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_ANON_KEY')||'',{global:{headers:{Authorization:Deno.env.get('SUPABASE_ANON_KEY')||''}}});const {data}=await c.rpc('match_vow_knowledge_keyword',{query_text:q.slice(0,900),domain_filter:domain||null,match_count:8});return(data||[]).slice(0,8).map((x:any)=>({domain:text(x.domain,80),topic:text(x.topic,120),title:text(x.title,160),content:text(x.content,650),principles:Array.isArray(x.principles)?x.principles.slice(0,5):[],recommended_actions:Array.isArray(x.recommended_actions)?x.recommended_actions.slice(0,5):[],metrics:Array.isArray(x.metrics)?x.metrics.slice(0,5):[],cautions:Array.isArray(x.cautions)?x.cautions.slice(0,5):[]}))}catch{return[]}}
function normaliseRequiredInputs(value:unknown):RequiredInput[]{return Array.isArray(value)?value.slice(0,20).map((x:any)=>({key:text(x?.key,80),question:text(x?.question,500),why:text(x?.why,500)})).filter((x:RequiredInput)=>x.key&&x.question):[]}
function missingRequiredInputKeys(requiredInputs:RequiredInput[],rows:Array<{key?:unknown;answer?:unknown}>){const answered=new Set(rows.map(x=>({key:text(x?.key,80),answer:text(x?.answer,1000)})).filter(x=>x.key&&x.answer).map(x=>x.key));return requiredInputs.map(x=>x.key).filter(key=>!answered.has(key));}

Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:CORS});if(req.method!=='POST')return json({error:'Method not allowed.'},405);try{
 const auth=req.headers.get('Authorization')||'';if(!auth.startsWith('Bearer '))return json({error:'Authentication required.'},401);
 const c=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_ANON_KEY')||'',{global:{headers:{Authorization:auth}}});
 const {data:u}=await c.auth.getUser();if(!u.user)return json({error:'Authentication required.'},401);
 const b=await req.json();const g=b?.goal||{};const a=b?.armadillo||{};const requested=b?.hamster_context?.mode;const mode:Mode=MODES.includes(requested)?requested:modeFor({...g,...a});const flow=workflow(mode);
 const answers=Array.isArray(b?.answers)?b.answers.slice(0,20):[];const clientRequiredInputs=normaliseRequiredInputs(b?.required_inputs);const domain=text(a?.domain||b?.hamster_context?.domain?.domain,100)||null;
 const k=await knowledge([text(g.title,300),text(g.outcome,400),domain||text(a.category,100),text(a.goal_type,120),...answers.map((x:any)=>text(x?.answer,300))].filter(Boolean).join(' '),domain);

 if(b?.action!=='plan'){
   const supplied=clientRequiredInputs;
   const r=await ai([{role:'system',content:`You are VOW's universal goal-understanding engine. There are NO specialist categories, no privileged domains, and no second-class goals. Every goal is equally important and deserves the same depth of reasoning. Determine the minimum information genuinely required to build a strong plan for this exact goal, regardless of whether it is running, travel, cooking, knitting, surfing, programming, study, business, art, or anything else. Do not use a fixed category list. Return canonical required inputs as stable machine-readable keys. Every required input must be covered by a compulsory question. If the user already supplied enough information for an input, do not ask for it again. You may add at most one additional intelligent follow-up if it materially improves execution. Return JSON only: {required_inputs:[{key:string,question:string,why:string}],questions:[{key:string,question:string}],rationale:string}. If supplied required_inputs are present, treat them as existing requirements and preserve every key; only improve wording if needed. Never omit a supplied requirement.`},{role:'user',content:JSON.stringify({goal:g,armadillo:a,mode,flow,required_inputs:supplied,answers,knowledge:k})}],false);
   const generated=normaliseRequiredInputs(r.required_inputs);const requiredInputs=supplied.length?supplied:generated;
   if(!requiredInputs.length)return json({error:'HAMSTER_DISCOVERY_FAILED'},422);
   const suppliedAnswers=new Set(answers.map((x:any)=>({key:text(x?.key,80),answer:text(x?.answer,1000)})).filter((x:any)=>x.key&&x.answer).map((x:any)=>x.key));
   const qs=requiredInputs.filter(x=>!suppliedAnswers.has(x.key)).map(x=>({key:x.key,question:x.question}));
   const extra=Array.isArray(r.questions)?r.questions.map((x:any)=>({key:text(x?.key,80),question:text(x?.question,500)})).filter((x:any)=>x.key&&x.question&&!requiredInputs.some(y=>y.key===x.key)).slice(0,1):[];
   const finalQuestions=[...qs,...extra].slice(0,Math.min(20,requiredInputs.length+1));
   const missing=requiredInputs.map(x=>x.key).filter(key=>!new Set(finalQuestions.map(x=>x.key)).has(key)&&!suppliedAnswers.has(key));
   if(missing.length)return json({error:'HAMSTER_DISCOVERY_FAILED',missing_required_inputs:missing},422);
   if(finalQuestions.length<2)return json({error:'HAMSTER_DISCOVERY_FAILED'},422);
   return json({structured:{questions:finalQuestions,rationale:text(r.rationale,800),mode,required_inputs:requiredInputs}});
 }

 const goalId=text(g?.id,100);if(!goalId)return json({error:'VOW requires a persisted goal before building this plan.'},422);
 const {data:storedQuestions,error:questionError}=await c.from('goal_clarification_answers').select('key,question,answer,question_order').eq('goal_id',goalId).eq('user_id',u.user.id).order('question_order',{ascending:true}).limit(20);if(questionError)throw questionError;
 const rows=storedQuestions||[];
 const requiredInputs=clientRequiredInputs;
 if(requiredInputs.length){const missing=missingRequiredInputKeys(requiredInputs,rows);if(missing.length)return json({error:`Missing required clarification input: ${missing.join(', ')}.`,missing_required_inputs:missing},422);}
 if(!rows.length)return json({error:'VOW requires its goal questions before building this plan.'},422);
 const unanswered=rows.filter((x:any)=>!text(x?.answer,1000));if(unanswered.length)return json({error:'Answer every VOW question before building this plan.',missing_required_inputs:unanswered.map((x:any)=>text(x?.key,80)).filter(Boolean)},422);
 const requiredQuestions=rows.map((x:any)=>({key:text(x?.key,80),question:text(x?.question,500),answer:text(x?.answer,1000)})).filter((x:any)=>x.question&&x.answer);
 if(requiredQuestions.length<2)return json({error:'VOW requires its goal questions before building this plan.'},422);
 const r=await ai([{role:'system',content:`You are VOW, the adaptive planning engine. Create a plan for the exact user and exact goal. Every domain receives the same planning effort and quality bar. Planning mode is HARD-CONSTRAINED to ${mode}. Use this workflow: ${JSON.stringify(flow)}. The user has completed every compulsory goal question; use every saved answer materially. Never turn a one-time outcome into a weekly programme. Do not invent a horizon or cadence unless the mode or user requires it. Every step must be actionable and reflect the answers. Adaptive mode must define evidence triggers that change the next action. Return JSON only: {mode,domain,completion_definition,overview,success_metric,horizon,cadence,deadline,steps,milestones,adaptation_rules,next_action}. steps are objects {order,title,purpose,target,evidence,estimated_minutes}. milestones are objects {title,description}.`},{role:'user',content:JSON.stringify({goal:g,armadillo:a,mode,flow,answers:requiredQuestions,required_inputs:requiredInputs,knowledge:k})}],true);
 if(!Array.isArray(r.steps)||!r.steps.length)return json({error:'HAMSTER_EMPTY_PLAN'},422);
 return json({structured:{...r,mode,workflow:flow,steps:r.steps.slice(0,24),knowledge_count:k.length}})
 }catch(e){console.error('vow-hamster',e);return json({error:'VOW could not complete that request right now.'},500)}});