/* eslint-disable no-empty, @typescript-eslint/no-explicit-any */
import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json"};
const MODEL="llama-3.1-8b-instant";
const MAX={plan:900,clarify:500,chat:400};
const COOLDOWN={plan:120000,clarify:30000,chat:10000};
const json=(body:unknown,status=200,extra:Record<string,string>={})=>new Response(JSON.stringify(body),{status,headers:{...CORS,...extra}});
function secretKey(){try{const x=JSON.parse(Deno.env.get("SUPABASE_SECRET_KEYS")||"{}");if(x.default)return x.default;}catch{}return Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";}
function userClient(req:Request){let key=Deno.env.get("SUPABASE_ANON_KEY")||"";if(!key){try{key=JSON.parse(Deno.env.get("SUPABASE_PUBLISHABLE_KEYS")||"{}").default||"";}catch{}}return createClient(Deno.env.get("SUPABASE_URL")!,key,{global:{headers:{Authorization:req.headers.get("Authorization")||""}}});}
const admin=()=>createClient(Deno.env.get("SUPABASE_URL")!,secretKey(),{auth:{persistSession:false,autoRefreshToken:false}});
function str(v:unknown,max=500){return typeof v==="string"?v.trim().slice(0,max):"";}
function arr(v:unknown,n:number,max=400){return Array.isArray(v)?v.slice(0,n).map(x=>str(x,max)).filter(Boolean):[];}
function parse(raw:string){const s=raw.trim().replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/i,"").trim();try{return JSON.parse(s)}catch{const a=s.indexOf("{"),b=s.lastIndexOf("}");if(a>=0&&b>a)return JSON.parse(s.slice(a,b+1));throw new Error("INVALID_AI_JSON");}}
function weeks(goal:any){const n=Number(goal?.duration_weeks??goal?.durationWeeks??goal?.weeks);if(Number.isFinite(n)&&n>=1)return Math.min(52,Math.round(n));if(goal?.start_date&&goal?.deadline){const a=Date.parse(goal.start_date),b=Date.parse(goal.deadline);if(Number.isFinite(a)&&Number.isFinite(b)&&b>a)return Math.min(52,Math.max(1,Math.ceil((b-a)/604800000)));}return 8;}
function selectedDays(input:any,weekly:number){const valid=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"];const requested=Array.isArray(input)?input.map((x:any)=>valid.find(v=>v.toLowerCase()===String(x).toLowerCase())).filter(Boolean) as string[]:[];if(requested.length)return requested.slice(0,7);return ["Monday","Wednesday","Friday","Saturday"].slice(0,Math.max(1,Math.min(4,weekly)));}
function schedule(blue:any,weeksN:number,days:string[],startDate:string){const focuses=Array.isArray(blue?.weekly_focus)&&blue.weekly_focus.length?blue.weekly_focus.slice(0,8).map((x:any)=>str(x,300)):[str(blue?.summary,250)||"Work consistently toward the goal."];const out:any[]=[];const start=new Date(`${startDate}T09:00:00`);const names=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"];for(let w=1;w<=weeksN;w++){const focus=focuses[(w-1)%focuses.length];for(const day of days){const d=new Date(start);const mondayOffset=(d.getDay()+6)%7;d.setDate(d.getDate()-mondayOffset+(w-1)*7+names.indexOf(day));out.push({week:w,day,task:focus,purpose:`Week ${w}: ${focus}`.slice(0,400),target_metric:str(blue?.success_metric,180)||"Complete the planned session",duration_minutes:30,preferred_time:"09:00",scheduled_at:d.toISOString()});}}return out;}
async function cooldown(userId:string,kind:keyof typeof COOLDOWN){const {data,error}=await admin().from("vow_ai_usage").select("created_at").eq("user_id",userId).eq("kind",kind).order("created_at",{ascending:false}).limit(1).maybeSingle();if(error)throw new Error("AI_USAGE_CHECK_FAILED");if(data?.created_at){const left=COOLDOWN[kind]-(Date.now()-Date.parse(data.created_at));if(left>0)return Math.ceil(left/1000);}return 0;}
async function record(userId:string,kind:keyof typeof COOLDOWN){const {error}=await admin().from("vow_ai_usage").insert({user_id:userId,kind});if(error)console.error("usage record",error.message);}
async function groq(messages:any[],kind:keyof typeof MAX){const key=Deno.env.get("GROQ_API_KEY");if(!key)throw new Error("GROQ_API_KEY_MISSING");const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),25000);try{const r=await fetch("https://api.groq.com/openai/v1/chat/completions",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${key}`},signal:controller.signal,body:JSON.stringify({model:MODEL,messages,max_completion_tokens:MAX[kind],temperature:0.2,response_format:{type:"json_object"}})});const raw=await r.text();if(!r.ok){console.error("Groq",r.status,raw.slice(0,1000));if(r.status===429)throw new Error("GROQ_429");throw new Error("GROQ_PROVIDER_ERROR");}const content=JSON.parse(raw)?.choices?.[0]?.message?.content;if(typeof content!=="string"||!content.trim())throw new Error("GROQ_EMPTY_RESPONSE");return parse(content);}finally{clearTimeout(timer);}}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:CORS});if(req.method!=="POST")return json({error:"Method not allowed."},405);try{const auth=req.headers.get("Authorization")||"";if(!auth.startsWith("Bearer "))return json({error:"Authentication required."},401);const {data,error}=await userClient(req).auth.getUser();if(error||!data.user)return json({error:"Authentication required."},401);const userId=data.user.id;const p=await req.json();const mode=p?.mode==="goal-plan"||p?.mode==="goal-clarify"||p?.mode==="chat"?p.mode:"chat";const message=str(p?.message,1600);if(!message)return json({error:"A request is required."},400);const kind=mode==="goal-plan"?"plan":mode==="goal-clarify"?"clarify":"chat";const wait=await cooldown(userId,kind);if(wait>0)return json({error:"VOW AI is on a short cooldown. Please try again shortly.",retry_after_seconds:wait},429,{"Retry-After":String(wait)});const goal=p?.goal||{};const weeksN=weeks(goal);const weekly=Math.min(7,Math.max(1,Math.round(Number(goal?.weekly_commitment_target??goal?.weeklyTarget??3)||3)));const days=selectedDays(p?.available_days,weekly);const answers=Array.isArray(p?.answers)?p.answers.slice(0,8).map((a:any)=>({question:str(a?.question,220),answer:str(a?.answer,350)})):[];const calendar=Array.isArray(p?.calendar)?p.calendar.slice(0,8).map((x:any)=>str(JSON.stringify(x),220)):[];const references=Array.isArray(p?.references)?p.references.slice(0,4).map((x:any)=>str(JSON.stringify(x),300)):[];const compact={title:str(goal?.title||goal?.outcome,300),outcome:str(goal?.outcome,500),why_it_matters:str(goal?.why_it_matters,350),baseline:str(goal?.baseline,300),start_date:str(goal?.start_date,30),deadline:str(goal?.deadline,30),duration_weeks:weeksN,weekly_commitment_target:weekly,available_days:days};
if(mode==="goal-plan"){const blueprint=await groq([{role:"system",content:`You are VOW AI, a practical goal coach. Return ONLY JSON. The user's duration is authoritative: ${weeksN} weeks. Their available days are authoritative: ${days.join(", ")}. Their weekly target is ${weekly}. Create a compact plan blueprint, NOT a daily schedule; the server will create every schedule item. Use exactly: outcome, success_metric, baseline, assumptions, milestones, weekly_focus, progression, checkpoints, risks, fallback_rules, summary. milestones are 2-8 objects with title, description, week. weekly_focus is 1-8 concise actionable strings. Keep every field concise.`},{role:"user",content:JSON.stringify({goal:compact,message,answers,calendar,references})}],"plan");const result={...blueprint,duration_weeks:weeksN,weekly_commitment_target:weekly,available_days:days,schedule:schedule(blueprint,weeksN,days,str(goal?.start_date)||new Date().toISOString().slice(0,10))};if(p?.goal_id){const a=admin();await a.from("goal_plan_items").delete().eq("goal_id",p.goal_id).eq("user_id",userId);const rows=result.schedule.map((s:any)=>({goal_id:p.goal_id,user_id:userId,plan_version:1,week_number:s.week,day_of_week:s.day,scheduled_at:s.scheduled_at,task:s.task,purpose:s.purpose,target_metric:s.target_metric,duration_minutes:s.duration_minutes,status:"scheduled"}));for(let i=0;i<rows.length;i+=100){const {error:e}=await a.from("goal_plan_items").insert(rows.slice(i,i+100));if(e)throw new Error("PLAN_SAVE_FAILED");}}await record(userId,"plan");return json({structured:result,text:JSON.stringify(result)});}
if(mode==="goal-clarify"){const result=await groq([{role:"system",content:"You are VOW AI. Return ONLY JSON with exactly: questions (max 3 strings), recommended_duration_weeks (integer 1-52), rationale (short). Ask only questions that materially improve the plan."},{role:"user",content:JSON.stringify({goal:compact,message,answers})}],"clarify");result.questions=arr(result.questions,3,220);result.recommended_duration_weeks=Math.min(52,Math.max(1,Number(result.recommended_duration_weeks)||weeksN));result.rationale=str(result.rationale,400);await record(userId,"clarify");return json({structured:result,text:JSON.stringify(result)});}
const result=await groq([{role:"system",content:"You are VOW AI. Return ONLY JSON with one key: text. Answer briefly and concretely."},{role:"user",content:JSON.stringify({goal:compact,message,answers})}],"chat");await record(userId,"chat");return json({text:str(result?.text,1600)||"I couldn't generate a response right now."});
}catch(e){const m=e instanceof Error?e.message:String(e);console.error("vow-goal-ai",m);if(m==="GROQ_429")return json({error:"VOW AI is temporarily busy. Please try again shortly."},429,{"Retry-After":"30"});if(m==="GROQ_API_KEY_MISSING")return json({error:"VOW AI is temporarily unavailable."},503);if(m==="AI_USAGE_CHECK_FAILED")return json({error:"VOW AI could not check availability. Please try again."},503);if(m==="PLAN_SAVE_FAILED")return json({error:"The AI plan was created but could not be saved. Please try again."},500);return json({error:"VOW AI could not complete that request right now. Please try again."},500);}});