import { serve } from 'https://deno.land/std@0.224.0/http/server.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const corsHeaders = { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type' };
const GOOGLE_CALENDAR_API = 'https://www.googleapis.com/calendar/v3';
const CALENDAR_EVENTS_SCOPE = 'https://www.googleapis.com/auth/calendar.events';
const CALENDAR_FULL_SCOPE = 'https://www.googleapis.com/auth/calendar';
function json(data: unknown, status = 200) { return new Response(JSON.stringify(data), { status, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }); }
function reauth(message: string) { return Object.assign(new Error(message), { code: 'REAUTH_REQUIRED' }); }
function hasWriteScope(scope: string) { return scope.split(/\s+/).some(value => value === CALENDAR_EVENTS_SCOPE || value === CALENDAR_FULL_SCOPE); }
async function refreshAccessToken(connection: Record<string, unknown>, admin: ReturnType<typeof createClient>) { let accessToken = connection.access_token as string | null; const expired = Boolean(connection.expires_at && new Date(String(connection.expires_at)).getTime() <= Date.now()); if (!expired) return accessToken; const refreshToken = connection.refresh_token as string | null; if (!refreshToken) throw reauth('Google Calendar authorization has expired. Please reconnect Google Calendar.'); const clientId = Deno.env.get('GOOGLE_CALENDAR_CLIENT_ID'); const clientSecret = Deno.env.get('GOOGLE_CALENDAR_CLIENT_SECRET'); if (!clientId || !clientSecret) throw new Error('Google OAuth configuration is missing'); const response = await fetch('https://oauth2.googleapis.com/token', { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams({ client_id: clientId, client_secret: clientSecret, refresh_token: refreshToken, grant_type: 'refresh_token' }) }); const data = await response.json(); if (!response.ok || !data.access_token) { if (data.error === 'invalid_grant') throw reauth('Google Calendar authorization is no longer valid. Please reconnect Google Calendar.'); throw new Error(data.error_description || 'Failed to refresh Google access token'); } accessToken = data.access_token; const { error } = await admin.from('google_calendar_connections').update({ access_token: accessToken, expires_at: data.expires_in ? new Date(Date.now() + data.expires_in * 1000).toISOString() : connection.expires_at, updated_at: new Date().toISOString() }).eq('user_id', connection.user_id); if (error) throw error; return accessToken; }
async function googleRequest(path: string, accessToken: string, init?: RequestInit) { const response = await fetch(`${GOOGLE_CALENDAR_API}${path}`, { ...init, headers: { Authorization: `Bearer ${accessToken}`, ...(init?.headers || {}) } }); if (response.status === 204) return null; const data = await response.json().catch(() => ({})); if (!response.ok) { if (response.status === 401) throw reauth('Google Calendar authorization is no longer valid. Please reconnect Google Calendar.'); throw new Error(data.error?.message || 'Google Calendar request failed'); } return data; }
function nextAvailableSlot(start: Date, occupied: Set<string>, durationMinutes: number) { const candidate = new Date(start); for (let attempt = 0; attempt < 48; attempt += 1) { const key = candidate.toISOString(); if (!occupied.has(key)) return candidate; candidate.setMinutes(candidate.getMinutes() + Math.max(30, Math.min(120, durationMinutes))); } throw new Error('Could not find an available calendar slot.'); }
serve(async req => { if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders }); try { const authHeader = req.headers.get('Authorization'); if (!authHeader) return json({ error: 'Missing authorization header' }, 401); const supabaseUrl = Deno.env.get('SUPABASE_URL'); const anonKey = Deno.env.get('SUPABASE_ANON_KEY'); const serviceRoleKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY'); if (!supabaseUrl || !anonKey || !serviceRoleKey) throw new Error('Supabase environment variables are missing'); const userClient = createClient(supabaseUrl, anonKey, { global: { headers: { Authorization: authHeader } } }); const { data: { user }, error: userError } = await userClient.auth.getUser(); if (userError || !user) return json({ error: 'Not authenticated' }, 401); const admin = createClient(supabaseUrl, serviceRoleKey); const body = await req.json().catch(() => ({})); const goalId = typeof body?.goalId === 'string' ? body.goalId : ''; if (!goalId) return json({ error: 'goalId is required' }, 400);
 const { data: goal, error: goalError } = await admin.from('goals').select('id,user_id,title').eq('id', goalId).eq('user_id', user.id).maybeSingle(); if (goalError) throw goalError; if (!goal) return json({ error: 'Goal not found' }, 404); const { data: connection, error: connectionError } = await admin.from('google_calendar_connections').select('*').eq('user_id', user.id).maybeSingle(); if (connectionError) throw connectionError; if (!connection) return json({ connected: false, created_count: 0, deleted_count: 0 }); if (!hasWriteScope(String(connection.scope || ''))) return json({ connected: false, needsReauth: true, created_count: 0, deleted_count: 0 });
 let accessToken: string; try { accessToken = await refreshAccessToken(connection as Record<string, unknown>, admin) as string; } catch (error) { if (error instanceof Error && 'code' in error) return json({ connected: false, needsReauth: true, error: error.message }, 401); throw error; } if (!accessToken) return json({ connected: false, needsReauth: true }, 401);
 const { data: sessions, error: sessionError } = await admin.from('sessions').select('id,title,scheduled_at,duration_minutes,notes,external_event_id,status').eq('goal_id', goalId).eq('user_id', user.id).order('scheduled_at', { ascending: true }); if (sessionError) throw sessionError; const { data: planItems, error: planError } = await admin.from('goal_plan_items').select('id,week_number,day_of_week,scheduled_at,task,purpose,target_metric,duration_minutes,status,external_event_id').eq('goal_id', goalId).eq('user_id', user.id).order('scheduled_at', { ascending: true }); if (planError) throw planError;
 const { data: otherSessions, error: otherSessionError } = await admin.from('sessions').select('scheduled_at,status').eq('user_id', user.id).neq('goal_id', goalId).eq('status', 'scheduled'); if (otherSessionError) throw otherSessionError;
 const oldEventIds = new Set<string>(); for (const row of [...(sessions || []), ...(planItems || [])]) if (row.external_event_id) oldEventIds.add(row.external_event_id); let deletedCount = 0; for (const eventId of oldEventIds) { try { await googleRequest(`/calendars/primary/events/${encodeURIComponent(eventId)}`, accessToken, { method: 'DELETE' }); deletedCount += 1; } catch (error) { if (error instanceof Error && 'code' in error) throw error; console.warn('[VOW Calendar] Could not delete old event', eventId, error); } }
 if (oldEventIds.size) { const { error: clearSessions } = await admin.from('sessions').update({ external_event_id: null }).eq('goal_id', goalId).eq('user_id', user.id); if (clearSessions) throw clearSessions; const { error: clearPlanItems } = await admin.from('goal_plan_items').update({ external_event_id: null }).eq('goal_id', goalId).eq('user_id', user.id); if (clearPlanItems) throw clearPlanItems; }
 const occupied = new Set<string>((otherSessions || []).map(row => new Date(row.scheduled_at).toISOString())); const sessionByTime = new Map((sessions || []).filter(s => s.status === 'scheduled').map(s => [`${s.scheduled_at}|${s.title}`, s])); let createdCount = 0; for (const item of planItems || []) { if (item.status !== 'scheduled') continue; const session = sessionByTime.get(`${item.scheduled_at}|${item.task}`); const requestedStart = new Date(item.scheduled_at); const durationMinutes = Math.max(5, item.duration_minutes || 60); const start = nextAvailableSlot(requestedStart, occupied, durationMinutes); const end = new Date(start.getTime() + durationMinutes * 60000); const changed = start.toISOString() !== requestedStart.toISOString(); if (changed) { const { error: planMoveError } = await admin.from('goal_plan_items').update({ scheduled_at: start.toISOString() }).eq('id', item.id).eq('user_id', user.id); if (planMoveError) throw planMoveError; if (session?.id) { const { error: sessionMoveError } = await admin.from('sessions').update({ scheduled_at: start.toISOString() }).eq('id', session.id).eq('user_id', user.id); if (sessionMoveError) throw sessionMoveError; } } occupied.add(start.toISOString()); const description = [item.purpose, item.target_metric ? `Target: ${item.target_metric}` : null, `VOW goal: ${goal.title}`, `Week ${item.week_number} · ${item.day_of_week}`].filter(Boolean).join('\n'); const event = await googleRequest('/calendars/primary/events', accessToken, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ summary: `VOW: ${item.task}`, description, start: { dateTime: start.toISOString() }, end: { dateTime: end.toISOString() }, reminders: { useDefault: true } }) }); createdCount += 1; if (event?.id) { const { error: planUpdateError } = await admin.from('goal_plan_items').update({ external_event_id: event.id }).eq('id', item.id).eq('user_id', user.id); if (planUpdateError) throw planUpdateError; if (session?.id) { const { error: sessionUpdateError } = await admin.from('sessions').update({ external_event_id: event.id }).eq('id', session.id).eq('user_id', user.id); if (sessionUpdateError) throw sessionUpdateError; } } }
 return json({ connected: true, created_count: createdCount, deleted_count: deletedCount }); } catch (error) { console.error('[VOW Calendar Goal Sync]', error); if (error instanceof Error && 'code' in error) return json({ connected: false, needsReauth: true, error: error.message }, 401); return json({ error: error instanceof Error ? error.message : 'Unexpected error' }, 500); } });
