import { serve } from "https://deno.land/std@0.224.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const corsHeaders = { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type" };
const GOOGLE_CALENDAR_API = "https://www.googleapis.com/calendar/v3";
function json(data: unknown, status = 200) { return new Response(JSON.stringify(data), { status, headers: { ...corsHeaders, "Content-Type": "application/json" } }); }
async function refreshAccessToken(connection: Record<string, unknown>, admin: ReturnType<typeof createClient>) { let accessToken = connection.access_token as string | null; const expired = Boolean(connection.expires_at && new Date(String(connection.expires_at)).getTime() <= Date.now()); if (!expired) return accessToken; const refreshToken = connection.refresh_token as string | null; if (!refreshToken) throw Object.assign(new Error("Google Calendar authorization has expired. Please reconnect Google Calendar."), { code: "REAUTH_REQUIRED" }); const clientId = Deno.env.get("GOOGLE_CALENDAR_CLIENT_ID"); const clientSecret = Deno.env.get("GOOGLE_CALENDAR_CLIENT_SECRET"); if (!clientId || !clientSecret) throw new Error("Google OAuth configuration is missing"); const response = await fetch("https://oauth2.googleapis.com/token", { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ client_id: clientId, client_secret: clientSecret, refresh_token: refreshToken, grant_type: "refresh_token" }) }); const data = await response.json(); if (!response.ok || !data.access_token) { if (data.error === "invalid_grant") throw Object.assign(new Error("Google Calendar authorization is no longer valid. Please reconnect Google Calendar."), { code: "REAUTH_REQUIRED" }); throw new Error(data.error_description || "Failed to refresh Google access token"); } accessToken = data.access_token; const { error } = await admin.from("google_calendar_connections").update({ access_token: accessToken, expires_at: data.expires_in ? new Date(Date.now() + data.expires_in * 1000).toISOString() : connection.expires_at, updated_at: new Date().toISOString() }).eq("user_id", connection.user_id); if (error) throw error; return accessToken; }
async function googleGet(path: string, accessToken: string) { const response = await fetch(`${GOOGLE_CALENDAR_API}${path}`, { headers: { Authorization: `Bearer ${accessToken}` } }); const data = await response.json(); if (!response.ok) { if (response.status === 401) throw Object.assign(new Error("Google Calendar authorization is no longer valid. Please reconnect Google Calendar."), { code: "REAUTH_REQUIRED" }); throw new Error(data.error?.message || "Google Calendar request failed"); } return data; }
async function listAllCalendarEvents(calendarId: string, accessToken: string, timeMin: string, timeMax: string) { const events: unknown[] = []; let pageToken = ''; do { const params = new URLSearchParams({ timeMin, timeMax, singleEvents: 'true', orderBy: 'startTime', showDeleted: 'false', maxResults: '2500' }); if (pageToken) params.set('pageToken', pageToken); const data = await googleGet(`/calendars/${encodeURIComponent(calendarId)}/events?${params.toString()}`, accessToken); if (Array.isArray(data.items)) events.push(...data.items); pageToken = typeof data.nextPageToken === 'string' ? data.nextPageToken : ''; } while (pageToken); return events; }
serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });
  try {
    const authHeader = req.headers.get("Authorization"); if (!authHeader) return json({ error: "Missing authorization header" }, 401); const supabaseUrl = Deno.env.get("SUPABASE_URL"); const supabaseAnonKey = Deno.env.get("SUPABASE_ANON_KEY"); const serviceRoleKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"); if (!supabaseUrl || !supabaseAnonKey || !serviceRoleKey) throw new Error("Supabase environment variables are missing"); const userClient = createClient(supabaseUrl, supabaseAnonKey, { global: { headers: { Authorization: authHeader } } }); const { data: { user }, error: userError } = await userClient.auth.getUser(); if (userError || !user) return json({ error: "Not authenticated" }, 401); const admin = createClient(supabaseUrl, serviceRoleKey); const { data: connection, error: connectionError } = await admin.from("google_calendar_connections").select("*").eq("user_id", user.id).maybeSingle(); if (connectionError) throw connectionError; if (!connection) return json({ error: "Google Calendar is not connected" }, 400); let accessToken: string; try { accessToken = await refreshAccessToken(connection as Record<string, unknown>, admin) as string; } catch (error) { if (error instanceof Error && 'code' in error) return json({ error: error.message, code: (error as Error & { code: string }).code }, 401); throw error; } if (!accessToken) return json({ error: "Google Calendar authorization is incomplete. Please reconnect Google Calendar.", code: "REAUTH_REQUIRED" }, 401);
    const body = await req.json().catch(() => ({})); const action = body?.action || "list";
    if (action === "list") {
      const timeMin = body?.timeMin || new Date(new Date().setMonth(new Date().getMonth() - 1)).toISOString(); const timeMax = body?.timeMax || new Date(new Date().setMonth(new Date().getMonth() + 12)).toISOString(); const calendarList = await googleGet(`/users/me/calendarList?minAccessRole=reader&showHidden=false&maxResults=250`, accessToken); const calendars = Array.isArray(calendarList.items) ? calendarList.items : []; const allEvents: unknown[] = [];
      for (const calendar of calendars) { const calendarId = typeof calendar.id === 'string' ? calendar.id : null; if (!calendarId) continue; try { const events = await listAllCalendarEvents(calendarId, accessToken, timeMin, timeMax); for (const event of events) allEvents.push({ ...(event as Record<string, unknown>), calendarId, calendarName: calendar.summary || calendarId }); } catch (error) { console.warn('[VOW Calendar] Skipping unreadable calendar', calendarId, error); } }
      allEvents.sort((a, b) => { const getStart = (value: unknown) => { const item = value as { start?: { dateTime?: string; date?: string } }; return item.start?.dateTime || item.start?.date || ''; }; return getStart(a).localeCompare(getStart(b)); }); return json({ events: allEvents, calendars: calendars.map((calendar: { id?: string; summary?: string; primary?: boolean; accessRole?: string }) => ({ id: calendar.id, summary: calendar.summary, primary: calendar.primary, accessRole: calendar.accessRole })) });
    }
    if (action === "create") { const event = body?.event; if (!event) return json({ error: "Missing event" }, 400); const response = await fetch(`${GOOGLE_CALENDAR_API}/calendars/primary/events`, { method: "POST", headers: { Authorization: `Bearer ${accessToken}`, "Content-Type": "application/json" }, body: JSON.stringify(event) }); const data = await response.json(); if (!response.ok) { if (response.status === 401) return json({ error: "Google Calendar authorization is no longer valid. Please reconnect Google Calendar.", code: "REAUTH_REQUIRED" }, 401); throw new Error(data.error?.message || "Failed to create Google Calendar event"); } return json({ event: data }); }
    return json({ error: "Unknown action" }, 400);
  } catch (error) { console.error("[VOW Calendar API]", error); if (error instanceof Error && 'code' in error) return json({ error: error.message, code: (error as Error & { code: string }).code }, 401); return json({ error: error instanceof Error ? error.message : "Unexpected error" }, 500); }
});
