import { site } from "./site"; import { p, ul, type LegalSection } from "./legal-types";
export const privacyIntro=`VOW is operated by ${site.operator} in connection with the VOW application. This Privacy Policy explains what information VOW collects, how it is used, and the choices available to you.`;
export const privacySections:LegalSection[]=[
{id:"information-we-collect",heading:"1. Information We Collect",blocks:[p("Depending on how you use VOW, we may collect account information such as your email address and profile details; goals, plans, milestones, sessions, reviews, journal entries and progress content; preferences and settings; and technical or diagnostic information needed to operate and secure the service.") ,p("Information from optional connected features, such as calendar or fitness integrations, is processed when you authorise those features.") ]},
{id:"ai",heading:"2. AI-Assisted Features",blocks:[p("VOW may process goal, planning, progress and related inputs through VOW's AI infrastructure and relevant third-party AI providers to provide AI-assisted functionality, such as suggested plans."),p("AI outputs are for planning and productivity support only and are not professional medical, financial, legal or other regulated advice.") ]},
{id:"connected-services",heading:"3. Connected Services",blocks:[p("Where enabled by you, VOW can connect to services such as Google Calendar and Strava. These integrations are user-authorised and can be disconnected through VOW or the relevant service's account controls."),p("VOW accesses information needed for the connected feature you chose to use.") ]},
{id:"notifications",heading:"4. Notifications",blocks:[p("VOW may use session dates, times and notification preferences to deliver local reminders. Notifications can be controlled in VOW and through your device settings.") ]},
{id:"payments",heading:"5. Payments",blocks:[p("Subscriptions and purchases are processed through the applicable payment or distribution provider, including Google Play where applicable. VOW does not intentionally collect or store raw payment-card numbers."),p("VOW may receive subscription identifiers, entitlement and status information and transaction-related metadata needed to provide Premium access and support.") ]},
{id:"use",heading:"6. How We Use Information",blocks:[p("VOW uses information to:"),ul(["authenticate users and secure accounts","provide and personalise VOW","generate AI-assisted plans and suggestions","manage goals, milestones and sessions","provide enabled integrations","send requested reminders","provide Premium features","prevent abuse and protect security","diagnose issues and provide support","comply with legal obligations","maintain and improve the service"])]},
{id:"sharing",heading:"7. Sharing and Service Providers",blocks:[p("VOW may process data with infrastructure and service providers needed to operate the product, including database and authentication infrastructure, AI providers, user-authorised integrations, and payment or distribution providers."),p("VOW does not sell personal information.") ]},
{id:"security",heading:"8. Security",blocks:[p("VOW uses reasonable technical and organisational safeguards, including encrypted connections, access controls and server-side controls intended to protect data and limit abuse. No service can guarantee absolute security.") ]},
{id:"retention",heading:"9. Retention and Deletion",blocks:[p("Information is retained for as long as reasonably necessary to provide the service, maintain security, resolve disputes, meet legal obligations and enforce agreements. When information is no longer required, it may be deleted or anonymised, subject to legitimate retention needs.") ]},
{id:"rights",heading:"10. Your Choices and Rights",blocks:[p("Depending on applicable law, you may have rights to access, correct, delete or request a copy of personal information. You can also withdraw optional integration permissions, disconnect connected services and control notification preferences.") ,p(`To exercise applicable rights, contact ${site.privacyEmail}.`) ]},
{id:"international",heading:"11. International Processing",blocks:[p("VOW and its service providers may process information in countries other than your country of residence. Appropriate safeguards will be used where required by applicable law.") ]},
{id:"young-users",heading:"12. Children and Young Users",blocks:[p("VOW is not specifically designed for children and does not intentionally bypass applicable age restrictions or parental-consent requirements.") ]},
{id:"third-party",heading:"13. Third-Party Services",blocks:[p("Google, Strava, Google Play and other third-party providers have their own terms and privacy policies. VOW does not control those services.") ]},
{id:"changes",heading:"14. Changes to This Policy",blocks:[p("This policy may be updated as VOW changes. The last-updated date will be revised when material changes are made.") ]},
{id:"contact",heading:"15. Contact",blocks:[ul([`Privacy: ${site.privacyEmail}`,`Support: ${site.supportEmail}`])]}
];