import { site } from "./site"; import { p, ul, type LegalSection } from "./legal-types";
export const termsIntro=`These Terms of Use and End User Licence Agreement govern your use of the VOW application and related services provided by ${site.operator}. By creating an account or using VOW, you agree to these Terms.`;
export const termsSections:LegalSection[]=[
{id:"licence",heading:"1. Licence to Use VOW",blocks:[p("VOW grants you a limited, personal, non-exclusive, non-transferable and revocable licence to use the app for your own personal, non-commercial purposes, subject to these Terms."),p("You may not copy, modify, distribute, sell, lease, reverse engineer or attempt to extract source code except where applicable law expressly permits.") ]},
{id:"accounts",heading:"2. Eligibility and Accounts",blocks:[p("You must meet the minimum age required by applicable law and by the platform you download VOW from. You are responsible for maintaining account security and for activity under your account.") ]},
{id:"acceptable-use",heading:"3. Acceptable Use",blocks:[p("You agree not to:"),ul(["use VOW for unlawful purposes","attempt unauthorised access to VOW, accounts or connected systems","interfere with the operation or security of the service","upload unlawful, harmful or infringing content","misrepresent your identity or affiliation","abuse automated or AI features"])]},
{id:"content",heading:"4. Your Content",blocks:[p("You retain ownership of goals, plans, journal entries and other content you create. You grant VOW a limited licence to host and process that content as needed to provide, secure and improve the service, including AI features you choose to use.") ]},
{id:"subscriptions",heading:"5. Subscriptions and Purchases",blocks:[p("Some features may require Premium. Subscriptions are purchased and billed through the applicable distribution platform, such as Google Play, and are subject to that platform's pricing, renewal and refund rules.") ]},
{id:"ai",heading:"6. AI-Assisted Features",blocks:[p("VOW may generate plans, suggestions and summaries using AI. AI output can be inaccurate or incomplete. Review it before acting on it. AI output is not professional medical, financial, legal or other regulated advice.") ]},
{id:"fitness",heading:"7. Health and Fitness",blocks:[p("VOW is not a medical or professional fitness service. Exercise or training decisions remain your responsibility. Seek qualified professional advice where appropriate.") ]},
{id:"third-party",heading:"8. Third-Party Services",blocks:[p("VOW may connect to third-party services such as Google Calendar and Strava. Your use of those services is governed by their own terms and privacy policies.") ]},
{id:"ip",heading:"9. Intellectual Property",blocks:[p(`VOW software, design, branding, text and graphics are owned by ${site.operator} and protected by applicable intellectual property laws. Except for the licence granted above, no rights are granted to you.`) ]},
{id:"termination",heading:"10. Termination",blocks:[p("You may stop using VOW and request account deletion. VOW may suspend or terminate access where you breach these Terms or where reasonably necessary to protect the service or other users.") ]},
{id:"disclaimers",heading:"11. Disclaimers",blocks:[p("VOW is provided on an as-is and as-available basis to the fullest extent permitted by law. VOW does not guarantee uninterrupted service, error-free operation or any particular goal or result.") ]},
{id:"liability",heading:"12. Limitation of Liability",blocks:[p("To the fullest extent permitted by law, VOW and its operator will not be liable for indirect, incidental, special, consequential or punitive damages arising from use of VOW. Nothing limits liability that cannot legally be limited.") ]},
{id:"changes",heading:"13. Changes to These Terms",blocks:[p("VOW may update these Terms from time to time. The last-updated date will be revised when material changes are made.") ]},
{id:"contact",heading:"14. Contact",blocks:[ul([`Support: ${site.supportEmail}`,`Privacy: ${site.privacyEmail}`])]}
];