import { useEffect, useMemo, useState } from 'react';
import { PageHeader } from './AppShell';
import { INTEGRATIONS, type IntegrationCategory, type IntegrationDefinition } from '@/lib/integrations/catalog';
import { supabase } from '@/lib/supabase';
import { useAuth } from '@/lib/auth';
import { Browser } from '@capacitor/browser';
import { Capacitor } from '@capacitor/core';
import { NATIVE_CALENDAR_REDIRECT } from '@/lib/nativeAuth';
import type { Goal } from '@/types/database';

function Glyph({ children, className = '' }: { children: string; className?: string }) { return <span aria-hidden="true" className={`inline-flex items-center justify-center font-medium leading-none ${className}`}>{children}</span>; }
type ConnectState = Record<string, 'connected' | 'setup'>;
type ActiveGoal = Pick<Goal, 'id' | 'title' | 'outcome' | 'status' | 'armadillo'>;
const categories: { id: IntegrationCategory | 'all'; label: string }[] = [
  { id: 'all', label: 'All' }, { id: 'fitness', label: 'Fitness' }, { id: 'health', label: 'Health' }, { id: 'education', label: 'Education' }, { id: 'productivity', label: 'Productivity' }, { id: 'reading', label: 'Reading' }, { id: 'mindfulness', label: 'Mindfulness' }, { id: 'faith', label: 'Faith' },
];
function integrationMatchesGoal(integration: IntegrationDefinition, goal: ActiveGoal): boolean {
  const armadillo = goal.armadillo && typeof goal.armadillo === 'object' ? goal.armadillo : {};
  const integration = typeof armadillo.integration === 'string' ? armadillo.integration : '';
  const evidenceSource = Array.isArray(armadillo.evidence_source) ? armadillo.evidence_source.filter((value): value is string => typeof value === 'string') : [];
  const evidence = Array.isArray(armadillo.evidence) ? armadillo.evidence.filter((value): value is string => typeof value === 'string') : [];
  const category = typeof armadillo.category === 'string' ? armadillo.category : '';
  const goalType = typeof armadillo.goal_type === 'string' ? armadillo.goal_type : '';
  const haystack = [integration, ...evidenceSource, ...evidence, category, goalType, goal.title, goal.outcome].filter(Boolean).join(' ').toLowerCase();
  if (haystack.includes(integration.id.toLowerCase()) || haystack.includes(integration.name.toLowerCase())) return true;
  return integration.recommendedGoalKeywords.some((keyword) => haystack.includes(keyword.toLowerCase())) && Boolean(integration || evidenceSource.length);
}
export function ConnectPage({ onBack }: { onBack?: () => void }) {
  const { session } = useAuth(); const userId = session?.user.id; const connectionKey = userId ? `vow:connections:${userId}` : '';
  const [category, setCategory] = useState<IntegrationCategory | 'all'>('all'); const [query, setQuery] = useState(''); const [connected, setConnected] = useState<ConnectState>({}); const [connecting, setConnecting] = useState<string | null>(null); const [googleCalendarConnected, setGoogleCalendarConnected] = useState(false); const [googleCalendarAvailable, setGoogleCalendarAvailable] = useState(false); const [activeGoals, setActiveGoals] = useState<ActiveGoal[]>([]); const [loadingGoals, setLoadingGoals] = useState(false);
  useEffect(() => { if (!userId) { setConnected({}); return; } try { setConnected(JSON.parse(localStorage.getItem(connectionKey) || '{}')); } catch { setConnected({}); } }, [userId, connectionKey]);
  useEffect(() => { if (userId) localStorage.setItem(connectionKey, JSON.stringify(connected)); }, [connected, userId, connectionKey]);
  useEffect(() => { if (!userId) { setActiveGoals([]); return; } let cancelled = false; setLoadingGoals(true); supabase.from('goals').select('id,title,outcome,status,armadillo').eq('user_id', userId).eq('status', 'active').then(({ data, error }) => { if (!cancelled) { setActiveGoals(error ? [] : ((data || []) as ActiveGoal[])); setLoadingGoals(false); } }); return () => { cancelled = true; }; }, [userId]);
  useEffect(() => { if (!session) return; let cancelled = false; supabase.functions.invoke('google-calendar-auth', { body: { action: 'status' } }).then(({ data, error }) => { if (cancelled) return; const available = !error && data?.available === true && data?.configured === true; setGoogleCalendarAvailable(available); setGoogleCalendarConnected(available && Boolean(data?.connected)); if (available && data?.connected) setConnected((current) => ({ ...current, 'google-calendar': 'connected' })); }).catch(() => { if (!cancelled) { setGoogleCalendarAvailable(false); setGoogleCalendarConnected(false); } }); return () => { cancelled = true; }; }, [session]);
  const goalRelevantIntegrations = useMemo(() => INTEGRATIONS.filter((integration) => activeGoals.some((goal) => integrationMatchesGoal(integration, goal))), [activeGoals]);
  const integrations = useMemo(() => { const q = query.trim().toLowerCase(); return goalRelevantIntegrations.filter((integration) => { const categoryMatch = category === 'all' || integration.category === category; const queryMatch = !q || `${integration.name} ${integration.description} ${integration.category}`.toLowerCase().includes(q); return categoryMatch && queryMatch; }); }, [category, query, goalRelevantIntegrations]);
  async function connectIntegration(id: string) { if (!session || connecting || id !== 'google-calendar' || !googleCalendarAvailable) return; setConnecting(id); try { const redirectUri = Capacitor.isNativePlatform() ? NATIVE_CALENDAR_REDIRECT : `${window.location.origin}/calendar/oauth/callback`; const { data, error: invokeError } = await supabase.functions.invoke('google-calendar-auth', { body: { action: 'start', redirectUri } }); if (invokeError || !data?.authorizationUrl) throw invokeError || new Error('Google Calendar is not configured yet.'); if (Capacitor.isNativePlatform()) await Browser.open({ url: data.authorizationUrl }); else window.location.assign(data.authorizationUrl); } catch { setGoogleCalendarAvailable(false); } finally { setConnecting(null); } }
  return <div>
    {onBack && <button onClick={onBack} className="text-sm text-vow-muted hover:text-vow-ink mb-6 flex items-center gap-1 transition-colors"><Glyph>←</Glyph>Back to profile</button>}
    <PageHeader title="Hedgehog" subtitle="Third-party connectors that matter to your active VOWs." />
    <section className="mb-8 border border-vow-border p-5 md:p-6"><h2 className="text-sm font-medium text-vow-ink mb-1">Goal-driven connections</h2><p className="text-sm text-vow-muted leading-relaxed">Hedgehog only surfaces services that an active VOW can use for evidence, context or execution. You do not need to browse a catalogue of connectors that have nothing to do with your goals.</p></section>
    <div className="mb-5"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search third-party connectors" aria-label="Search third-party connectors" className="w-full border border-vow-border bg-transparent px-4 py-3 text-sm text-vow-ink outline-none focus:border-vow-ink" /></div>
    {goalRelevantIntegrations.length > 0 && <div className="flex gap-2 overflow-x-auto pb-2 mb-6 scrollbar-hide">{categories.map((item) => <button key={item.id} onClick={() => setCategory(item.id)} aria-pressed={category === item.id} className={`whitespace-nowrap px-3 py-2 text-xs border transition-colors ${category === item.id ? 'border-vow-ink text-vow-ink' : 'border-vow-border text-vow-muted hover:text-vow-ink'}`}>{item.label}</button>)}</div>}
    {loadingGoals ? <div className="border border-vow-border p-8 text-center"><p className="text-sm text-vow-muted">Checking your active VOWs…</p></div> : integrations.length === 0 ? <div className="border border-vow-border p-8 text-center"><p className="text-sm text-vow-ink mb-1">No third-party connectors are needed right now</p><p className="text-xs text-vow-muted">When an active VOW needs an external service for evidence, context or execution, it will appear here.</p></div> : <div className="space-y-2">{integrations.map((integration) => { const isConnected = integration.id === 'google-calendar' ? googleCalendarConnected : connected[integration.id] === 'connected'; const unavailable = integration.status === 'setup-required' || (integration.id === 'google-calendar' && !googleCalendarAvailable); const actionUnavailable = unavailable || integration.id !== 'google-calendar'; const relatedGoals = activeGoals.filter((goal) => integrationMatchesGoal(integration, goal)); return <div key={integration.id} className="border border-vow-border p-4 md:p-5 flex items-center gap-4"><div className="w-11 h-11 border border-vow-border flex items-center justify-center shrink-0 bg-white p-2"><img src={integration.iconUrl} alt="" className="w-full h-full object-contain" loading="lazy" onError={(event) => { event.currentTarget.style.display = 'none'; }} /></div><div className="min-w-0 flex-1"><div className="flex items-center gap-2 flex-wrap"><h3 className="text-sm font-medium text-vow-ink">{integration.name}</h3>{isConnected && <span className="text-[10px] text-vow-ink">Connected</span>}{actionUnavailable && !isConnected && <span className="text-[10px] text-vow-muted">Coming later</span>}</div><p className="text-xs text-vow-muted mt-1 leading-relaxed">{integration.description}</p><p className="text-[10px] text-vow-muted mt-2">For: {relatedGoals.map((goal) => goal.title).slice(0, 2).join(' · ')}{relatedGoals.length > 2 ? ` +${relatedGoals.length - 2} more` : ''}</p><p className="text-[10px] text-vow-muted mt-1">Evidence: {integration.evidence.join(' · ')}</p></div><button disabled={isConnected || actionUnavailable || connecting === integration.id} onClick={() => connectIntegration(integration.id)} className={`shrink-0 px-3 py-2 text-xs border transition-colors ${isConnected ? 'border-vow-border text-vow-muted' : actionUnavailable ? 'border-vow-border text-vow-muted opacity-50 cursor-not-allowed' : 'border-vow-ink text-vow-ink hover:bg-vow-border/40 disabled:opacity-50'}`}>{isConnected ? 'Connected' : actionUnavailable ? 'Coming later' : connecting === integration.id ? 'Connecting…' : 'Connect'}</button></div>; })}</div>}
  </div>;
}
