import { useEffect, useMemo, useState } from 'react';
import { supabase } from '@/lib/supabase';
import { checkContentSafety } from '@/lib/contentSafety';
import { analyseGoalForEvidence, type ArmadilloResult } from '@/lib/armadillo';
import { inferHamsterMode, buildHamsterContext, HAMSTER_WORKFLOWS, type HamsterMode } from '@/lib/hamster';
import { specialistFor } from '@/lib/domainRouter';
import { PageHeader } from './AppShell';

type DraftGoal={id:string;title?:string|null;outcome?:string|null;why_it_matters?:string|null;plan_json?:unknown};
type HamsterPlan={mode:HamsterMode;domain:string;completion_definition:string;overview:string;success_metric:string;horizon:string;cadence:string;deadline:string;steps:Array<{order:number;title:string;purpose:string;target:string;evidence:string;estimated_minutes:number}>;milestones:Array<{title:string;description:string}>;adaptation_rules:string[];next_action:string;workflow?:Record<string,unknown>;knowledge_count?:number};
type ClarificationRow={question?:unknown;answer?:unknown;question_order?:unknown};

export function GoalPlanner({userId,onCreated,onCancel,draftGoal}:{userId:string;onCreated:()=>void;onCancel?:()=>void|Promise<void>;draftGoal?:DraftGoal|null}){
 const [goal,setGoal]=useState(draftGoal?.title||draftGoal?.outcome||''); const [why,setWhy]=useState(draftGoal?.why_it_matters||''); const [armadillo,setArmadillo]=useState<ArmadilloResult|null>(null); const [specialist,setSpecialist]=useState<ReturnType<typeof specialistFor>>(null);
 const [mode,setMode]=useState<HamsterMode|null>(null); const [questions,setQuestions]=useState<string[]>([]); const [answers,setAnswers]=useState<string[]>([]); const [plan,setPlan]=useState<HamsterPlan|null>(null); const [draftId,setDraftId]=useState<string|null>(draftGoal?.id||null); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
 const workflow=useMemo(()=>mode?HAMSTER_WORKFLOWS[mode]:null,[mode]);
 useEffect(()=>{if(!draftGoal?.id)return;setGoal(draftGoal.title||draftGoal.outcome||'');setWhy(draftGoal.why_it_matters||'');setDraftId(draftGoal.id);},[draftGoal?.id,draftGoal?.title,draftGoal?.outcome,draftGoal?.why_it_matters]);
 useEffect(()=>{if(!draftGoal?.id)return;let cancelled=false;(async()=>{const {data}=await supabase.from('goal_clarification_answers').select('question,answer,question_order').eq('goal_id',draftGoal.id).eq('user_id',userId).order('question_order',{ascending:true});if(cancelled||!data?.length)return;const rows=data as ClarificationRow[];const restoredQuestions:string[]=[];for(const row of rows.slice(0,4)){if(typeof row.question==='string'&&row.question.trim())restoredQuestions.push(row.question);}if(!restoredQuestions.length)return;const restoredAnswers:string[]=[];for(const row of rows.slice(0,restoredQuestions.length)){restoredAnswers.push(typeof row.answer==='string'?row.answer:'');}setQuestions(restoredQuestions);setAnswers(restoredAnswers);})();return()=>{cancelled=true;};},[draftGoal?.id,userId]);
 async function safe(text:string){if(!text.trim())return;const r=await checkContentSafety(text);if(r.status!=='safe')throw new Error(r.message||'Please reword the text and try again.');}
 async function draft(){if(draftId)return draftId;const {data,error:e}=await supabase.from('goals').insert({user_id:userId,title:goal.trim(),outcome:goal.trim(),why_it_matters:why.trim()||null,status:'draft',weekly_commitment_target:0}).select('id').single();if(e||!data)throw e||new Error('Could not start this goal.');setDraftId(data.id);return data.id;}
 async function start(){if(!goal.trim()||busy)return;setBusy(true);setError('');setPlan(null);try{await safe(goal);await safe(why);const a=analyseGoalForEvidence({title:goal,outcome:goal,why_it_matters:why});const s=specialistFor({title:goal,category:a.category,goal_type:a.goal_type});setArmadillo(a);setSpecialist(s);const inferred=inferHamsterMode({title:goal,outcome:goal,why_it_matters:why,category:a.category,goal_type:a.goal_type,target:a.target,time_target:a.time_target});setMode(inferred);const context=buildHamsterContext({title:goal,outcome:goal,why_it_matters:why,category:s?.domain||a.category,goal_type:s?.goal_types[0]||a.goal_type,planning_mode:inferred});const id=await draft();const {data,error:e}=await supabase.functions.invoke('vow-hamster',{body:{action:'clarify',goal:{id,title:goal.trim(),outcome:goal.trim(),why_it_matters:why.trim()||null},armadillo:{...a,category:s?.domain||a.category,goal_type:s?.goal_types[0]||a.goal_type},hamster_context:{...context,mode:inferred,domain:s},answers:[]}});if(e||!data?.structured)throw e||new Error(data?.error||'VOW could not personalise this goal.');const qs:string[]=Array.isArray(data.structured.questions)?data.structured.questions.filter((value:unknown):value is string=>typeof value==='string').slice(0,4):[];if(qs.length<2)throw new Error('VOW could not ask enough domain-specific questions.');setQuestions(qs);setAnswers(qs.map(()=>''));await supabase.from('goal_clarification_answers').delete().eq('goal_id',id).eq('user_id',userId);await supabase.from('goal_clarification_answers').insert(qs.map((question,index)=>({goal_id:id,user_id:userId,question,answer:null,question_order:index})));}catch(e){setError(e instanceof Error?e.message:'VOW could not start this goal.')}finally{setBusy(false)}}
 async function build(){if(!draftId||!questions.length||busy)return;setBusy(true);setError('');try{const clean=answers.map(a=>a.trim());if(clean.filter(Boolean).length<2)throw new Error('Give VOW at least two meaningful answers so the plan can be genuinely yours.');await safe(clean.join('\n'));await supabase.from('goal_clarification_answers').delete().eq('goal_id',draftId).eq('user_id',userId);await supabase.from('goal_clarification_answers').insert(questions.map((question,index)=>({goal_id:draftId,user_id:userId,question,answer:clean[index]||null,question_order:index})));const a=armadillo||analyseGoalForEvidence({title:goal,outcome:goal,why_it_matters:why});const s=specialist||specialistFor({title:goal,category:a.category,goal_type:a.goal_type});const ctx=buildHamsterContext({title:goal,outcome:goal,why_it_matters:why,category:s?.domain||a.category,goal_type:s?.goal_types[0]||a.goal_type,planning_mode:mode});const {data,error:e}=await supabase.functions.invoke('vow-hamster',{body:{action:'plan',goal:{id:draftId,title:goal.trim(),outcome:goal.trim(),why_it_matters:why.trim()||null},armadillo:{...a,category:s?.domain||a.category,goal_type:s?.goal_types[0]||a.goal_type},hamster_context:{...ctx,mode,domain:s},answers:questions.map((question,index)=>({question,answer:clean[index]||''}))}});if(e||!data?.structured)throw e||new Error(data?.error||'VOW could not build the plan.');const next=data.structured as HamsterPlan;if(next.mode!==mode)throw new Error('VOW changed the planning workflow unexpectedly.');if(!Array.isArray(next.steps)||!next.steps.length)throw new Error('VOW returned no actionable steps.');setPlan(next);}catch(e){setError(e instanceof Error?e.message:'VOW could not build this plan.')}finally{setBusy(false)}}
 async function lock(){if(!plan||!draftId||busy)return;setBusy(true);setError('');try{const context={hamster:{mode:plan.mode,workflow:HAMSTER_WORKFLOWS[plan.mode],specialist,plan},armadillo:armadillo||{},personalisation:{questions,answers,completed:answers.filter(Boolean).length>=2}};const {error:e}=await supabase.from('goals').update({title:goal.trim(),outcome:plan.completion_definition||goal.trim(),why_it_matters:why.trim()||null,status:'active',plan_json:plan,goal_context_json:context,plan_version:2,plan_generated_at:new Date().toISOString(),planning_horizon_weeks:null,planning_timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,deadline:null}).eq('id',draftId).eq('user_id',userId);if(e)throw e;await supabase.from('milestones').delete().eq('goal_id',draftId);if(plan.milestones?.length)await supabase.from('milestones').insert(plan.milestones.map((m,i)=>({goal_id:draftId,title:m.title,description:m.description,sort_order:i,status:i===0?'in_progress':'pending',deadline:null})));onCreated();}catch(e){setError(e instanceof Error?e.message:'Could not lock this VOW.')}finally{setBusy(false)}}
 if(plan)return <div><PageHeader title="Your VOW" subtitle={`${HAMSTER_WORKFLOWS[plan.mode].name} planning · ${plan.domain}`} /><div className="max-w-3xl space-y-5"><section className="border border-vow-border p-5"><p className="vow-label mb-2">How this goal works</p><p className="text-lg font-medium text-vow-ink">{plan.overview}</p><p className="text-sm text-vow-muted mt-3">{plan.completion_definition}</p></section><section className="border border-vow-border p-5"><p className="vow-label mb-3">Execution</p><div className="space-y-4">{plan.steps.map((s)=><div key={`${s.order}-${s.title}`} className="border-l-2 border-vow-ink pl-4"><p className="text-sm font-medium text-vow-ink">{s.order}. {s.title}</p><p className="text-xs text-vow-muted mt-1">{s.purpose}</p><p className="text-xs text-vow-muted mt-1">Target: {s.target} · Evidence: {s.evidence}{s.estimated_minutes?` · ~${s.estimated_minutes} min`:''}</p></div>)}</div></section><section className="border border-vow-border p-5"><p className="vow-label mb-3">Hamster</p><p className="text-sm text-vow-ink">{HAMSTER_WORKFLOWS[plan.mode].name}: {HAMSTER_WORKFLOWS[plan.mode].purpose}</p><p className="text-sm text-vow-muted mt-2">Horizon: {plan.horizon} · Cadence: {plan.cadence} · Deadline: {plan.deadline}</p><p className="text-sm text-vow-muted mt-2">{plan.next_action}</p></section>{plan.adaptation_rules?.length>0&&<section className="border border-vow-border p-5"><p className="vow-label mb-3">What changes the plan</p>{plan.adaptation_rules.map(rule=><p key={rule} className="text-sm text-vow-muted py-1">{rule}</p>)}</section>}{error&&<p className="text-sm text-vow-ink border-l-2 border-vow-ink pl-3">{error}</p>}<div className="flex gap-3"><button className="vow-btn-ghost" onClick={()=>setPlan(null)}>Adjust</button><button className="vow-btn-primary flex-1" onClick={lock} disabled={busy}>{busy?'Locking...':'Lock in VOW'}</button></div></div></div>;
 if(questions.length)return <div><PageHeader title="VOW needs your context" subtitle={`${workflow?.name||'Adaptive'} planning · ${specialist?.id||'new domain flow'}`} /><div className="max-w-xl space-y-5">{questions.map((q,i)=><div key={`${i}-${q}`}><label className="vow-label block mb-2" htmlFor={`vow-q-${i}`}>{q}</label><textarea id={`vow-q-${i}`} rows={4} value={answers[i]||''} onChange={e=>setAnswers(x=>x.map((a,j)=>j===i?e.target.value:a))} className="vow-input resize-none" placeholder="Your answer..." /></div>)}{error&&<p className="text-sm text-vow-ink border-l-2 border-vow-ink pl-3">{error}</p>}<div className="flex gap-3"><button className="vow-btn-ghost" onClick={()=>setQuestions([])}>Back</button><button className="vow-btn-primary flex-1" onClick={build} disabled={busy}>{busy?'Hamster is shaping the plan...':'Build my VOW'}</button></div></div></div>;
 return <div><PageHeader title="Make your VOW" subtitle="Tell VOW what you want to accomplish. The system chooses the right domain specialist and planning workflow for you." /><div className="max-w-xl space-y-5"><textarea autoFocus rows={4} value={goal} onChange={e=>setGoal(e.target.value)} className="vow-input resize-none" placeholder="e.g. Make ravioli for my family on Saturday" /><textarea rows={3} value={why} onChange={e=>setWhy(e.target.value)} className="vow-input resize-none" placeholder="Why does this matter?" />{error&&<p className="text-sm text-vow-ink border-l-2 border-vow-ink pl-3">{error}</p>}<div className="flex gap-3"><button className="vow-btn-ghost" onClick={()=>void onCancel?.()}>Cancel</button><button className="vow-btn-primary flex-1" disabled={!goal.trim()||busy} onClick={start}>{busy?'VOW is understanding your goal...':'Continue'}</button></div></div></div>;
}
