import { createElement, useState } from 'react';
import { FunctionsHttpError } from '@supabase/supabase-js';
import { supabase } from '@/lib/supabase';
import { checkContentSafety } from '@/lib/contentSafety';
import { analyseGoalForEvidence, type ArmadilloResult } from '@/lib/armadillo';

type Props={userId:string;onCreated:()=>void;onCancel?:()=>void};
type Question={question:string;answer:string};
type Template={sequence:number;task:string;purpose:string;target_metric:string;duration_minutes:number;preferred_time?:string};
type Plan={outcome:string;success_metric:string;baseline:string;planning_mode:'one_time'|'project'|'recurring'|'mastery'|'performance'|'event'|'adaptive';horizon_label:string;milestones:Array<{title:string;description:string;order:number}>;session_templates:Template[];weekly_focus:string[];progression:string;checkpoints:string[];risks:string[];fallback_rules:string[];summary:string};
const h=createElement;
const nextDate=(offset=0)=>{const d=new Date();d.setSeconds(0,0);d.setDate(d.getDate()+offset);return d;};
const dateOnly=(d:Date)=>{const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`;};
async function fnError(e:unknown){if(e instanceof FunctionsHttpError){try{const b=await e.context.json();return b?.error||b?.message||e.message;}catch{return e.message;}}return e instanceof Error?e.message:String(e||'');}

export function GoalPlanner({userId,onCreated,onCancel}:Props){
 const [title,setTitle]=useState(''); const [why,setWhy]=useState(''); const [armadillo,setArmadillo]=useState<ArmadilloResult|null>(null); const [questions,setQuestions]=useState<Question[]>([]); const [plan,setPlan]=useState<Plan|null>(null); const [goalId,setGoalId]=useState<string|null>(null); const [busy,setBusy]=useState(false); const [saving,setSaving]=useState(false); const [error,setError]=useState('');
 const saveDraft=async()=>{if(goalId)return goalId;const {data,error:e}=await supabase.from('goals').insert({user_id:userId,title:title.trim(),outcome:title.trim(),why_it_matters:why.trim()||null,status:'draft',weekly_commitment_target:0,start_date:null,deadline:null,duration:null}).select('id').single();if(e||!data)throw e||new Error('Could not start this goal.');setGoalId(data.id);return data.id;};
 const start=async()=>{if(!title.trim()||busy)return;setBusy(true);setError('');try{const safe=await checkContentSafety([title.trim(),why.trim()].filter(Boolean).join('\n'));if(safe.status!=='safe')throw new Error(safe.message||'Please reword the text and try again.');const id=await saveDraft();const a=analyseGoalForEvidence({title:title.trim(),outcome:title.trim(),why_it_matters:why.trim()||null});setArmadillo(a);const {data,error:e}=await supabase.functions.invoke('vow-goal-ai',{body:{mode:'goal-clarify',goal:{id,title:title.trim(),outcome:title.trim(),why_it_matters:why.trim()||null},armadillo:a,answers:[],references:[],message:'Create the smallest set of domain-specific discovery questions needed to personalise this exact goal. Do not ask the user to choose weeks, days or a time of day.'}});if(e||!data?.structured)throw new Error(await fnError(e)||data?.error||'VOW could not personalise this goal.');const qs=Array.isArray(data.structured.questions)?data.structured.questions.slice(0,3).map((q:string)=>({question:q,answer:''})):[];if(qs.length<2)throw new Error('VOW did not get enough goal-specific context.');setQuestions(qs);await supabase.from('goal_clarification_answers').delete().eq('goal_id',id).eq('user_id',userId);}catch(e){setError(e instanceof Error?e.message:'Could not start this goal.');}finally{setBusy(false);}};
 const generate=async()=>{if(!armadillo||!goalId||busy)return;setBusy(true);setError('');try{const clean=questions.map(q=>({question:q.question,answer:q.answer.trim()}));const {error:de}=await supabase.from('goal_clarification_answers').delete().eq('goal_id',goalId).eq('user_id',userId);if(de)throw de;const {error:ie}=await supabase.from('goal_clarification_answers').insert(clean.map((q,i)=>({goal_id:goalId,user_id:userId,question:q.question,answer:q.answer||null,question_order:i})));if(ie)throw ie;const {data,error:e}=await supabase.functions.invoke('vow-goal-ai',{body:{mode:'goal-plan',goal:{id:goalId,title:title.trim(),outcome:title.trim(),why_it_matters:why.trim()||null},armadillo,answers:clean,references:[],message:'Build the complete personalised plan for this exact goal. VOW, not the user, decides the planning horizon, cadence and calendar needs. Do not impose a weekly programme when the goal is one-time. Return ordered execution steps that reflect the domain and answers.'}});if(e||!data?.structured)throw new Error(await fnError(e)||data?.error||'VOW could not build the personalised plan.');const p=data.structured as Plan;if(!p.session_templates?.length)throw new Error('VOW returned no concrete execution steps.');setPlan(p);}catch(e){setError(e instanceof Error?e.message:'Could not build the plan.');}finally{setBusy(false);}};
 const create=async()=>{if(!plan||!goalId||saving)return;setSaving(true);setError('');try{const templates=[...plan.session_templates].sort((a,b)=>a.sequence-b.sequence);const oneTime=plan.planning_mode==='one_time';const start=nextDate(1);const scheduled=oneTime?[{template:{sequence:1,task:plan.outcome,purpose:plan.summary,target_metric:plan.success_metric,duration_minutes:templates.reduce((n,t)=>n+Math.max(5,Number(t.duration_minutes)||30),0),preferred_time:'09:00'},date:start}]:templates.map((template,index)=>({template,date:nextDate(index+1)}));const milestones=plan.milestones.map((m,index)=>({goal_id:goalId,title:m.title,description:m.description,sort_order:m.order??index,deadline:dateOnly(nextDate(oneTime?1:index+1)),status:index===0?'in_progress':'pending'}));const {data:ms,error:me}=await supabase.from('milestones').insert(milestones).select('id,sort_order');if(me)throw me;const milestoneFor=(i:number)=>(ms||[])[Math.min((ms||[]).length-1,Math.max(0,i))]?.id||null;const rows=scheduled.map(({template,date},index)=>({goal_id:goalId,milestone_id:milestoneFor(index),user_id:userId,title:template.task,scheduled_at:date.toISOString(),duration_minutes:Math.max(5,Math.min(240,Number(template.duration_minutes)||30)),status:'scheduled',moved_count:0,notes:[template.purpose,template.target_metric?`Target: ${template.target_metric}`:null].filter(Boolean).join('\n')||null}));const {error:se}=await supabase.from('sessions').insert(rows);if(se)throw se;const horizon=plan.planning_mode==='event'?'goal':'system';const {error:ge}=await supabase.from('goals').update({title:title.trim(),outcome:plan.outcome||title.trim(),why_it_matters:why.trim()||null,status:'active',armadillo,armadillo_analyzed_at:new Date().toISOString(),plan_json:plan,plan_version:1,plan_generated_at:new Date().toISOString(),planning_mode:plan.planning_mode,horizon_source:horizon,planning_horizon_weeks:null,planning_timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,start_date:dateOnly(start),deadline:dateOnly(oneTime?start:nextDate(Math.max(1,templates.length))),weekly_commitment_target:oneTime?0:scheduled.length}).eq('id',goalId).eq('user_id',userId);if(ge)throw ge;try{await supabase.functions.invoke('google-calendar-sync-goal',{body:{goalId}});}catch{}onCreated();}catch(e){setError(e instanceof Error?e.message:'Failed to create this goal.');}finally{setSaving(false);}};
 const field=(label:string,value:string,setter:(x:string)=>void,placeholder:string,multiline=false)=>h('label',{className:'block'},h('span',{className:'vow-label block mb-2'},label),multiline?h('textarea',{value,onChange:(e:any)=>setter(e.target.value),placeholder,className:'w-full min-h-24 border border-vow-border bg-transparent p-3 text-sm outline-none'}):h('input',{value,onChange:(e:any)=>setter(e.target.value),placeholder,className:'w-full min-h-12 border border-vow-border bg-transparent px-3 text-sm outline-none'}));
 if(plan)return h('div',{className:'max-w-4xl space-y-8'},h('button',{onClick:()=>setPlan(null),className:'text-sm text-vow-muted'},'← Back to questions'),h('div',null,h('p',{className:'vow-label mb-2'},plan.planning_mode.replace('_',' ')),h('h1',{className:'vow-heading text-2xl text-vow-ink'},plan.outcome),h('p',{className:'text-sm text-vow-muted mt-3'},plan.horizon_label)),h('section',{className:'border border-vow-border p-5'},h('p',{className:'vow-label mb-3'},'Execution'),h('div',{className:'space-y-5'},plan.session_templates.map((s,i)=>h('div',{key:`${s.sequence}-${i}`,className:'border-b border-vow-border pb-5 last:border-0 last:pb-0'},h('p',{className:'text-xs text-vow-muted mb-1'},`Step ${i+1}`),h('p',{className:'text-base font-medium text-vow-ink'},s.task),h('p',{className:'text-sm text-vow-muted mt-2'},s.purpose),h('p',{className:'text-xs text-vow-muted mt-2'},s.target_metric))))),h('section',{className:'border border-vow-border p-5'},h('p',{className:'vow-label mb-2'},'Timing'),h('p',{className:'text-sm text-vow-muted leading-relaxed'},plan.horizon_label)),error&&h('p',{className:'text-sm text-vow-ink border-l-2 border-vow-ink pl-3'},error),h('button',{onClick:create,disabled:saving,className:'min-h-12 px-5 border border-vow-ink text-sm font-medium'},saving?'Creating…':'Make this my VOW'));
 return h('div',{className:'max-w-2xl space-y-8'},onCancel&&h('button',{onClick:onCancel,className:'text-sm text-vow-muted'},'← Cancel'),h('div',null,h('p',{className:'vow-label mb-2'},'Make your VOW'),h('h1',{className:'vow-heading text-3xl text-vow-ink'},'Tell VOW what you want to accomplish.'),h('p',{className:'text-sm text-vow-muted mt-3 leading-relaxed'},'You do not need to choose weeks, days or a time. VOW determines the planning shape from the goal itself.')),field('Goal',title,setTitle,'e.g. make ravioli'),field('Why it matters',why,setWhy,'Optional context that could change the plan',true),!questions.length&&h('button',{onClick:start,disabled:busy||!title.trim(),className:'min-h-12 px-5 border border-vow-ink text-sm font-medium'},busy?'Understanding…':'Continue'),questions.length>0&&h('div',{className:'space-y-6'},h('div',{className:'border-l-2 border-vow-ink pl-4'},h('p',{className:'text-sm text-vow-ink'},`VOW identified ${armadillo?.category||'your domain'} → ${armadillo?.goal_type||'your goal type'}.`)),questions.map((q,i)=>field(`Question ${i+1}`,q.answer,(v)=>setQuestions(xs=>xs.map((x,j)=>j===i?{...x,answer:v}:x)),q.question)),error&&h('p',{className:'text-sm text-vow-ink border-l-2 border-vow-ink pl-3'},error),h('button',{onClick:generate,disabled:busy||questions.some(q=>!q.answer.trim()),className:'min-h-12 px-5 border border-vow-ink text-sm font-medium'},busy?'Building…':'Build my plan')));
}
