import { useState } from 'react';
import { supabase } from '@/lib/supabase';
import { addDays, toDateString } from '@/lib/dates';
import { syncUpcomingSessionNotifications } from '@/lib/notifications';
import type { Session } from '@/types/database';
import { PageHeader } from './AppShell';

type PlanItem={week:number;day:string;task:string;purpose:string;target_metric:string;duration_minutes:number;preferred_time:string;scheduled_at?:string};
type Plan={outcome:string;success_metric:string;baseline:string;assumptions:string[];milestones:Array<{title:string;description:string;week:number}>;schedule:PlanItem[];progression:string;checkpoints:string[];risks:string[];fallback_rules:string[];summary:string;duration_weeks:number;weekly_commitment_target:number;available_days:string[]};
const DAYS=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
function nextMonday(){const d=new Date();const day=d.getDay();d.setHours(0,0,0,0);d.setDate(d.getDate()+(day===0?1:8-day));return d;}
function deadlineFor(start:Date,weeks:number){return toDateString(addDays(start,weeks*7-1));}
function durationLabel(w:number){return w===1?'1 week':`${w} weeks`;}

export function GoalPlanner({userId,onCreated,onCancel}:{userId:string;onCreated:()=>void;onCancel:()=>void}){
 const [rawInput,setRawInput]=useState(''); const [why,setWhy]=useState(''); const [durationWeeks,setDurationWeeks]=useState(8); const [availableDays,setAvailableDays]=useState<string[]>(['Monday','Wednesday','Saturday']); const [plan,setPlan]=useState<Plan|null>(null); const [draftGoalId,setDraftGoalId]=useState<string|null>(null); const [planning,setPlanning]=useState(false); const [saving,setSaving]=useState(false); const [error,setError]=useState('');
 function toggleDay(day:string){setAvailableDays(x=>x.includes(day)?x.filter(d=>d!==day):x.length<7?[...x,day]:x);}
 async function ensureDraft(){if(draftGoalId)return draftGoalId;const start=nextMonday();const {data,error:e}=await supabase.from('goals').insert({user_id:userId,title:rawInput.trim(),outcome:rawInput.trim(),why_it_matters:why.trim()||null,start_date:toDateString(start),deadline:deadlineFor(start,durationWeeks),duration:`${durationWeeks}w`,status:'draft',weekly_commitment_target:availableDays.length}).select('id').single();if(e||!data)throw e||new Error('Could not start this goal.');setDraftGoalId(data.id);return data.id;}
 async function buildPlan(){if(!rawInput.trim()||planning||availableDays.length===0)return;setPlanning(true);setError('');try{const goalId=await ensureDraft();const start=nextMonday();const {data,error:e}=await supabase.functions.invoke('vow-goal-ai',{body:{mode:'goal-plan',goal_id:goalId,goal:{id:goalId,title:rawInput.trim(),outcome:rawInput.trim(),why_it_matters:why.trim()||null,start_date:toDateString(start),deadline:deadlineFor(start,durationWeeks),duration_weeks:durationWeeks,weekly_commitment_target:availableDays.length},message:`Build the personalised VOW plan. The selected duration is exactly ${durationWeeks} weeks and must not be changed. Use only these days: ${availableDays.join(', ')}.`,available_days:availableDays}});if(e||!data?.structured)throw new Error(data?.error||e?.message||'VOW AI could not build the plan.');const next=data.structured as Plan;if(next.duration_weeks!==durationWeeks)throw new Error('VOW AI returned the wrong duration. Please try again.');const expected=durationWeeks*availableDays.length;if(!next.schedule?.length||next.schedule.length!==expected)throw new Error('VOW AI returned an incomplete schedule. Please try again.');setPlan(next);}catch(err){setError(err instanceof Error?err.message:'VOW AI is unavailable right now.');}finally{setPlanning(false);}}
 async function handleCreate(){if(!plan||!draftGoalId||saving)return;setSaving(true);setError('');try{const start=nextMonday();const {error:goalError}=await supabase.from('goals').update({title:rawInput.trim(),outcome:plan.outcome||rawInput.trim(),why_it_matters:why.trim()||null,start_date:toDateString(start),deadline:deadlineFor(start,durationWeeks),duration:`${durationWeeks}w`,status:'active',weekly_commitment_target:availableDays.length,plan_json:plan,plan_version:1,plan_generated_at:new Date().toISOString(),planning_horizon_weeks:durationWeeks,planning_timezone:Intl.DateTimeFormat().resolvedOptions().timeZone}).eq('id',draftGoalId);if(goalError)throw goalError;const {data:milestones,error:milestoneError}=await supabase.from('milestones').insert(plan.milestones.map((m,i)=>({goal_id:draftGoalId,title:m.title,description:m.description,sort_order:i,deadline:deadlineFor(start,Math.min(durationWeeks,Math.max(1,m.week))),status:i===0?'in_progress':'pending'}))).select('id,sort_order').order('sort_order');if(milestoneError)throw milestoneError;const rows=plan.schedule.map(item=>{const week=Math.max(1,Math.min(durationWeeks,item.week));const dayIndex=Math.max(0,DAYS.indexOf(item.day));const date=addDays(start,(week-1)*7+dayIndex);const match=/^(\d{1,2}):(\d{2})/.exec(item.preferred_time||'09:00');date.setHours(Math.min(23,Number(match?.[1]||9)),Number(match?.[2]||0),0,0);const mi=Math.min(Math.max(0,Math.floor(((week-1)/Math.max(1,durationWeeks))*Math.max(1,(milestones||[]).length))),Math.max(0,(milestones||[]).length-1));return {goal_id:draftGoalId,milestone_id:milestones?.[mi]?.id??null,user_id:userId,title:item.task,scheduled_at:date.toISOString(),duration_minutes:Math.max(5,Number(item.duration_minutes)||30),status:'scheduled',notes:[item.purpose,item.target_metric?`Target: ${item.target_metric}`:null].filter(Boolean).join('\n')||null};});const {data:sessions,error:sessionError}=await supabase.from('sessions').insert(rows).select('*');if(sessionError)throw sessionError;if(sessions)try{await syncUpcomingSessionNotifications(sessions as Session[]);}catch{}try{await supabase.functions.invoke('google-calendar-sync-goal',{body:{goalId:draftGoalId}});}catch{}onCreated();}catch(err){setError(err instanceof Error?err.message:'Failed to create goal.');}finally{setSaving(false);}}
 if(plan)return <div><button onClick={()=>setPlan(null)} className="text-sm text-vow-muted hover:text-vow-ink mb-6">← Adjust goal</button><PageHeader title="Your VOW plan" subtitle={`${durationLabel(durationWeeks)} · ${availableDays.length} sessions/week`} /><div className="max-w-3xl space-y-6"><section className="border border-vow-border p-5"><p className="vow-label mb-2">Outcome</p><p className="text-lg font-medium text-vow-ink">{plan.outcome}</p><p className="text-sm text-vow-muted mt-3">{plan.summary}</p></section><section className="border border-vow-border p-5"><p className="vow-label mb-2">Success metric</p><p className="text-sm text-vow-ink">{plan.success_metric}</p><p className="vow-label mt-5 mb-2">Baseline</p><p className="text-sm text-vow-muted">{plan.baseline}</p></section><section className="border border-vow-border p-5"><p className="vow-label mb-4">Schedule · {durationLabel(durationWeeks)}</p><div className="divide-y divide-vow-border">{plan.schedule.map((item,i)=><div key={`${item.week}-${item.day}-${i}`} className="py-3 flex gap-3"><span className="text-xs text-vow-muted w-12 shrink-0">W{item.week}</span><span className="text-xs text-vow-muted w-20 shrink-0">{item.day}</span><div><p className="text-sm text-vow-ink font-medium">{item.task}</p><p className="text-xs text-vow-muted mt-1">{item.duration_minutes} min · {item.target_metric}</p></div></div>)}</div></section><section className="border border-vow-border p-5"><p className="vow-label mb-4">Milestones & progression</p>{plan.milestones.map(m=><div key={`${m.week}-${m.title}`} className="mb-4"><p className="text-sm text-vow-ink font-medium">Week {m.week} · {m.title}</p><p className="text-xs text-vow-muted mt-1">{m.description}</p></div>)}<p className="text-sm text-vow-muted pt-4 border-t border-vow-border">{plan.progression}</p></section>{error&&<p className="text-sm text-vow-ink border-l-2 border-vow-ink pl-3">{error}</p>}<div className="flex gap-3"><button onClick={()=>setPlan(null)} className="vow-btn-ghost">Back</button><button onClick={handleCreate} disabled={saving} className="vow-btn-primary flex-1">{saving?'Locking in...':'Lock in VOW'}</button></div></div></div>;
 return <div><PageHeader title="New goal" subtitle="Tell VOW what you want to accomplish. It will build the work around your commitment."/><div className="max-w-xl space-y-6"><textarea value={rawInput} onChange={e=>setRawInput(e.target.value)} rows={4} className="vow-input resize-none" placeholder="e.g. Run a sub-60-minute 10K" autoFocus/><div><label className="vow-label block mb-2">Why does this matter?</label><textarea value={why} onChange={e=>setWhy(e.target.value)} rows={2} className="vow-input resize-none" placeholder="Give VOW the reason behind the commitment."/></div><div><div className="flex items-baseline justify-between mb-3"><label className="vow-label">Duration</label><span className="text-sm font-medium text-vow-ink">{durationLabel(durationWeeks)}</span></div><input type="range" min={1} max={52} value={durationWeeks} onChange={e=>setDurationWeeks(Number(e.target.value))} className="w-full"/><div className="flex justify-between text-[10px] text-vow-muted mt-1"><span>1 week</span><span>52 weeks</span></div></div><div><label className="vow-label block mb-3">Available days</label><div className="grid grid-cols-2 sm:grid-cols-4 gap-2">{DAYS.map(day=><button key={day} type="button" onClick={()=>toggleDay(day)} className={`border px-3 py-2 text-xs transition-colors ${availableDays.includes(day)?'border-vow-ink bg-vow-ink text-vow-bg':'border-vow-border text-vow-muted hover:text-vow-ink'}`}>{day}</button>)}</div></div>{error&&<p className="text-sm text-vow-ink border-l-2 border-vow-ink pl-3">{error}</p>}<div className="flex gap-3"><button onClick={onCancel} className="vow-btn-ghost">Cancel</button><button onClick={buildPlan} disabled={!rawInput.trim()||planning||availableDays.length===0} className="vow-btn-primary flex-1">{planning?'VOW is building your plan...':'Build my VOW plan'}</button></div></div></div>;
}