import { useState } from 'react';
import { supabase } from '@/lib/supabase';
import { useAuth } from '@/lib/auth';
import { PageHeader } from './AppShell';

export function SecurityCenterPage(){
 const {session}=useAuth(); const[message,setMessage]=useState(''); const[busy,setBusy]=useState(false);
 async function exportData(){if(!session||busy)return;setBusy(true);setMessage('Preparing your export…');try{const{data,error}=await supabase.functions.invoke('vow-account-export',{body:{}});if(error||!data?.exported)throw error||new Error('export');const blob=new Blob([JSON.stringify(data.exported,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`vow-data-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url);setMessage('Your VOW data export is ready.');}catch{setMessage('VOW could not complete the export. Please try again.');}finally{setBusy(false)}}
 async function requestDeletion(){if(!session||busy)return;setBusy(true);const{error}=await supabase.from('data_requests').insert({user_id:session.user.id,request_type:'delete',status:'requested'});setMessage(error?'VOW could not record the deletion request. Please try again.':'Deletion request recorded. A secure account-deletion workflow must complete this request; no account data is silently removed from this screen.');setBusy(false)}
 return <div className="min-w-0"><PageHeader title="Security & privacy" subtitle="Manage the information VOW stores and the safety controls around your account."/>{message&&<p className="text-sm text-vow-ink border-l-2 border-vow-ink pl-3 mb-6">{message}</p>}<div className="border border-vow-border divide-y divide-vow-border"><section className="p-5"><p className="text-sm text-vow-ink">Private content</p><p className="text-xs text-vow-muted mt-1 leading-relaxed">Your goals and journal entries are private. VOW safety systems may analyse submitted content to keep the service safe, while the owner moderation surface stores safety metadata rather than your goal or journal wording.</p></section><section className="p-5"><div className="flex items-start justify-between gap-5"><div><p className="text-sm text-vow-ink">Export my data</p><p className="text-xs text-vow-muted mt-1">Download the account data VOW can export for you.</p></div><button type="button" disabled={busy} onClick={exportData} className="vow-btn-soft shrink-0">{busy?'Working…':'Export data'}</button></div></section><section className="p-5"><div className="flex items-start justify-between gap-5"><div><p className="text-sm text-vow-ink">Delete my account</p><p className="text-xs text-vow-muted mt-1">Submit a deletion request without exposing or deleting account data from the client.</p></div><button type="button" disabled={busy} onClick={requestDeletion} className="vow-btn-soft shrink-0">Request deletion</button></div></section><section className="p-5"><p className="text-sm text-vow-ink">Safety review</p><p className="text-xs text-vow-muted mt-1 leading-relaxed">Safety restrictions should provide a clear status and review path while keeping private goal and journal text out of owner-facing moderation metadata.</p></section></div></div>;
}
