import { useState } from 'react';
import { supabase } from '@/lib/supabase';
import { useAuth } from '@/lib/auth';
import { PageHeader } from './AppShell';

export function SecurityCenterPage(){
 const {session}=useAuth(); const[message,setMessage]=useState(''); const[busy,setBusy]=useState(false); const[confirmDelete,setConfirmDelete]=useState(false); const[appealReason,setAppealReason]=useState('');
 async function exportData(){if(!session||busy)return;setBusy(true);setMessage('Preparing your export…');try{const{data,error}=await supabase.functions.invoke('vow-account-export',{body:{}});if(error||!data?.exported)throw error||new Error('export');const blob=new Blob([JSON.stringify(data.exported,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`vow-data-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url);setMessage('Your VOW data export is ready.');}catch{setMessage('VOW could not complete the export. Please try again.');}finally{setBusy(false)}}
 async function deleteAccount(){if(!session||busy)return;setConfirmDelete(false);setBusy(true);setMessage('Deleting your account…');try{const{data,error}=await supabase.functions.invoke('vow-account-delete',{body:{confirm:true}});if(error||!data?.deleted)throw error||new Error('delete');await supabase.auth.signOut();setMessage('Your VOW account has been deleted.');}catch{setMessage('VOW could not complete account deletion. No client-side partial deletion was performed.');}finally{setBusy(false)}}
 async function submitAppeal(){if(!session||busy||appealReason.trim().length<10)return;setBusy(true);const{error}=await supabase.from('moderation_appeals').insert({user_id:session.user.id,reason:appealReason.trim()});setMessage(error?'VOW could not submit your review request. Please try again.':'Review request submitted. Your private goal and journal wording is not exposed through this form.');if(!error)setAppealReason('');setBusy(false)}
 return <div className="min-w-0"><PageHeader title="Security & privacy" subtitle="Manage the information VOW stores and the safety controls around your account."/>{message&&<p className="text-sm text-vow-ink border-l-2 border-vow-ink pl-3 mb-6">{message}</p>}<div className="border border-vow-border divide-y divide-vow-border"><section className="p-5"><p className="text-sm text-vow-ink">Private content</p><p className="text-xs text-vow-muted mt-1 leading-relaxed">Your goals and journal entries are private. VOW safety systems may analyse submitted content to keep the service safe, while the owner moderation surface stores safety metadata rather than your goal or journal wording.</p></section><section className="p-5"><div className="flex items-start justify-between gap-5"><div><p className="text-sm text-vow-ink">Export my data</p><p className="text-xs text-vow-muted mt-1">Download the account data VOW can export for you.</p></div><button type="button" disabled={busy} onClick={exportData} className="vow-btn-soft shrink-0">{busy?'Working…':'Export data'}</button></div></section><section className="p-5"><div className="flex items-start justify-between gap-5"><div><p className="text-sm text-vow-ink">Delete my account</p><p className="text-xs text-vow-muted mt-1">Permanently remove your VOW account and associated account data.</p></div><button type="button" disabled={busy} onClick={()=>setConfirmDelete(true)} className="vow-btn-soft shrink-0">Delete account</button></div></section><section className="p-5"><p className="text-sm text-vow-ink">Request a safety review</p><p className="text-xs text-vow-muted mt-1 mb-3 leading-relaxed">If VOW restricted something incorrectly, submit a short explanation. Keep private goal or journal details out of this request.</p><textarea value={appealReason} onChange={e=>setAppealReason(e.target.value.slice(0,1000))} rows={4} className="vow-input w-full resize-none" placeholder="Explain why you think the restriction should be reviewed…"/><button type="button" disabled={busy||appealReason.trim().length<10} onClick={submitAppeal} className="vow-btn-soft mt-3">Submit review request</button></section></div>{confirmDelete&&<div className="fixed inset-0 z-50 bg-black/20 flex items-center justify-center p-4" role="dialog" aria-modal="true"><div className="bg-vow-bg border border-vow-border p-6 max-w-sm w-full"><h2 className="vow-heading text-lg text-vow-ink mb-2">Delete your VOW account?</h2><p className="text-sm text-vow-muted leading-relaxed mb-6">This is permanent. Your account and associated VOW data will be removed. This cannot be undone.</p><div className="flex gap-3"><button type="button" onClick={()=>setConfirmDelete(false)} className="vow-btn-ghost flex-1">Cancel</button><button type="button" onClick={deleteAccount} className="vow-btn-primary flex-1">Delete permanently</button></div></div></div>}</div>;
}
