import { useState } from 'react';
import { supabase } from '@/lib/supabase';
import { PageHeader } from './AppShell';

export function SupportPage({ onBack }: { onBack: () => void }) {
  const [message, setMessage] = useState(''); const [status, setStatus] = useState(''); const [busy, setBusy] = useState(false);
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!message.trim() || busy) return; setBusy(true); setStatus(''); const { data, error } = await supabase.functions.invoke('vow-support', { body: { message } }); if (error || !data?.persisted) setStatus('We could not save that right now. Please email support@vowglobal.online directly.'); else { setMessage(''); setStatus(data.accepted ? 'Your support request was accepted for delivery.' : 'Your request was saved, but email delivery is unavailable. Please email support@vowglobal.online directly.'); } setBusy(false); }
  return <div><button onClick={onBack} className="text-sm text-vow-muted hover:text-vow-ink mb-6">← Back to profile</button><PageHeader title="Support" subtitle="Tell us what happened and we’ll keep your request on record." /><form onSubmit={submit} className="max-w-xl border border-vow-border p-5"><label htmlFor="support-message" className="vow-label block mb-2">How can we help?</label><textarea id="support-message" value={message} onChange={(event) => setMessage(event.target.value)} rows={7} maxLength={10000} required className="vow-input resize-y" placeholder="Describe the issue or question…" /><button type="submit" disabled={busy || !message.trim()} className="vow-btn-primary w-full mt-4 disabled:opacity-50">{busy ? 'Sending…' : 'Send support request'}</button>{status && <p className="text-sm text-vow-ink mt-4" role="status">{status}</p>}<p className="text-xs text-vow-muted mt-5">You can also email <a className="underline" href="mailto:support@vowglobal.online">support@vowglobal.online</a>. Alternative: <a className="underline" href="mailto:vowglobalapp@gmail.com">vowglobalapp@gmail.com</a>.</p></form></div>;
}
