import { useEffect, useMemo, useState } from 'react';
import { PageHeader } from './AppShell';
import { supabase } from '@/lib/supabase';
import { useAuth } from '@/lib/auth';
import type { Goal, GoalPlanItem, RavenAwardRecord } from '@/types/database';

type Dependency = { id: string; goal_id: string; depends_on_goal_id: string };
type Experiment = { id: string; goalId: string; hypothesis: string; approach: string; status: 'active' | 'completed'; outcome?: string | null };
type Memory = { id: string; text: string };
const titleOf = (goal: Goal) => goal.title || goal.outcome || 'Goal';
const health = (goal: Goal, items: GoalPlanItem[]) => { const due = items.filter((item) => new Date(item.scheduled_at).getTime() <= Date.now() && item.status !== 'cancelled'); const done = due.filter((item) => item.status === 'completed').length; const overdue = due.filter((item) => item.status === 'scheduled' || item.status === 'moved').length; const pct = due.length ? Math.round(done / due.length * 100) : goal.status === 'completed' ? 100 : 0; return { pct, overdue, label: goal.status === 'completed' || pct >= 80 ? 'on track' : pct >= 50 ? 'at risk' : 'off track' }; };

export function VowIntelligencePage() {
  const { session } = useAuth();
  const [goals, setGoals] = useState<Goal[]>([]); const [items, setItems] = useState<GoalPlanItem[]>([]); const [awards, setAwards] = useState<RavenAwardRecord[]>([]); const [deps, setDeps] = useState<Dependency[]>([]); const [adjustments, setAdjustments] = useState<{ id: string; goal_id: string; proposed_change: string; status: string }[]>([]);
  const [experiments, setExperiments] = useState<Experiment[]>([]); const [memories, setMemories] = useState<Memory[]>([]); const [accountability, setAccountability] = useState(false); const [message, setMessage] = useState(''); const [online, setOnline] = useState(navigator.onLine);
  const [newMemory, setNewMemory] = useState(''); const [newHypothesis, setNewHypothesis] = useState(''); const [newApproach, setNewApproach] = useState(''); const [experimentGoal, setExperimentGoal] = useState(''); const [selectedDependency, setSelectedDependency] = useState(''); const [checkin, setCheckin] = useState('');

  async function load() {
    if (!session) return; const userId = session.user.id;
    const [g, p, a, d, pa, ex, mem, acc] = await Promise.all([
      supabase.from('goals').select('*').eq('user_id', userId).order('created_at', { ascending: false }), supabase.from('goal_plan_items').select('*').eq('user_id', userId).order('scheduled_at', { ascending: true }), supabase.from('raven_awards').select('*').eq('user_id', userId).order('earned_at', { ascending: false }).limit(12), supabase.from('goal_dependencies').select('id,goal_id,depends_on_goal_id').eq('user_id', userId), supabase.from('plan_adjustments').select('id,goal_id,proposed_change,status').eq('user_id', userId).order('created_at', { ascending: false }).limit(12), supabase.from('goal_experiments').select('id,goal_id,hypothesis,approach,status,outcome').eq('user_id', userId).order('created_at', { ascending: false }), supabase.from('vow_memory').select('id,memory').eq('user_id', userId).eq('active', true).order('created_at', { ascending: false }), supabase.from('accountability_settings').select('enabled').eq('user_id', userId).maybeSingle(),
    ]);
    if ([g, p, a, d, pa, ex, mem, acc].some((result) => result.error)) setMessage('Some intelligence signals could not be loaded.');
    setGoals((g.data || []) as Goal[]); setItems((p.data || []) as GoalPlanItem[]); setAwards((a.data || []) as RavenAwardRecord[]); setDeps((d.data || []) as Dependency[]); setAdjustments((pa.data || []) as typeof adjustments); setAccountability(Boolean(acc.data?.enabled));
    setExperiments((ex.data || []).map((row) => ({ id: row.id, goalId: row.goal_id, hypothesis: row.hypothesis, approach: row.approach, status: row.status === 'completed' ? 'completed' : 'active', outcome: row.outcome })));
    setMemories((mem.data || []).map((row) => ({ id: row.id, text: row.memory })));
  }
  useEffect(() => { load().catch(() => setMessage('VOW could not load intelligence right now.')); }, [session]);
  useEffect(() => { const on = () => setOnline(true); const off = () => setOnline(false); addEventListener('online', on); addEventListener('offline', off); return () => { removeEventListener('online', on); removeEventListener('offline', off); }; }, []);

  const rows = useMemo(() => goals.filter((goal) => ['active', 'locked', 'completed', 'abandoned'].includes(goal.status)).map((goal) => ({ goal, health: health(goal, items.filter((item) => item.goal_id === goal.id)) })), [goals, items]);
  const activeRows = rows.filter((row) => ['active', 'locked'].includes(row.goal.status));
  const momentum = useMemo(() => activeRows.map(({ goal, health: current }) => { const recent = items.filter((item) => item.goal_id === goal.id && new Date(item.scheduled_at).getTime() > Date.now() - 14 * 86400000 && new Date(item.scheduled_at).getTime() <= Date.now() && item.status !== 'cancelled'); const recentPct = recent.length ? Math.round(recent.filter((item) => item.status === 'completed').length / recent.length * 100) : current.pct; return { goal, health: current, score: Math.round((recentPct + current.pct) / 2), trend: recentPct > current.pct ? 'accelerating' : recentPct < current.pct ? 'slipping' : 'stable' }; }), [activeRows, items]);
  const conflicts = useMemo(() => { const result: { a: GoalPlanItem; b: GoalPlanItem }[] = []; const scheduled = items.filter((item) => item.status === 'scheduled' || item.status === 'moved').sort((a, b) => new Date(a.scheduled_at).getTime() - new Date(b.scheduled_at).getTime()); for (let i = 0; i < scheduled.length; i += 1) for (let j = i + 1; j < scheduled.length; j += 1) { if (scheduled[i].goal_id !== scheduled[j].goal_id && Math.abs(new Date(scheduled[j].scheduled_at).getTime() - new Date(scheduled[i].scheduled_at).getTime()) < 45 * 60000) result.push({ a: scheduled[i], b: scheduled[j] }); if (result.length >= 6) return result; } return result; }, [items]);
  const patterns = useMemo(() => { const completed = items.filter((item) => item.status === 'completed' && new Date(item.scheduled_at).getTime() > Date.now() - 60 * 86400000); const evening = completed.filter((item) => new Date(item.scheduled_at).getHours() >= 17).length; const morning = completed.filter((item) => new Date(item.scheduled_at).getHours() < 12).length; const best = evening > morning ? 'evenings' : morning > evening ? 'mornings' : 'mixed times'; return [{ title: 'Strongest working window', description: `Completed work currently clusters around ${best}.`, confidence: completed.length ? Math.round(Math.max(evening, morning) / completed.length * 100) : 0 }, { title: 'Execution load', description: `${completed.length} completed plan items were recorded in the last 60 days.`, confidence: Math.min(100, completed.length * 5) }, { title: 'Disruption signal', description: adjustments.length ? `${adjustments.length} recent plan adjustments suggest flexibility is useful.` : 'No recent plan adjustments detected.', confidence: Math.min(100, adjustments.length * 15) }]; }, [items, adjustments]);
  const completedEvidence = items.filter((item) => item.status === 'completed').slice(-8).reverse(); const recoveryCandidates = activeRows.filter((row) => row.health.overdue >= 2); const archaeology = goals.filter((goal) => goal.status === 'completed' || goal.status === 'abandoned').slice(0, 8);
  const scorecard = useMemo(() => { const done = items.filter((item) => item.status === 'completed').length; const total = items.filter((item) => item.status !== 'cancelled').length; const moved = items.filter((item) => item.status === 'moved').length; const avg = activeRows.length ? Math.round(activeRows.reduce((sum, row) => sum + row.health.pct, 0) / activeRows.length) : 0; return { execution: total ? Math.round(done / total * 100) : 0, health: avg, adaptation: Math.min(100, moved ? 50 + moved * 5 : 100), awards: Math.min(100, awards.length * 10) }; }, [items, activeRows, awards]);

  async function toggleAccountability() { if (!session || !online) return; const next = !accountability; const { error } = await supabase.from('accountability_settings').upsert({ user_id: session.user.id, enabled: next, updated_at: new Date().toISOString() }); if (error) setMessage('Could not update accountability settings.'); else setAccountability(next); }
  async function addMemory() { if (!session || !online || !newMemory.trim()) return; const { data, error } = await supabase.from('vow_memory').insert({ user_id: session.user.id, memory_key: crypto.randomUUID(), memory: newMemory.trim(), source: 'user' }).select('id,memory').single(); if (error || !data) setMessage('Could not save that memory.'); else { setMemories((current) => [{ id: data.id, text: data.memory }, ...current]); setNewMemory(''); } }
  async function removeMemory(id: string) { if (!session || !online) return; const { error } = await supabase.from('vow_memory').update({ active: false, updated_at: new Date().toISOString() }).eq('id', id).eq('user_id', session.user.id); if (error) setMessage('Could not remove that memory.'); else setMemories((current) => current.filter((memory) => memory.id !== id)); }
  async function addExperiment() { if (!session || !online || !experimentGoal || !newHypothesis.trim() || !newApproach.trim()) return; const { data, error } = await supabase.from('goal_experiments').insert({ user_id: session.user.id, goal_id: experimentGoal, hypothesis: newHypothesis.trim(), approach: newApproach.trim(), status: 'active' }).select('id,goal_id,hypothesis,approach,status,outcome').single(); if (error || !data) setMessage('Could not start that experiment.'); else { setExperiments((current) => [{ id: data.id, goalId: data.goal_id, hypothesis: data.hypothesis, approach: data.approach, status: 'active', outcome: data.outcome }, ...current]); setNewHypothesis(''); setNewApproach(''); } }
  async function completeExperiment(id: string) { if (!session || !online) return; const { error } = await supabase.from('goal_experiments').update({ status: 'completed', outcome: 'Completed and ready for reflection.', completed_at: new Date().toISOString() }).eq('id', id).eq('user_id', session.user.id); if (error) setMessage('Could not complete that experiment.'); else setExperiments((current) => current.map((experiment) => experiment.id === id ? { ...experiment, status: 'completed', outcome: 'Completed and ready for reflection.' } : experiment)); }
  async function addDependency() { if (!session || !online || !experimentGoal || !selectedDependency || experimentGoal === selectedDependency) return; const { error } = await supabase.from('goal_dependencies').insert({ user_id: session.user.id, goal_id: experimentGoal, depends_on_goal_id: selectedDependency }); if (error) setMessage('Could not add that dependency.'); else { setSelectedDependency(''); await load(); } }
  async function recover(goal: Goal) { if (!session || !online) return; const overdue = items.filter((item) => item.goal_id === goal.id && item.status === 'scheduled' && new Date(item.scheduled_at) < new Date()).slice(0, 3); if (!overdue.length) { setMessage('No overdue work needs recovery.'); return; } const base = new Date(); base.setDate(base.getDate() + 1); base.setHours(18, 0, 0, 0); for (let n = 0; n < overdue.length; n += 1) { const at = new Date(base); at.setDate(base.getDate() + n); await supabase.from('goal_plan_items').update({ scheduled_at: at.toISOString(), status: 'moved' }).eq('id', overdue[n].id).eq('user_id', session.user.id); } await supabase.from('plan_adjustments').insert({ user_id: session.user.id, goal_id: goal.id, reason: 'Recovery mode after disruption', proposed_change: `Rebuilt ${overdue.length} overdue task(s) into a short recovery sequence.`, status: 'applied', applied_at: new Date().toISOString() }); setMessage(`Recovery sequence created for ${titleOf(goal)}.`); await load(); }

  return <div className="min-w-0"><PageHeader title="VOW Intelligence" subtitle="Turn execution history into better decisions, not just more tasks." />{!online && <div className="border border-vow-border p-4 mb-6 text-sm text-vow-muted">You are offline. Existing intelligence remains visible; plan changes require a connection.</div>}{message && <p className="text-sm text-vow-ink border-l-2 border-vow-ink pl-3 mb-6">{message}</p>}
    <section className="border border-vow-border p-5 mb-6"><p className="vow-label">Goal momentum</p><h2 className="vow-heading text-xl text-vow-ink mt-1">Which goals are moving?</h2><div className="mt-5 space-y-4">{momentum.length ? momentum.map((item) => <div key={item.goal.id} className="border-t border-vow-border pt-4 flex items-center justify-between gap-4"><div><p className="text-sm text-vow-ink">{titleOf(item.goal)}</p><p className="text-xs text-vow-muted mt-1">{item.trend} · {item.score}% momentum · {item.health.label}</p></div><span className="text-xs text-vow-muted">{item.health.overdue} overdue</span></div>) : <p className="text-sm text-vow-muted">Create an active goal to build momentum data.</p>}</div></section>
    <section className="border border-vow-border p-5 mb-6"><p className="vow-label">Adaptive difficulty</p><h2 className="vow-heading text-xl text-vow-ink mt-1">Let performance calibrate the next step</h2><div className="mt-5 space-y-3">{momentum.map((item) => <div key={item.goal.id} className="border-t border-vow-border pt-3 text-sm text-vow-muted">{item.health.pct >= 85 ? `Strong execution on ${titleOf(item.goal)}. VOW can increase challenge gradually.` : item.health.pct < 50 ? `${titleOf(item.goal)} needs a smaller next step before adding load.` : `${titleOf(item.goal)} is in a workable range. Keep difficulty steady and observe the next cycle.`}</div>)}</div></section>
    <section className="border border-vow-border p-5 mb-6"><p className="vow-label">Goal conflicts</p><h2 className="vow-heading text-xl text-vow-ink mt-1">Protect the schedule from collisions</h2>{conflicts.length ? <div className="mt-5 space-y-3">{conflicts.map((conflict, index) => { const first = goals.find((goal) => goal.id === conflict.a.goal_id); const second = goals.find((goal) => goal.id === conflict.b.goal_id); return <div key={index} className="border-t border-vow-border pt-3 text-sm"><p className="text-vow-ink">{first ? titleOf(first) : 'Goal'} ↔ {second ? titleOf(second) : 'Goal'}</p><p className="text-xs text-vow-muted mt-1">Two scheduled tasks fall within 45 minutes of each other.</p></div>; })}</div> : <p className="text-sm text-vow-muted mt-5">No cross-goal schedule collisions detected.</p>}</section>
    <section className="border border-vow-border p-5 mb-6"><p className="vow-label">Evidence</p><h2 className="vow-heading text-xl text-vow-ink mt-1">Show the work behind progress</h2><div className="mt-5 space-y-2">{completedEvidence.map((item) => <div key={item.id} className="border-t border-vow-border pt-3"><p className="text-sm text-vow-ink">{item.task}</p><p className="text-xs text-vow-muted mt-1">Completed · {new Date(item.scheduled_at).toLocaleDateString('en-GB')}</p></div>)}{!completedEvidence.length && <p className="text-sm text-vow-muted">Complete plan items to build an evidence trail.</p>}</div></section>
    <section className="border border-vow-border p-5 mb-6"><p className="vow-label">Goal experiments</p><h2 className="vow-heading text-xl text-vow-ink mt-1">Test what actually works</h2><div className="grid gap-2 mt-5"><select value={experimentGoal} onChange={(event) => setExperimentGoal(event.target.value)} className="vow-input"><option value="">Goal…</option>{activeRows.map((row) => <option key={row.goal.id} value={row.goal.id}>{titleOf(row.goal)}</option>)}</select><input value={newHypothesis} onChange={(event) => setNewHypothesis(event.target.value)} className="vow-input" placeholder="Hypothesis"/><input value={newApproach} onChange={(event) => setNewApproach(event.target.value)} className="vow-input" placeholder="Approach"/><button type="button" disabled={!online} onClick={addExperiment} className="vow-btn-primary">Start experiment</button></div><div className="mt-5 space-y-3">{experiments.map((experiment) => <div key={experiment.id} className="border-t border-vow-border pt-3"><p className="text-sm text-vow-ink">{experiment.hypothesis}</p><p className="text-xs text-vow-muted mt-1">{experiment.approach} · {experiment.status}</p>{experiment.status === 'active' && <button type="button" disabled={!online} onClick={() => completeExperiment(experiment.id)} className="text-xs text-vow-muted mt-2">Mark complete →</button>}</div>)}</div></section>
    <section className="border border-vow-border p-5 mb-6"><p className="vow-label">Operating patterns</p><h2 className="vow-heading text-xl text-vow-ink mt-1">How you tend to work</h2><div className="mt-5 space-y-3">{patterns.map((pattern) => <div key={pattern.title} className="border-t border-vow-border pt-3"><p className="text-sm text-vow-ink">{pattern.title}</p><p className="text-xs text-vow-muted mt-1">{pattern.description} · {pattern.confidence}% signal</p></div>)}</div></section>
    <section className="border border-vow-border p-5 mb-6"><p className="vow-label">Recovery mode</p><h2 className="vow-heading text-xl text-vow-ink mt-1">Recover without rebuilding everything</h2><div className="mt-5 space-y-3">{recoveryCandidates.length ? recoveryCandidates.map((row) => <div key={row.goal.id} className="border-t border-vow-border pt-3 flex items-center justify-between gap-3"><div><p className="text-sm text-vow-ink">{titleOf(row.goal)}</p><p className="text-xs text-vow-muted mt-1">{row.health.overdue} overdue tasks</p></div><button type="button" disabled={!online} onClick={() => recover(row.goal)} className="vow-btn-soft">Recover plan</button></div>) : <p className="text-sm text-vow-muted">No goals currently need recovery.</p>}</div></section>
    <section className="border border-vow-border p-5 mb-6"><p className="vow-label">Goal templates</p><h2 className="vow-heading text-xl text-vow-ink mt-1">Reusable planning patterns</h2><div className="grid sm:grid-cols-2 gap-3 mt-5">{['Skill building', 'Fitness consistency', 'Project delivery', 'Exam preparation'].map((template) => <div key={template} className="border border-vow-border p-4"><p className="text-sm text-vow-ink">{template}</p><p className="text-xs text-vow-muted mt-1">Use a clear outcome, weekly commitment, evidence and review cycle.</p></div>)}</div></section>
    <section className="border border-vow-border p-5 mb-6"><p className="vow-label">Accountability</p><h2 className="vow-heading text-xl text-vow-ink mt-1">Choose stronger check-ins</h2><p className="text-sm text-vow-muted mt-2">Optional accountability keeps commitments visible without exposing private journal content.</p><button type="button" disabled={!online} onClick={toggleAccountability} className="vow-btn-soft mt-5">{accountability ? 'Accountability on' : 'Turn accountability on'}</button></section>
    <section className="border border-vow-border p-5 mb-6"><p className="vow-label">Goal archaeology</p><h2 className="vow-heading text-xl text-vow-ink mt-1">Learn from old goals</h2><div className="mt-5 space-y-3">{archaeology.length ? archaeology.map((goal) => <div key={goal.id} className="border-t border-vow-border pt-3"><p className="text-sm text-vow-ink">{titleOf(goal)}</p><p className="text-xs text-vow-muted mt-1">{goal.status === 'completed' ? 'Completed — keep the conditions that worked.' : 'Abandoned — identify the constraint before repeating the pattern.'}</p></div>) : <p className="text-sm text-vow-muted">Completed and abandoned goals will become your history.</p>}</div></section>
    <section className="border border-vow-border p-5 mb-6"><p className="vow-label">VOW scorecard</p><h2 className="vow-heading text-xl text-vow-ink mt-1">A long-view execution signal</h2><div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mt-5">{Object.entries(scorecard).map(([key, value]) => <div key={key} className="border-t border-vow-border pt-3"><p className="text-xs text-vow-muted capitalize">{key}</p><p className="text-xl text-vow-ink mt-1">{value}</p></div>)}</div></section>
    <section className="border border-vow-border p-5 mb-6"><p className="vow-label">AI check-ins</p><h2 className="vow-heading text-xl text-vow-ink mt-1">Ask the right question at the right time</h2><button type="button" onClick={() => { const item = momentum[0]; setCheckin(item ? `${titleOf(item.goal)} is ${item.trend} at ${item.score}% momentum. What is the smallest useful action you can complete next?` : 'Create an active goal and VOW will generate a contextual check-in.'); }} className="vow-btn-soft mt-5">Generate check-in</button>{checkin && <p className="text-sm text-vow-ink mt-4 border-t border-vow-border pt-4">{checkin}</p>}</section>
    <section className="border border-vow-border p-5 mb-6"><p className="vow-label">VOW memory</p><h2 className="vow-heading text-xl text-vow-ink mt-1">Keep useful lessons close</h2><div className="flex gap-2 mt-5"><input value={newMemory} onChange={(event) => setNewMemory(event.target.value)} className="vow-input flex-1" placeholder="A preference or lesson to remember"/><button type="button" disabled={!online} onClick={addMemory} className="vow-btn-primary">Save</button></div><div className="mt-5 space-y-2">{memories.map((memory) => <div key={memory.id} className="border-t border-vow-border pt-3 flex justify-between gap-3"><p className="text-sm text-vow-ink">{memory.text}</p><button type="button" disabled={!online} onClick={() => removeMemory(memory.id)} className="text-xs text-vow-muted">Remove</button></div>)}</div></section>
    <section className="border border-vow-border p-5"><p className="vow-label">Goal network</p><h2 className="vow-heading text-xl text-vow-ink mt-1">Dependencies</h2><div className="flex flex-col sm:flex-row gap-2 mt-5"><select value={experimentGoal} onChange={(event) => setExperimentGoal(event.target.value)} className="vow-input"><option value="">Goal…</option>{goals.map((goal) => <option key={goal.id} value={goal.id}>{titleOf(goal)}</option>)}</select><select value={selectedDependency} onChange={(event) => setSelectedDependency(event.target.value)} className="vow-input"><option value="">Depends on…</option>{goals.map((goal) => <option key={goal.id} value={goal.id}>{titleOf(goal)}</option>)}</select><button type="button" disabled={!online} onClick={addDependency} className="vow-btn-primary">Add</button></div><div className="mt-5 space-y-2">{deps.map((dependency) => { const first = goals.find((goal) => goal.id === dependency.goal_id); const second = goals.find((goal) => goal.id === dependency.depends_on_goal_id); return <div key={dependency.id} className="flex justify-between border-t border-vow-border pt-3 text-sm"><span>{first ? titleOf(first) : 'Goal'} ← {second ? titleOf(second) : 'Goal'}</span></div>; })}</div></section>
  </div>;
}
