import { useEffect, useMemo, useState } from 'react';
import { PageHeader } from './AppShell';
import { supabase } from '@/lib/supabase';
import { useAuth } from '@/lib/auth';
import type { Goal, GoalPlanItem, Review, RavenAwardRecord } from '@/types/database';

type Dependency = { id: string; goal_id: string; depends_on_goal_id: string };
function health(goal: Goal, items: GoalPlanItem[]) { const due = items.filter((i) => new Date(i.scheduled_at).getTime() <= Date.now() && i.status !== 'cancelled'); const done = due.filter((i) => i.status === 'completed').length; const overdue = due.filter((i) => i.status === 'scheduled' || i.status === 'moved').length; const pct = due.length ? Math.round(done / due.length * 100) : goal.status === 'completed' ? 100 : 0; return { pct, overdue, label: goal.status === 'completed' || pct >= 80 ? 'on track' : pct >= 50 ? 'at risk' : 'off track' }; }
export function VowIntelligencePage() {
 const { session } = useAuth(); const [goals,setGoals]=useState<Goal[]>([]); const [items,setItems]=useState<GoalPlanItem[]>([]); const [reviews,setReviews]=useState<Review[]>([]); const [awards,setAwards]=useState<RavenAwardRecord[]>([]); const [deps,setDeps]=useState<Dependency[]>([]); const [selected,setSelected]=useState(''); const [depends,setDepends]=useState(''); const [message,setMessage]=useState(''); const [online,setOnline]=useState(navigator.onLine);
 async function load(){ if(!session)return; const [g,p,r,a,d]=await Promise.all([supabase.from('goals').select('*').eq('user_id',session.user.id).order('created_at',{ascending:false}),supabase.from('goal_plan_items').select('*').eq('user_id',session.user.id).order('scheduled_at',{ascending:true}),supabase.from('reviews').select('*').eq('user_id',session.user.id).order('week_start',{ascending:false}).limit(4),supabase.from('raven_awards').select('*').eq('user_id',session.user.id).order('earned_at',{ascending:false}).limit(8),supabase.from('goal_dependencies').select('id,goal_id,depends_on_goal_id').eq('user_id',session.user.id)]); if(g.error||p.error||r.error||a.error||d.error)setMessage('Some insights could not be loaded.'); setGoals((g.data||[]) as Goal[]); setItems((p.data||[]) as GoalPlanItem[]); setReviews((r.data||[]) as Review[]); setAwards((a.data||[]) as RavenAwardRecord[]); setDeps((d.data||[]) as Dependency[]); }
 useEffect(()=>{load().catch(()=>setMessage('VOW could not load insights right now.'));},[session]); useEffect(()=>{const on=()=>setOnline(true),off=()=>setOnline(false);addEventListener('online',on);addEventListener('offline',off);return()=>{removeEventListener('online',on);removeEventListener('offline',off)}},[]);
 const rows=useMemo(()=>goals.filter(g=>['active','locked','completed'].includes(g.status)).map(g=>({g,h:health(g,items.filter(i=>i.goal_id===g.id))})),[goals,items]); const week=useMemo(()=>{const end=Date.now(),start=end-7*86400000;return items.filter(i=>{const t=new Date(i.scheduled_at).getTime();return t>=start&&t<=end})},[items]); const review=reviews[0];
 async function adjust(g:Goal){if(!session||!online)return;const overdue=items.filter(i=>i.goal_id===g.id&&i.status==='scheduled'&&new Date(i.scheduled_at).getTime()<Date.now()).slice(0,3);if(!overdue.length){setMessage('No overdue tasks need adjustment.');return}const base=new Date();base.setDate(base.getDate()+1);base.setHours(18,0,0,0);for(let n=0;n<overdue.length;n++){const at=new Date(base);at.setDate(base.getDate()+n);await supabase.from('goal_plan_items').update({scheduled_at:at.toISOString(),status:'moved'}).eq('id',overdue[n].id).eq('user_id',session.user.id)}await supabase.from('plan_adjustments').insert({user_id:session.user.id,goal_id:g.id,reason:'Overdue scheduled work',proposed_change:`Moved ${overdue.length} overdue task(s) forward.`,status:'applied',applied_at:new Date().toISOString()});setMessage(`Plan adjusted for ${g.title||g.outcome}.`);await load()}
 async function addDependency(){if(!session||!selected||!depends||selected===depends)return;const {error}=await supabase.from('goal_dependencies').insert({user_id:session.user.id,goal_id:selected,depends_on_goal_id:depends});if(error)setMessage('Could not add that dependency.');else{setDepends('');await load()}}
 async function removeDependency(id:string){if(!session)return;await supabase.from('goal_dependencies').delete().eq('id',id).eq('user_id',session.user.id);await load()}
 return <div className="min-w-0"><PageHeader title="VOW Intelligence" subtitle="Plan, do, review and adapt using the activity you actually complete." />{!online&&<div className="border border-vow-border p-4 mb-6 text-sm text-vow-muted">You are offline. Reconnect to sync and adjust plans.</div>}{message&&<p className="text-sm text-vow-ink border-l-2 border-vow-ink pl-3 mb-6">{message}</p>}
 <section className="border border-vow-border p-5 mb-6"><p className="vow-label">Goal health</p><h2 className="vow-heading text-xl text-vow-ink mt-1">Real progress, not guessed progress</h2><div className="space-y-4 mt-5">{rows.length?rows.map(({g,h})=><div key={g.id} className="border-t border-vow-border pt-4 flex items-center justify-between gap-3"><div><p className="text-sm text-vow-ink">{g.title||g.outcome}</p><p className="text-xs text-vow-muted mt-1">{h.label} · {h.pct}% · {h.overdue} overdue</p></div>{h.overdue>0&&<button type="button" disabled={!online} onClick={()=>adjust(g)} className="vow-btn-soft">Adjust plan</button>}</div>):<p className="text-sm text-vow-muted">Create a goal to start seeing health signals.</p>}</div></section>
 <section className="border border-vow-border p-5 mb-6"><p className="vow-label">Weekly review</p><h2 className="vow-heading text-xl text-vow-ink mt-1">{review?`Week of ${review.week_start}`:'This week'}</h2><div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mt-5">{[['Completion',review?`${review.completion_pct}%`:week.length?`${Math.round(week.filter(i=>i.status==='completed').length/week.length*100)}%`:'—'],['Completed',review?String(review.completed_count):String(week.filter(i=>i.status==='completed').length)],['Missed',review?String(review.missed_count):String(week.filter(i=>i.status==='skipped').length)],['Moved',review?String(review.moved_count):String(week.filter(i=>i.status==='moved').length)]].map(([k,v])=><div key={k} className="border-t border-vow-border pt-3"><p className="text-xs text-vow-muted">{k}</p><p className="text-xl text-vow-ink mt-1">{v}</p></div>)}</div>{review?.coaching_text&&<p className="text-sm text-vow-muted mt-5 border-t border-vow-border pt-5">{review.coaching_text}</p>}</section>
 <section className="border border-vow-border p-5 mb-6"><p className="vow-label">Goal network</p><h2 className="vow-heading text-xl text-vow-ink mt-1">Dependencies</h2><div className="flex flex-col sm:flex-row gap-2 mt-5"><select value={selected} onChange={e=>setSelected(e.target.value)} className="vow-input"><option value="">Goal…</option>{goals.map(g=><option key={g.id} value={g.id}>{g.title||g.outcome}</option>)}</select><select value={depends} onChange={e=>setDepends(e.target.value)} className="vow-input"><option value="">Depends on…</option>{goals.map(g=><option key={g.id} value={g.id}>{g.title||g.outcome}</option>)}</select><button type="button" onClick={addDependency} className="vow-btn-primary">Add</button></div><div className="mt-5 space-y-2">{deps.map(d=>{const a=goals.find(g=>g.id===d.goal_id),b=goals.find(g=>g.id===d.depends_on_goal_id);return <div key={d.id} className="flex justify-between border-t border-vow-border pt-3 text-sm"><span>{a?.title||a?.outcome||'Goal'} ← {b?.title||b?.outcome||'Goal'}</span><button type="button" onClick={()=>removeDependency(d.id)} className="text-xs text-vow-muted">Remove</button></div>})}</div></section>
 <section className="border border-vow-border p-5"><p className="vow-label">Milestones</p><h2 className="vow-heading text-xl text-vow-ink mt-1">Keep momentum visible</h2><div className="grid sm:grid-cols-2 gap-3 mt-5">{awards.length?awards.map(a=><div key={a.id} className="border border-vow-border p-4"><p className="text-sm text-vow-ink">{a.title}</p><p className="text-xs text-vow-muted mt-1">{a.description}</p></div>):<p className="text-sm text-vow-muted">Earned milestones will appear here.</p>}</div></section></div>;
}
