import { useEffect, useMemo, useState } from 'react';
import { PageHeader } from './AppShell';
import { supabase } from '@/lib/supabase';
import { useAuth } from '@/lib/auth';
import type { Goal, GoalPlanItem, Review, RavenAwardRecord, PlanAdjustment } from '@/types/database';

type Dependency = { id: string; goal_id: string; depends_on_goal_id: string };
type Experiment = { id: string; goalId: string; hypothesis: string; approach: string; status: 'active'|'completed'; outcome?: string; createdAt: string };
type Memory = { id: string; text: string; createdAt: string };
const key=(userId:string,suffix:string)=>`vow:intelligence:${userId}:${suffix}`;
const titleOf=(g:Goal)=>g.title||g.outcome||'Goal';
function health(goal:Goal,items:GoalPlanItem[]){const due=items.filter(i=>new Date(i.scheduled_at).getTime()<=Date.now()&&i.status!=='cancelled');const done=due.filter(i=>i.status==='completed').length;const overdue=due.filter(i=>i.status==='scheduled'||i.status==='moved').length;const pct=due.length?Math.round(done/due.length*100):goal.status==='completed'?100:0;return{pct,overdue,label:goal.status==='completed'||pct>=80?'on track':pct>=50?'at risk':'off track'};}
function loadLocal<T>(userId:string,suffix:string,fallback:T):T{try{const raw=localStorage.getItem(key(userId,suffix));return raw?JSON.parse(raw) as T:fallback}catch{return fallback}}
function saveLocal<T>(userId:string,suffix:string,value:T){localStorage.setItem(key(userId,suffix),JSON.stringify(value));}
export function VowIntelligencePage(){
 const {session}=useAuth();const [goals,setGoals]=useState<Goal[]>([]);const [items,setItems]=useState<GoalPlanItem[]>([]);const [reviews,setReviews]=useState<Review[]>([]);const [awards,setAwards]=useState<RavenAwardRecord[]>([]);const [deps,setDeps]=useState<Dependency[]>([]);const [adjustments,setAdjustments]=useState<PlanAdjustment[]>([]);const [experiments,setExperiments]=useState<Experiment[]>([]);const [memories,setMemories]=useState<Memory[]>([]);const [accountability,setAccountability]=useState(false);const [message,setMessage]=useState('');const [online,setOnline]=useState(navigator.onLine);const [newMemory,setNewMemory]=useState('');const [newHypothesis,setNewHypothesis]=useState('');const [newApproach,setNewApproach]=useState('');const [experimentGoal,setExperimentGoal]=useState('');const [selectedDependency,setSelectedDependency]=useState('');const [checkin,setCheckin]=useState('');
 async function load(){if(!session)return;const [g,p,r,a,d,pa]=await Promise.all([supabase.from('goals').select('*').eq('user_id',session.user.id).order('created_at',{ascending:false}),supabase.from('goal_plan_items').select('*').eq('user_id',session.user.id).order('scheduled_at',{ascending:true}),supabase.from('reviews').select('*').eq('user_id',session.user.id).order('week_start',{ascending:false}).limit(8),supabase.from('raven_awards').select('*').eq('user_id',session.user.id).order('earned_at',{ascending:false}).limit(12),supabase.from('goal_dependencies').select('id,goal_id,depends_on_goal_id').eq('user_id',session.user.id),supabase.from('plan_adjustments').select('*').eq('user_id',session.user.id).order('created_at',{ascending:false}).limit(12)]);if(g.error||p.error||r.error||a.error||d.error||pa.error)setMessage('Some intelligence signals could not be loaded.');setGoals((g.data||[])as Goal[]);setItems((p.data||[])as GoalPlanItem[]);setReviews((r.data||[])as Review[]);setAwards((a.data||[])as RavenAwardRecord[]);setDeps((d.data||[])as Dependency[]);setAdjustments((pa.data||[])as PlanAdjustment[])}
 useEffect(()=>{load().catch(()=>setMessage('VOW could not load intelligence right now.'));},[session]);useEffect(()=>{if(!session)return;setExperiments(loadLocal(session.user.id,'experiments',[]));setMemories(loadLocal(session.user.id,'memory',[]));setAccountability(loadLocal(session.user.id,'accountability',false));},[session]);useEffect(()=>{const on=()=>setOnline(true),off=()=>setOnline(false);addEventListener('online',on);addEventListener('offline',off);return()=>{removeEventListener('online',on);removeEventListener('offline',off)}},[]);
 const rows=useMemo(()=>goals.filter(g=>['active','locked','completed','abandoned'].includes(g.status)).map(g=>({g,h:health(g,items.filter(i=>i.goal_id===g.id))})),[goals,items]);const activeRows=rows.filter(x=>['active','locked'].includes(x.g.status));const completedEvidence=useMemo(()=>items.filter(i=>i.status==='completed').slice(-20).reverse(),[items]);
 const momentum=useMemo(()=>activeRows.map(({g,h})=>{const recent=items.filter(i=>i.goal_id===g.id&&new Date(i.scheduled_at).getTime()>Date.now()-14*86400000&&new Date(i.scheduled_at).getTime()<=Date.now()&&i.status!=='cancelled');const recentPct=recent.length?Math.round(recent.filter(i=>i.status==='completed').length/recent.length*100):h.pct;return{g,h,score:Math.round((recentPct+h.pct)/2),trend:recentPct>h.pct?'accelerating':recentPct<h.pct?'slipping':'stable'}}),[activeRows,items]);
 const conflicts=useMemo(()=>{const result:{a:GoalPlanItem;b:GoalPlanItem}[]=[];const scheduled=items.filter(i=>i.status==='scheduled'||i.status==='moved').sort((a,b)=>new Date(a.scheduled_at).getTime()-new Date(b.scheduled_at).getTime());for(let i=0;i<scheduled.length;i++)for(let j=i+1;j<scheduled.length;j++){if(scheduled[j].goal_id===scheduled[i].goal_id)continue;const gap=Math.abs(new Date(scheduled[j].scheduled_at).getTime()-new Date(scheduled[i].scheduled_at).getTime());if(gap<45*60000){result.push({a:scheduled[i],b:scheduled[j]});if(result.length>=6)return result;}}return result},[items]);
 const patterns=useMemo(()=>{const completed=items.filter(i=>i.status==='completed'&&new Date(i.scheduled_at).getTime()>Date.now()-60*86400000);const hours=completed.map(i=>new Date(i.scheduled_at).getHours());const evening=hours.filter(h=>h>=17).length;const morning=hours.filter(h=>h<12).length;const best=evening>morning?'evenings':morning>evening?'mornings':'mixed times';return[{title:'Strongest working window',description:`Completed work currently clusters around ${best}.`,confidence:completed.length?Math.round(Math.max(evening,morning)/completed.length*100):0},{title:'Execution load',description:`${completed.length} completed plan items were recorded in the last 60 days.`,confidence:completed.length?Math.min(100,completed.length*5):0},{title:'Disruption signal',description:adjustments.length?`${adjustments.length} recent plan adjustments suggest flexibility is useful.`:'No recent plan adjustments detected.',confidence:adjustments.length?Math.min(100,adjustments.length*15):0}]},[items,adjustments]);
 const archaeology=useMemo(()=>goals.filter(g=>g.status==='completed'||g.status==='abandoned').slice(0,8),[goals]);const scorecard=useMemo(()=>{const done=items.filter(i=>i.status==='completed').length;const total=items.filter(i=>i.status!=='cancelled').length;const moved=items.filter(i=>i.status==='moved').length;const healthAvg=activeRows.length?Math.round(activeRows.reduce((s,x)=>s+x.h.pct,0)/activeRows.length):0;return{execution:total?Math.round(done/total*100):0,health:healthAvg,adaptation:Math.min(100,moved?50+moved*5:100),awards:Math.min(100,awards.length*10)}},[items,activeRows,awards]);const recoveryCandidates=activeRows.filter(x=>x.h.overdue>=2);
 function toggleAccountability(){if(!session)return;const next=!accountability;setAccountability(next);saveLocal(session.user.id,'accountability',next)}function addMemory(){if(!session||!newMemory.trim())return;const next=[...memories,{id:crypto.randomUUID(),text:newMemory.trim(),createdAt:new Date().toISOString()}];setMemories(next);saveLocal(session.user.id,'memory',next);setNewMemory('')}function removeMemory(id:string){if(!session)return;const next=memories.filter(m=>m.id!==id);setMemories(next);saveLocal(session.user.id,'memory',next)}function addExperiment(){if(!session||!experimentGoal||!newHypothesis.trim()||!newApproach.trim())return;const next=[...experiments,{id:crypto.randomUUID(),goalId:experimentGoal,hypothesis:newHypothesis.trim(),approach:newApproach.trim(),status:'active' as const,createdAt:new Date().toISOString()}];setExperiments(next);saveLocal(session.user.id,'experiments',next);setNewHypothesis('');setNewApproach('')}function completeExperiment(id:string){if(!session)return;const next=experiments.map(e=>e.id===id?{...e,status:'completed' as const,outcome:'Completed and ready for reflection.'}:e);setExperiments(next);saveLocal(session.user.id,'experiments',next)}
 async function recover(g:Goal){if(!session||!online)return;const overdue=items.filter(i=>i.goal_id===g.id&&i.status==='scheduled'&&new Date(i.scheduled_at)<new Date()).slice(0,3);if(!overdue.length){setMessage('No overdue work needs recovery.');return}const base=new Date();base.setDate(base.getDate()+1);base.setHours(18,0,0,0);for(let n=0;n<overdue.length;n++){const at=new Date(base);at.setDate(base.getDate()+n);await supabase.from('goal_plan_items').update({scheduled_at:at.toISOString(),status:'moved'}).eq('id',overdue[n].id).eq('user_id',session.user.id)}await supabase.from('plan_adjustments').insert({user_id:session.user.id,goal_id:g.id,reason:'Recovery mode after disruption',proposed_change:`Rebuilt ${overdue.length} overdue task(s) into a short recovery sequence.`,status:'applied',applied_at:new Date().toISOString()});setMessage(`Recovery sequence created for ${titleOf(g)}.`);await load()}
 async function addDependency(){if(!session||!experimentGoal||!selectedDependency||experimentGoal===selectedDependency)return;const {error}=await supabase.from('goal_dependencies').insert({user_id:session.user.id,goal_id:experimentGoal,depends_on_goal_id:selectedDependency});if(error)setMessage('Could not add that dependency.');else{setSelectedDependency('');await load()}}
 return <div className="min-w-0"><PageHeader title="VOW Intelligence" subtitle="Turn execution history into better decisions, not just more tasks." />{!online&&<div className="border border-vow-border p-4 mb-6 text-sm text-vow-muted">You are offline. Existing intelligence remains visible; plan changes require a connection.</div>}{message&&<p className="text-sm text-vow-ink border-l-2 border-vow-ink pl-3 mb-6">{message}</p>}
 <section className="border border-vow-border p-5 mb-6"><p className="vow-label">Goal momentum</p><h2 className="vow-heading text-xl text-vow-ink mt-1">Which goals are moving?</h2><div className="mt-5 space-y-4">{momentum.length?momentum.map(x=><div key={x.g.id} className="border-t border-vow-border pt-4 flex items-center justify-between gap-4"><div><p className="text-sm text-vow-ink">{titleOf(x.g)}</p><p className="text-xs text-vow-muted mt-1">{x.trend} · {x.score}% momentum · {x.h.label}</p></div><span className="text-xs text-vow-muted">{x.h.overdue} overdue</span></div>):<p className="text-sm text-vow-muted">Create an active goal to build momentum data.</p>}</div></section>
 <section className="border border-vow-border p-5 mb-6"><p className="vow-label">Adaptive difficulty</p><h2 className="vow-heading text-xl text-vow-ink mt-1">Let performance calibrate the next step</h2><div className="mt-5 space-y-3">{momentum.map(x=><div key={x.g.id} className="border-t border-vow-border pt-3 text-sm text-vow-muted">{x.h.pct>=85?`Strong execution on ${titleOf(x.g)}. VOW can increase challenge gradually.`:x.h.pct<50?`${titleOf(x.g)} needs a smaller next step before adding load.`:`${titleOf(x.g)} is in a workable range. Keep difficulty steady and observe the next cycle.`}</div>)}</div></section>
 <section className="border border-vow-border p-5 mb-6"><p className="vow-label">Goal conflicts</p><h2 className="vow-heading text-xl text-vow-ink mt-1">Protect the schedule from collisions</h2>{conflicts.length?<div className="mt-5 space-y-3">{conflicts.map((c,i)=>{const ga=goals.find(g=>g.id===c.a.goal_id),gb=goals.find(g=>g.id===c.b.goal_id);return <div key={i} className="border-t border-vow-border pt-3 text-sm"><p className="text-vow-ink">{ga?titleOf(ga):'Goal'} ↔ {gb?titleOf(gb):'Goal'}</p><p className="text-xs text-vow-muted mt-1">Two scheduled tasks fall within 45 minutes of each other.</p></div>})}</div>:<p className="text-sm text-vow-muted mt-5">No cross-goal schedule collisions detected.</p>}</section>
 <section className="border border-vow-border p-5 mb-6"><p className="vow-label">Evidence</p><h2 className="vow-heading text-xl text-vow-ink mt-1">Show the work behind progress</h2><div className="mt-5 space-y-2">{completedEvidence.slice(0,8).map(i=><div key={i.id} className="border-t border-vow-border pt-3"><p className="text-sm text-vow-ink">{i.task}</p><p className="text-xs text-vow-muted mt-1">Completed · {new Date(i.scheduled_at).toLocaleDateString('en-GB')}</p></div>)}{!completedEvidence.length&&<p className="text-sm text-vow-muted">Complete plan items to build an evidence trail.</p>}</div></section>
 <section className="border border-vow-border p-5 mb-6"><p className="vow-label">Goal experiments</p><h2 className="vow-heading text-xl text-vow-ink mt-1">Test what actually works</h2><div className="grid gap-2 mt-5"><select value={experimentGoal} onChange={e=>setExperimentGoal(e.target.value)} className="vow-input"><option value="">Goal…</option>{activeRows.map(x=><option key={x.g.id} value={x.g.id}>{titleOf(x.g)}</option>)}</select><input value={newHypothesis} onChange={e=>setNewHypothesis(e.target.value)} className="vow-input" placeholder="Hypothesis"/><input value={newApproach} onChange={e=>setNewApproach(e.target.value)} className="vow-input" placeholder="Approach"/><button type="button" onClick={addExperiment} className="vow-btn-primary">Start experiment</button></div><div className="mt-5 space-y-3">{experiments.map(e=><div key={e.id} className="border-t border-vow-border pt-3"><p className="text-sm text-vow-ink">{e.hypothesis}</p><p className="text-xs text-vow-muted mt-1">{e.approach} · {e.status}</p>{e.status==='active'&&<button type="button" onClick={()=>completeExperiment(e.id)} className="text-xs text-vow-muted mt-2">Mark complete →</button>}</div>)}</div></section>
 <section className="border border-vow-border p-5 mb-6"><p className="vow-label">Operating patterns</p><h2 className="vow-heading text-xl text-vow-ink mt-1">How you tend to work</h2><div className="mt-5 space-y-3">{patterns.map(p=><div key={p.title} className="border-t border-vow-border pt-3"><p className="text-sm text-vow-ink">{p.title}</p><p className="text-xs text-vow-muted mt-1">{p.description} · {p.confidence}% signal</p></div>)}</div></section>
 <section className="border border-vow-border p-5 mb-6"><p className="vow-label">Recovery mode</p><h2 className="vow-heading text-xl text-vow-ink mt-1">Recover without rebuilding everything</h2><div className="mt-5 space-y-3">{recoveryCandidates.length?recoveryCandidates.map(x=><div key={x.g.id} className="border-t border-vow-border pt-3 flex items-center justify-between gap-3"><div><p className="text-sm text-vow-ink">{titleOf(x.g)}</p><p className="text-xs text-vow-muted mt-1">{x.h.overdue} overdue tasks</p></div><button type="button" disabled={!online} onClick={()=>recover(x.g)} className="vow-btn-soft">Recover plan</button></div>):<p className="text-sm text-vow-muted">No goals currently need recovery.</p>}</div></section>
 <section className="border border-vow-border p-5 mb-6"><p className="vow-label">Goal templates</p><h2 className="vow-heading text-xl text-vow-ink mt-1">Reusable planning patterns</h2><div className="grid sm:grid-cols-2 gap-3 mt-5">{['Skill building','Fitness consistency','Project delivery','Exam preparation'].map(t=><div key={t} className="border border-vow-border p-4"><p className="text-sm text-vow-ink">{t}</p><p className="text-xs text-vow-muted mt-1">Use a clear outcome, weekly commitment, evidence and review cycle.</p></div>)}</div></section>
 <section className="border border-vow-border p-5 mb-6"><p className="vow-label">Accountability</p><h2 className="vow-heading text-xl text-vow-ink mt-1">Choose stronger check-ins</h2><p className="text-sm text-vow-muted mt-2">Optional accountability keeps commitments visible without exposing private journal content.</p><button type="button" onClick={toggleAccountability} className="vow-btn-soft mt-5">{accountability?'Accountability on':'Turn accountability on'}</button></section>
 <section className="border border-vow-border p-5 mb-6"><p className="vow-label">Goal archaeology</p><h2 className="vow-heading text-xl text-vow-ink mt-1">Learn from old goals</h2><div className="mt-5 space-y-3">{archaeology.length?archaeology.map(g=><div key={g.id} className="border-t border-vow-border pt-3"><p className="text-sm text-vow-ink">{titleOf(g)}</p><p className="text-xs text-vow-muted mt-1">{g.status==='completed'?'Completed — keep the conditions that worked.':'Abandoned — identify the constraint before repeating the pattern.'}</p></div>):<p className="text-sm text-vow-muted">Completed and abandoned goals will become your history.</p>}</div></section>
 <section className="border border-vow-border p-5 mb-6"><p className="vow-label">VOW scorecard</p><h2 className="vow-heading text-xl text-vow-ink mt-1">A long-view execution signal</h2><div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mt-5">{Object.entries(scorecard).map(([k,v])=><div key={k} className="border-t border-vow-border pt-3"><p className="text-xs text-vow-muted capitalize">{k}</p><p className="text-xl text-vow-ink mt-1">{v}</p></div>)}</div></section>
 <section className="border border-vow-border p-5 mb-6"><p className="vow-label">AI check-ins</p><h2 className="vow-heading text-xl text-vow-ink mt-1">Ask the right question at the right time</h2><button type="button" onClick={()=>{const x=momentum[0];setCheckin(x?`${titleOf(x.g)} is ${x.trend} at ${x.score}% momentum. What is the smallest useful action you can complete next?`:'Create an active goal and VOW will generate a contextual check-in.')}} className="vow-btn-soft mt-5">Generate check-in</button>{checkin&&<p className="text-sm text-vow-ink mt-4 border-t border-vow-border pt-4">{checkin}</p>}</section>
 <section className="border border-vow-border p-5 mb-6"><p className="vow-label">VOW memory</p><h2 className="vow-heading text-xl text-vow-ink mt-1">Keep useful lessons close</h2><div className="flex gap-2 mt-5"><input value={newMemory} onChange={e=>setNewMemory(e.target.value)} className="vow-input flex-1" placeholder="A preference or lesson to remember"/><button type="button" onClick={addMemory} className="vow-btn-primary">Save</button></div><div className="mt-5 space-y-2">{memories.map(m=><div key={m.id} className="border-t border-vow-border pt-3 flex justify-between gap-3"><p className="text-sm text-vow-ink">{m.text}</p><button type="button" onClick={()=>removeMemory(m.id)} className="text-xs text-vow-muted">Remove</button></div>)}</div></section>
 <section className="border border-vow-border p-5"><p className="vow-label">Goal network</p><h2 className="vow-heading text-xl text-vow-ink mt-1">Dependencies</h2><div className="flex flex-col sm:flex-row gap-2 mt-5"><select value={experimentGoal} onChange={e=>setExperimentGoal(e.target.value)} className="vow-input"><option value="">Goal…</option>{goals.map(g=><option key={g.id} value={g.id}>{titleOf(g)}</option>)}</select><select value={selectedDependency} onChange={e=>setSelectedDependency(e.target.value)} className="vow-input"><option value="">Depends on…</option>{goals.map(g=><option key={g.id} value={g.id}>{titleOf(g)}</option>)}</select><button type="button" onClick={addDependency} className="vow-btn-primary">Add</button></div><div className="mt-5 space-y-2">{deps.map(d=>{const a=goals.find(g=>g.id===d.goal_id),b=goals.find(g=>g.id===d.depends_on_goal_id);return <div key={d.id} className="flex justify-between border-t border-vow-border pt-3 text-sm"><span>{a?titleOf(a):'Goal'} ← {b?titleOf(b):'Goal'}</span></div>})}</div></section></div>;
}
