CREATE OR REPLACE FUNCTION public.armadillo_analyse_goal(goal_title text, goal_outcome text DEFAULT NULL, goal_why text DEFAULT NULL)
RETURNS jsonb LANGUAGE plpgsql IMMUTABLE SET search_path = public, pg_temp AS $$
DECLARE
  t text := lower(trim(concat_ws(' ', coalesce(goal_title,''), coalesce(goal_outcome,''), coalesce(goal_why,''))));
  category text := 'General'; goal_type text := 'Goal'; metric text := 'measurable progress toward the stated outcome';
  target text := NULL; direction text := 'progress'; secondary_metric text := NULL; time_target text := NULL;
  integration text := NULL; planning_strategy text := 'define the clearest measurable outcome, then break it into small repeatable actions';
  evidence jsonb := jsonb_build_array('manual progress updates','goal milestones','completed sessions or actions');
  evidence_source jsonb := jsonb_build_array('manual tracking'); needs_clarification boolean := false;
  clarification_reasons jsonb := '[]'::jsonb; confidence numeric := 0.55; m text[];
BEGIN
  IF t ~ '(run|running|5k|10k|marathon|half marathon|mile|km)' THEN category := 'Sports'; goal_type := 'Running'; metric := 'distance'; evidence := jsonb_build_array('activity distance','activity duration','activity pace'); integration := 'Strava'; planning_strategy := 'progressive running sessions with gradual workload changes';
  ELSIF t ~ '(cycle|cycling|bike|biking|ride|kilometre|kilometer)' THEN category := 'Sports'; goal_type := 'Cycling'; metric := 'distance'; evidence := jsonb_build_array('ride distance','ride duration','ride speed'); integration := 'Strava'; planning_strategy := 'progressive rides with endurance and recovery';
  ELSIF t ~ '(swim|swimming|pool|freestyle|laps)' THEN category := 'Sports'; goal_type := 'Swimming'; metric := 'distance, duration'; evidence := jsonb_build_array('swim distance','swim duration','completed sessions'); integration := 'Strava'; planning_strategy := 'progressive swim sessions with technique and recovery';
  ELSIF t ~ '(football|soccer|match|football training)' THEN category := 'Sports'; goal_type := 'Football'; metric := 'sessions, minutes, performance'; evidence := jsonb_build_array('training sessions','match activity','manual performance notes'); integration := 'Strava'; planning_strategy := 'structured practice, match work and recovery';
  ELSIF t ~ '(study|revise|revision|exam|homework|learn|learning|physics|chemistry|biology|maths|mathematics)' THEN category := 'Education'; goal_type := 'Study'; metric := 'study time, task completion, accuracy'; evidence := jsonb_build_array('study sessions','completed tasks','practice results'); integration := 'Google Calendar'; planning_strategy := 'scheduled focused study with spaced practice and checkpoints';
  ELSIF t ~ '(read|reading|book|books|pages)' THEN category := 'Reading'; goal_type := 'Reading'; metric := 'pages, books, reading time'; evidence := jsonb_build_array('pages read','books completed','reading sessions'); planning_strategy := 'consistent reading sessions measured by the clearest available reading metric';
  ELSIF t ~ '(meditate|meditation|mindfulness)' THEN category := 'Mindfulness'; goal_type := 'Meditation'; metric := 'sessions, duration'; evidence := jsonb_build_array('meditation sessions','meditation duration'); integration := 'Medito'; planning_strategy := 'short, repeatable sessions with gradual consistency building';
  ELSIF t ~ '(github|commit|commits|pull request|contribution|coding project)' THEN category := 'Technology/Projects'; goal_type := 'GitHub Contributions'; metric := 'contributions, pull requests, commits'; evidence := jsonb_build_array('GitHub activity','pull requests','commits'); integration := 'GitHub'; planning_strategy := 'break the project into concrete deliverables and ship incrementally';
  ELSIF t ~ '(portfolio|project|career|cv|resume|job|application|internship)' THEN category := 'Career/Projects'; goal_type := 'Project'; metric := 'deliverables, milestones, completion'; evidence := jsonb_build_array('project milestones','completed deliverables','project review'); integration := 'Google Calendar'; planning_strategy := 'sequence concrete deliverables into weekly execution blocks';
  ELSIF t ~ '(save|saving|savings|money|budget|financial|finance)' THEN category := 'Finance'; goal_type := 'Saving'; metric := 'money saved'; evidence := jsonb_build_array('manual savings updates','transaction records when available','milestones'); planning_strategy := 'set measurable savings checkpoints and review progress regularly';
  ELSIF t ~ '(music|song|guitar|piano|draw|drawing|paint|painting|write|writing|novel|creative)' THEN category := 'Creative'; goal_type := 'Creative Practice'; metric := 'sessions, completed pieces'; evidence := jsonb_build_array('practice sessions','completed pieces','project milestones'); planning_strategy := 'turn the creative outcome into repeatable practice and deliverables';
  END IF;
  m := regexp_match(t, '(\d+(?:\.\d+)?)\s*(km|kilometres?|kilometers?|miles?|mi|pages?|books?|hours?|hrs?|minutes?|mins?|sessions?)');
  IF m IS NOT NULL THEN target := m[1] || ' ' || m[2]; END IF;
  IF target IS NULL AND t ~ '\m(5k|10k|half marathon|marathon)\M' THEN target := (regexp_match(t, '\m(5k|10k|half marathon|marathon)\M'))[1]; END IF;
  IF target IS NULL THEN m := regexp_match(t, '(?:save|saving|budget)\s+(?:of\s+)?([$£€]?\s*\d+(?:[,.]\d+)?)'); IF m IS NOT NULL THEN target := trim(m[1]); END IF; END IF;
  m := regexp_match(t, '(under|below|within)\s+(\d+(?:\.\d+)?)\s*(hours?|hrs?|minutes?|mins?)');
  IF m IS NOT NULL THEN time_target := m[1] || ' ' || m[2] || ' ' || m[3]; secondary_metric := 'time'; ELSIF t ~ '(under|below|within)\s+(an?|one)\s+hour' THEN time_target := 'under 60 minutes'; secondary_metric := 'time'; END IF;
  IF t ~ '(reduce|decrease|lower|cut|spend less)' THEN direction := 'decrease'; ELSIF t ~ '(maintain|keep|sustain)' THEN direction := 'maintain'; ELSIF t ~ '(finish|complete|ship|submit|deliver)' THEN direction := 'complete'; ELSIF t ~ '(improve|increase|grow|raise|more|faster|better)' THEN direction := 'increase'; ELSIF t ~ '(build|develop|establish|learn|practice)' THEN direction := 'build'; END IF;
  IF integration IS NOT NULL THEN evidence_source := jsonb_build_array(integration,'manual tracking'); END IF;
  IF goal_type = 'Goal' OR (t ~ '(get better|improve|do more|be better|get fit|work on|try to)' AND target IS NULL) THEN needs_clarification := true; clarification_reasons := jsonb_build_array('The goal needs a clearer measurable outcome before a personalised plan can be precise.'); END IF;
  IF category <> 'General' THEN confidence := CASE WHEN needs_clarification THEN 0.78 ELSE 0.94 END; END IF;
  RETURN jsonb_build_object('category',category,'goal_type',goal_type,'metric',metric,'target',target,'direction',direction,'secondary_metric',secondary_metric,'time_target',time_target,'evidence',evidence,'evidence_source',evidence_source,'integration',integration,'planning_strategy',planning_strategy,'needs_clarification',needs_clarification,'clarification_reasons',clarification_reasons,'fallback','Manual tracking remains the source of truth if an integration is unavailable or not connected.','confidence',confidence);
END; $$;
