create table if not exists public.goal_dependencies (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, goal_id uuid not null references public.goals(id) on delete cascade, depends_on_goal_id uuid not null references public.goals(id) on delete cascade, created_at timestamptz not null default now(), constraint goal_dependencies_no_self check (goal_id <> depends_on_goal_id), constraint goal_dependencies_unique unique (goal_id, depends_on_goal_id));
create table if not exists public.plan_adjustments (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, goal_id uuid not null references public.goals(id) on delete cascade, reason text not null, proposed_change text not null, status text not null default 'proposed', created_at timestamptz not null default now(), applied_at timestamptz);
create table if not exists public.user_entitlements (user_id uuid primary key references auth.users(id) on delete cascade, plan text not null default 'free', status text not null default 'inactive', source text not null default 'none', expires_at timestamptz, updated_at timestamptz not null default now());
create table if not exists public.data_requests (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, request_type text not null, status text not null default 'requested', created_at timestamptz not null default now(), completed_at timestamptz);
alter table public.moderation_events add column if not exists risk_level text, add column if not exists review_status text not null default 'pending', add column if not exists cooldown_until timestamptz, add column if not exists owner_alerted_at timestamptz;
create index if not exists goal_dependencies_user_idx on public.goal_dependencies(user_id);
create index if not exists plan_adjustments_goal_idx on public.plan_adjustments(goal_id, created_at desc);
create index if not exists moderation_events_risk_created_idx on public.moderation_events(risk_level, created_at desc);
alter table public.goal_dependencies enable row level security;
alter table public.plan_adjustments enable row level security;
alter table public.user_entitlements enable row level security;
alter table public.data_requests enable row level security;
grant select, insert, update, delete on public.goal_dependencies to authenticated;
grant select, insert, update on public.plan_adjustments to authenticated;
grant select on public.user_entitlements to authenticated;
grant select, insert on public.data_requests to authenticated;
create policy "Users manage own goal dependencies" on public.goal_dependencies for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "Users manage own plan adjustments" on public.plan_adjustments for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "Users view own entitlement" on public.user_entitlements for select to authenticated using ((select auth.uid()) = user_id);
create policy "Users manage own data requests" on public.data_requests for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
