-- Expand VOW's reusable planning knowledge for broad goal families.
-- Armadillo classifies the goal; the AI planner uses these principles to build
-- a progressive, personalised sequence rather than repeating the same task.

insert into public.vow_knowledge
  (domain, topic, title, content, principles, recommended_actions, metrics, cautions, active)
values
  ('learning', 'skill_acquisition', 'Beginner skill progression',
   'For a new practical or creative skill, start by establishing the learner baseline and defining the desired real-world outcome. Teach the minimum foundations first, then use progressively harder practice, application and checkpoints. If the learner provides no experience information, treat the starting point as Level 1 beginner rather than inventing prior knowledge.',
   '["Establish baseline before prescribing difficulty","Break complex skills into prerequisite subskills","Move from demonstration to guided practice to independent application","Increase difficulty only after the current stage is reliable","Use checkpoints to decide whether to progress, repeat or adjust"]'::jsonb,
   '["Ask about prior experience","Ask what the learner wants to be able to do","Ask about available time and practical constraints","Teach one or two foundational skills first","Use a small real-world application before increasing complexity","Review progress at a meaningful milestone"]'::jsonb,
   '["skills_mastered","successful_repetitions","practice_sessions","completed_applications","project_completion"]'::jsonb,
   '["Do not assume expertise from the goal wording alone","Do not make every day identical","Do not increase difficulty simply because another week has started"]'::jsonb,
   true),
  ('learning', 'skill_acquisition', 'Unknown-skill baseline',
   'When a user says learn, master, improve or become able to do something but gives no baseline, the safest useful default is a Level 1 plan. Start with terminology, equipment or environment orientation, basic technique and a very small success criterion before moving to more advanced work.',
   '["Introduce the environment and essential terms","Demonstrate the first fundamental","Use a short controlled exercise","Check understanding or execution","Repeat with a small increase in difficulty"]'::jsonb,
   '["Start from the simplest prerequisite","Give a concrete first exercise","Define what success looks like","Delay advanced techniques until foundations are stable"]'::jsonb,
   '["first_skill_completed","successful_repetitions","practice_consistency","foundation_checkpoint"]'::jsonb,
   '["Never fabricate a user baseline","Avoid overwhelming beginners with advanced theory or too many techniques at once"]'::jsonb,
   true),
  ('creative', 'crafts', 'Craft and making progression',
   'Craft goals such as crochet, knitting, sewing, pottery, woodworking or model making should progress from materials and terminology to basic techniques, controlled exercises, combining techniques and a guided project, then toward an independent project.',
   '["Learn tools and materials before complex construction","Practise individual techniques","Combine techniques only after their components are understood","Use a progressively harder project as the main application"]'::jsonb,
   '["Identify tools and materials","Practise a foundational technique","Complete a small sample","Follow a beginner project","Modify or create a small independent project"]'::jsonb,
   '["techniques_mastered","practice_sessions","samples_completed","projects_completed"]'::jsonb,
   '["Use appropriate tool and material safety guidance","Do not jump directly to a complex project when prerequisites are missing"]'::jsonb,
   true),
  ('creative', 'photography', 'Photography progression',
   'Photography goals should move from camera or phone controls and composition fundamentals into focused shooting exercises, review, editing and a coherent final photo set. The exact sequence should adapt to the equipment and intended photography style.',
   '["Learn one camera control at a time","Practise composition deliberately","Review results and identify one improvement","Apply techniques in increasingly varied conditions"]'::jsonb,
   '["Establish equipment baseline","Practise focus and exposure","Shoot a constrained exercise","Review a small set","Complete a themed photo set"]'::jsonb,
   '["shoots_completed","selected_images","technical_exercises","photo_set_completion"]'::jsonb,
   '["Do not assume professional equipment","Avoid treating gear purchases as the main form of progress"]'::jsonb,
   true),
  ('creative', 'music', 'Instrument and music progression',
   'Music goals should progress from setup and basic technique to rhythm or notation where relevant, simple controlled exercises, short pieces, transitions and eventually independent performance or creation.',
   '["Prioritise clean fundamentals","Practise difficult sections slowly","Connect technical drills to real music","Increase complexity only when control is reliable"]'::jsonb,
   '["Establish instrument and baseline","Practise one technical foundation","Learn a short section","Connect sections","Perform or record a complete piece"]'::jsonb,
   '["practice_sessions","clean_repetitions","pieces_started","pieces_completed","performance_runs"]'::jsonb,
   '["Avoid repetitive practice when technique is deteriorating","Do not equate speed with mastery"]'::jsonb,
   true),
  ('practical', 'cooking', 'Cooking skill progression',
   'Cooking goals should progress from kitchen setup and basic safety to core techniques, simple dishes, combining techniques and increasingly independent meals. Plans should adapt to dietary requirements, equipment, cuisine and the intended outcome.',
   '["Master core techniques before complex recipes","Use small dishes to practise one technique at a time","Increase independence gradually","Review results and adjust technique"]'::jsonb,
   '["Establish kitchen and equipment baseline","Practise a basic technique","Cook a simple dish","Combine two or more techniques","Complete a meal independently"]'::jsonb,
   '["techniques_mastered","dishes_completed","practice_sessions","successful_meals"]'::jsonb,
   '["Follow appropriate food safety guidance","Do not assume access to specific equipment or ingredients"]'::jsonb,
   true),
  ('languages', 'language_learning', 'Language acquisition progression',
   'Language-learning goals should progress through high-value vocabulary and pronunciation into sentence formation, listening and reading comprehension, guided speaking and writing, then increasingly independent real-world use. Personalise by target language, current level and intended use.',
   '["Use the target language actively","Space practice over time","Connect vocabulary to context","Balance input and output","Track recurring errors"]'::jsonb,
   '["Establish current level","Build a small high-frequency vocabulary base","Practise short sentences","Add listening and speaking","Use realistic conversations or writing tasks"]'::jsonb,
   '["vocabulary_retained","comprehension_accuracy","speaking_minutes","writing_tasks","recurring_errors"]'::jsonb,
   '["Do not reduce language learning to vocabulary memorisation alone","Do not assume zero or advanced proficiency without asking"]'::jsonb,
   true),
  ('technology', 'programming', 'Programming skill progression',
   'Programming goals should move from environment setup and core concepts into small exercises, debugging, a focused project, testing and shipping. The plan should adapt to the language, framework and desired application.',
   '["Learn by building","Keep exercises small","Treat debugging as learning","Test working behaviour","Ship incremental outcomes"]'::jsonb,
   '["Establish language and tooling baseline","Build tiny programs","Debug deliberately","Implement one focused feature","Test and ship a small project"]'::jsonb,
   '["concepts_demonstrated","features_completed","bugs_fixed","tests_passing","projects_shipped"]'::jsonb,
   '["Do not copy code without understanding it","Never place secrets in client-side source code"]'::jsonb,
   true),
  ('communication', 'public_speaking', 'Communication skill progression',
   'Public speaking, presenting and debate goals should progress from message structure and short low-pressure practice to timed rehearsals, feedback and a complete delivery.',
   '["Clarify the core message","Practise aloud","Increase audience and duration gradually","Use feedback to target one improvement"]'::jsonb,
   '["Define the message","Deliver a short version","Record or rehearse","Practise with a small audience","Deliver the full presentation"]'::jsonb,
   '["rehearsals","delivery_duration","feedback_items","complete_deliveries"]'::jsonb,
   '["Do not require memorising every word","Keep progression realistic for the available audience and setting"]'::jsonb,
   true),
  ('sports', 'skill_sports', 'Sports skill progression',
   'Skill-based sports should progress from safety, equipment and movement fundamentals into isolated technique, controlled drills, variable practice, game or real-world application and performance review. Endurance sports should additionally manage workload progression and recovery.',
   '["Establish experience and physical baseline","Teach foundational movement or technique","Use controlled repetition","Apply skills under realistic constraints","Review performance and adjust"]'::jsonb,
   '["Ask about experience and access","Practise a fundamental skill","Use a controlled drill","Increase complexity or variability","Apply the skill in realistic conditions"]'::jsonb,
   '["sessions_completed","skill_checkpoints","successful_repetitions","performance_notes"]'::jsonb,
   '["Use appropriate safety and supervision for the activity","Avoid sudden workload increases","Do not confuse advanced terminology with demonstrated skill"]'::jsonb,
   true),
  ('projects', 'project_execution', 'Outcome-to-deliverable progression',
   'For projects, VOW should convert the desired outcome into dependencies and concrete deliverables. The plan should progress from definition and setup to the smallest useful output, iteration, quality checks and completion.',
   '["Define the finished outcome","Identify dependencies","Ship small increments","Review evidence at checkpoints","Finish rather than endlessly expand scope"]'::jsonb,
   '["Write acceptance criteria","Break the outcome into deliverables","Schedule the first useful output","Review blockers","Complete and verify the final outcome"]'::jsonb,
   '["deliverables_completed","milestones_completed","blocked_items","acceptance_criteria_met"]'::jsonb,
   '["Do not create activity for activity sake","Avoid adding scope that does not serve the stated outcome"]'::jsonb,
   true)
on conflict (domain, topic, title) do update set
  content = excluded.content,
  principles = excluded.principles,
  recommended_actions = excluded.recommended_actions,
  metrics = excluded.metrics,
  cautions = excluded.cautions,
  active = true,
  updated_at = now();
